ROMBLOCK 72, $0000
.SECTION "AutoLayout0" FORCE
AutoLayout0:
.incbin "auto_layout_000.bin"
.ENDS
ROMBLOCK 72, $0cea
.SECTION "AutoGuard0" FORCE
AutoGuard0:
.incbin "auto_guard_000.bin"
.ENDS
ROMBLOCK 72, $0d04
.SECTION "AutoGuard1" FORCE
AutoGuard1:
.incbin "auto_guard_001.bin"
.ENDS
ROMBLOCK 72, $0d1e
.SECTION "AutoLayout1" FORCE
AutoLayout1:
.incbin "auto_layout_001.bin"
.ENDS
ROMBLOCK 72, $19ff
.SECTION "AutoGuard2" FORCE
AutoGuard2:
.incbin "auto_guard_002.bin"
.ENDS
ROMBLOCK 72, $1a19
.SECTION "AutoGuard3" FORCE
AutoGuard3:
.incbin "auto_guard_003.bin"
.ENDS
ROMBLOCK 72, $1a33
.SECTION "AutoGuard4" FORCE
AutoGuard4:
.incbin "auto_guard_004.bin"
.ENDS
ROMBLOCK 72, $1a4d
.SECTION "AutoGuard5" FORCE
AutoGuard5:
.incbin "auto_guard_005.bin"
.ENDS
ROMBLOCK 72, $1a67
.SECTION "AutoGuard6" FORCE
AutoGuard6:
.incbin "auto_guard_006.bin"
.ENDS
ROMBLOCK 72, $1a81
.SECTION "AutoGuard7" FORCE
AutoGuard7:
.incbin "auto_guard_007.bin"
.ENDS
ROMBLOCK 72, $1a9b
.SECTION "AutoGuard8" FORCE
AutoGuard8:
.incbin "auto_guard_008.bin"
.ENDS
ROMBLOCK 72, $1ab5
.SECTION "AutoGuard9" FORCE
AutoGuard9:
.incbin "auto_guard_009.bin"
.ENDS
ROMBLOCK 72, $1acf
.SECTION "AutoGuard10" FORCE
AutoGuard10:
.incbin "auto_guard_010.bin"
.ENDS
ROMBLOCK 72, $1ae9
.SECTION "AutoGuard11" FORCE
AutoGuard11:
.incbin "auto_guard_011.bin"
.ENDS
ROMBLOCK 72, $1b03
.SECTION "AutoGuard12" FORCE
AutoGuard12:
.incbin "auto_guard_012.bin"
.ENDS
ROMBLOCK 72, $1b1d
.SECTION "AutoGuard13" FORCE
AutoGuard13:
.incbin "auto_guard_013.bin"
.ENDS
ROMBLOCK 72, $1b37
.SECTION "AutoGuard14" FORCE
AutoGuard14:
.incbin "auto_guard_014.bin"
.ENDS
ROMBLOCK 72, $1b51
.SECTION "AutoGuard15" FORCE
AutoGuard15:
.incbin "auto_guard_015.bin"
.ENDS
ROMBLOCK 72, $1b6b
.SECTION "AutoGuard16" FORCE
AutoGuard16:
.incbin "auto_guard_016.bin"
.ENDS
ROMBLOCK 72, $1b85
.SECTION "AutoGuard17" FORCE
AutoGuard17:
.incbin "auto_guard_017.bin"
.ENDS
ROMBLOCK 72, $1b9f
.SECTION "AutoLayout2" FORCE
AutoLayout2:
.incbin "auto_layout_002.bin"
.ENDS
ROMBLOCK 72, $3744
.SECTION "AutoGuard18" FORCE
AutoGuard18:
.incbin "auto_guard_018.bin"
.ENDS
ROMBLOCK 72, $375e
.SECTION "AutoLayout3" FORCE
AutoLayout3:
.incbin "auto_layout_003.bin"
.ENDS
ROMBLOCK 72, $52fd
.SECTION "AutoGuard19" FORCE
AutoGuard19:
.incbin "auto_guard_019.bin"
.ENDS
ROMBLOCK 72, $5317
.SECTION "AutoLayout4" FORCE
AutoLayout4:
.incbin "auto_layout_004.bin"
.ENDS
ROMBLOCK 72, $6ec5
.SECTION "AutoGuard20" FORCE
AutoGuard20:
.incbin "auto_guard_020.bin"
.ENDS
ROMBLOCK 73, $0000
.SECTION "AutoLayout5" FORCE
AutoLayout5:
.incbin "auto_layout_005.bin"
.ENDS
ROMBLOCK 73, $1bb7
.SECTION "AutoGuard21" FORCE
AutoGuard21:
.incbin "auto_guard_021.bin"
.ENDS
ROMBLOCK 73, $1bd5
.SECTION "AutoLayout6" FORCE
AutoLayout6:
.incbin "auto_layout_006.bin"
.ENDS
ROMBLOCK 73, $3789
.SECTION "AutoGuard22" FORCE
AutoGuard22:
.incbin "auto_guard_022.bin"
.ENDS
ROMBLOCK 73, $37a7
.SECTION "AutoGuard23" FORCE
AutoGuard23:
.incbin "auto_guard_023.bin"
.ENDS
ROMBLOCK 73, $37c9
.SECTION "AutoGuard24" FORCE
AutoGuard24:
.incbin "auto_guard_024.bin"
.ENDS
ROMBLOCK 73, $37ef
.SECTION "AutoGuard25" FORCE
AutoGuard25:
.incbin "auto_guard_025.bin"
.ENDS
ROMBLOCK 73, $3815
.SECTION "AutoLayout7" FORCE
AutoLayout7:
.incbin "auto_layout_007.bin"
.ENDS
ROMBLOCK 73, $464c
.SECTION "AutoGuard26" FORCE
AutoGuard26:
.incbin "auto_guard_026.bin"
.ENDS
ROMBLOCK 73, $466a
.SECTION "AutoGuard27" FORCE
AutoGuard27:
.incbin "auto_guard_027.bin"
.ENDS
ROMBLOCK 73, $4688
.SECTION "AutoGuard28" FORCE
AutoGuard28:
.incbin "auto_guard_028.bin"
.ENDS
ROMBLOCK 73, $46a6
.SECTION "AutoGuard29" FORCE
AutoGuard29:
.incbin "auto_guard_029.bin"
.ENDS
ROMBLOCK 73, $46c4
.SECTION "AutoLayout8" FORCE
AutoLayout8:
.incbin "auto_layout_008.bin"
.ENDS
ROMBLOCK 73, $5ccc
.SECTION "AutoGuard30" FORCE
AutoGuard30:
.incbin "auto_guard_030.bin"
.ENDS
ROMBLOCK 73, $5ce6
.SECTION "AutoLayout9" FORCE
AutoLayout9:
.incbin "auto_layout_009.bin"
.ENDS
ROMBLOCK 73, $7312
.SECTION "AutoGuard31" FORCE
AutoGuard31:
.incbin "auto_guard_031.bin"
.ENDS
ROMBLOCK 74, $0000
.SECTION "AutoLayout10" FORCE
AutoLayout10:
.incbin "auto_layout_010.bin"
.ENDS
ROMBLOCK 74, $160b
.SECTION "AutoGuard32" FORCE
AutoGuard32:
.incbin "auto_guard_032.bin"
.ENDS
ROMBLOCK 74, $1625
.SECTION "AutoLayout11" FORCE
AutoLayout11:
.incbin "auto_layout_011.bin"
.ENDS
ROMBLOCK 74, $2c2d
.SECTION "AutoGuard33" FORCE
AutoGuard33:
.incbin "auto_guard_033.bin"
.ENDS
ROMBLOCK 74, $2c47
.SECTION "AutoLayout12" FORCE
AutoLayout12:
.incbin "auto_layout_012.bin"
.ENDS
ROMBLOCK 74, $424f
.SECTION "AutoGuard34" FORCE
AutoGuard34:
.incbin "auto_guard_034.bin"
.ENDS
ROMBLOCK 74, $4269
.SECTION "AutoLayout13" FORCE
AutoLayout13:
.incbin "auto_layout_013.bin"
.ENDS
ROMBLOCK 74, $58a4
.SECTION "AutoGuard35" FORCE
AutoGuard35:
.incbin "auto_guard_035.bin"
.ENDS
ROMBLOCK 74, $58be
.SECTION "AutoLayout14" FORCE
AutoLayout14:
.incbin "auto_layout_014.bin"
.ENDS
ROMBLOCK 74, $6ecf
.SECTION "AutoGuard36" FORCE
AutoGuard36:
.incbin "auto_guard_036.bin"
.ENDS
ROMBLOCK 75, $0000
.SECTION "AutoLayout15" FORCE
AutoLayout15:
.incbin "auto_layout_015.bin"
.ENDS
ROMBLOCK 75, $162f
.SECTION "AutoGuard37" FORCE
AutoGuard37:
.incbin "auto_guard_037.bin"
.ENDS
ROMBLOCK 75, $1649
.SECTION "AutoLayout16" FORCE
AutoLayout16:
.incbin "auto_layout_016.bin"
.ENDS
ROMBLOCK 75, $3152
.SECTION "AutoGuard38" FORCE
AutoGuard38:
.incbin "auto_guard_038.bin"
.ENDS
ROMBLOCK 75, $3168
.SECTION "AutoLayout17" FORCE
AutoLayout17:
.incbin "auto_layout_017.bin"
.ENDS
ROMBLOCK 75, $4c6b
.SECTION "AutoGuard39" FORCE
AutoGuard39:
.incbin "auto_guard_039.bin"
.ENDS
ROMBLOCK 75, $4c85
.SECTION "AutoLayout18" FORCE
AutoLayout18:
.incbin "auto_layout_018.bin"
.ENDS
ROMBLOCK 75, $6785
.SECTION "AutoGuard40" FORCE
AutoGuard40:
.incbin "auto_guard_040.bin"
.ENDS
ROMBLOCK 76, $0000
.SECTION "AutoLayout19" FORCE
AutoLayout19:
.incbin "auto_layout_019.bin"
.ENDS
ROMBLOCK 76, $1b06
.SECTION "AutoGuard41" FORCE
AutoGuard41:
.incbin "auto_guard_041.bin"
.ENDS
ROMBLOCK 76, $1b20
.SECTION "AutoLayout20" FORCE
AutoLayout20:
.incbin "auto_layout_020.bin"
.ENDS
ROMBLOCK 76, $362f
.SECTION "AutoGuard42" FORCE
AutoGuard42:
.incbin "auto_guard_042.bin"
.ENDS
ROMBLOCK 76, $3649
.SECTION "AutoLayout21" FORCE
AutoLayout21:
.incbin "auto_layout_021.bin"
.ENDS
ROMBLOCK 76, $5164
.SECTION "AutoGuard43" FORCE
AutoGuard43:
.incbin "auto_guard_043.bin"
.ENDS
ROMBLOCK 76, $517e
.SECTION "AutoLayout22" FORCE
AutoLayout22:
.incbin "auto_layout_022.bin"
.ENDS
ROMBLOCK 76, $6c93
.SECTION "AutoGuard44" FORCE
AutoGuard44:
.incbin "auto_guard_044.bin"
.ENDS
ROMBLOCK 77, $0000
.SECTION "AutoLayout23" FORCE
AutoLayout23:
.incbin "auto_layout_023.bin"
.ENDS
ROMBLOCK 77, $1bed
.SECTION "AutoGuard45" FORCE
AutoGuard45:
.incbin "auto_guard_045.bin"
.ENDS
ROMBLOCK 77, $1c07
.SECTION "AutoLayout24" FORCE
AutoLayout24:
.incbin "auto_layout_024.bin"
.ENDS
ROMBLOCK 77, $371f
.SECTION "AutoGuard46" FORCE
AutoGuard46:
.incbin "auto_guard_046.bin"
.ENDS
ROMBLOCK 77, $3739
.SECTION "AutoLayout25" FORCE
AutoLayout25:
.incbin "auto_layout_025.bin"
.ENDS
ROMBLOCK 77, $524e
.SECTION "AutoGuard47" FORCE
AutoGuard47:
.incbin "auto_guard_047.bin"
.ENDS
ROMBLOCK 77, $5268
.SECTION "AutoLayout26" FORCE
AutoLayout26:
.incbin "auto_layout_026.bin"
.ENDS
ROMBLOCK 77, $6d74
.SECTION "AutoGuard48" FORCE
AutoGuard48:
.incbin "auto_guard_048.bin"
.ENDS
ROMBLOCK 78, $0000
.SECTION "AutoLayout27" FORCE
AutoLayout27:
.incbin "auto_layout_027.bin"
.ENDS
ROMBLOCK 78, $1b12
.SECTION "AutoGuard49" FORCE
AutoGuard49:
.incbin "auto_guard_049.bin"
.ENDS
ROMBLOCK 78, $1b2c
.SECTION "AutoLayout28" FORCE
AutoLayout28:
.incbin "auto_layout_028.bin"
.ENDS
ROMBLOCK 78, $39ce
.SECTION "AutoGuard50" FORCE
AutoGuard50:
.incbin "auto_guard_050.bin"
.ENDS
ROMBLOCK 78, $39e8
.SECTION "AutoLayout29" FORCE
AutoLayout29:
.incbin "auto_layout_029.bin"
.ENDS
ROMBLOCK 78, $5f1a
.SECTION "AutoGuard51" FORCE
AutoGuard51:
.incbin "auto_guard_051.bin"
.ENDS
ROMBLOCK 79, $0000
.SECTION "AutoLayout30" FORCE
AutoLayout30:
.incbin "auto_layout_030.bin"
.ENDS
ROMBLOCK 79, $253b
.SECTION "AutoGuard52" FORCE
AutoGuard52:
.incbin "auto_guard_052.bin"
.ENDS
ROMBLOCK 79, $2555
.SECTION "AutoLayout31" FORCE
AutoLayout31:
.incbin "auto_layout_031.bin"
.ENDS
ROMBLOCK 79, $451a
.SECTION "AutoGuard53" FORCE
AutoGuard53:
.incbin "auto_guard_053.bin"
.ENDS
ROMBLOCK 79, $4534
.SECTION "AutoLayout32" FORCE
AutoLayout32:
.incbin "auto_layout_032.bin"
.ENDS
ROMBLOCK 79, $6c79
.SECTION "AutoGuard54" FORCE
AutoGuard54:
.incbin "auto_guard_054.bin"
.ENDS
ROMBLOCK 80, $0000
.SECTION "AutoLayout33" FORCE
AutoLayout33:
.incbin "auto_layout_033.bin"
.ENDS
ROMBLOCK 80, $2727
.SECTION "AutoGuard55" FORCE
AutoGuard55:
.incbin "auto_guard_055.bin"
.ENDS
ROMBLOCK 80, $2741
.SECTION "AutoLayout34" FORCE
AutoLayout34:
.incbin "auto_layout_034.bin"
.ENDS
ROMBLOCK 80, $4514
.SECTION "AutoGuard56" FORCE
AutoGuard56:
.incbin "auto_guard_056.bin"
.ENDS
ROMBLOCK 80, $452a
.SECTION "AutoLayout35" FORCE
AutoLayout35:
.incbin "auto_layout_035.bin"
.ENDS
ROMBLOCK 80, $6393
.SECTION "AutoGuard57" FORCE
AutoGuard57:
.incbin "auto_guard_057.bin"
.ENDS
ROMBLOCK 81, $0000
.SECTION "AutoLayout36" FORCE
AutoLayout36:
.incbin "auto_layout_036.bin"
.ENDS
ROMBLOCK 81, $1ee4
.SECTION "AutoGuard58" FORCE
AutoGuard58:
.incbin "auto_guard_058.bin"
.ENDS
ROMBLOCK 81, $1efa
.SECTION "AutoLayout37" FORCE
AutoLayout37:
.incbin "auto_layout_037.bin"
.ENDS
ROMBLOCK 81, $3d21
.SECTION "AutoGuard59" FORCE
AutoGuard59:
.incbin "auto_guard_059.bin"
.ENDS
ROMBLOCK 81, $3d37
.SECTION "AutoLayout38" FORCE
AutoLayout38:
.incbin "auto_layout_038.bin"
.ENDS
ROMBLOCK 81, $5b4c
.SECTION "AutoGuard60" FORCE
AutoGuard60:
.incbin "auto_guard_060.bin"
.ENDS
ROMBLOCK 81, $5b62
.SECTION "AutoLayout39" FORCE
AutoLayout39:
.incbin "auto_layout_039.bin"
.ENDS
ROMBLOCK 81, $7a5e
.SECTION "AutoGuard61" FORCE
AutoGuard61:
.incbin "auto_guard_061.bin"
.ENDS
ROMBLOCK 82, $0000
.SECTION "AutoLayout40" FORCE
AutoLayout40:
.incbin "auto_layout_040.bin"
.ENDS
ROMBLOCK 82, $1dbe
.SECTION "AutoGuard62" FORCE
AutoGuard62:
.incbin "auto_guard_062.bin"
.ENDS
ROMBLOCK 82, $1dd4
.SECTION "AutoLayout41" FORCE
AutoLayout41:
.incbin "auto_layout_041.bin"
.ENDS
ROMBLOCK 82, $3c10
.SECTION "AutoGuard63" FORCE
AutoGuard63:
.incbin "auto_guard_063.bin"
.ENDS
ROMBLOCK 82, $3c2a
.SECTION "AutoLayout42" FORCE
AutoLayout42:
.incbin "auto_layout_042.bin"
.ENDS
ROMBLOCK 82, $52dd
.SECTION "AutoGuard64" FORCE
AutoGuard64:
.incbin "auto_guard_064.bin"
.ENDS
ROMBLOCK 82, $52f7
.SECTION "AutoLayout43" FORCE
AutoLayout43:
.incbin "auto_layout_043.bin"
.ENDS
ROMBLOCK 82, $69ad
.SECTION "AutoGuard65" FORCE
AutoGuard65:
.incbin "auto_guard_065.bin"
.ENDS
ROMBLOCK 83, $0000
.SECTION "AutoLayout44" FORCE
AutoLayout44:
.incbin "auto_layout_044.bin"
.ENDS
ROMBLOCK 83, $16b0
.SECTION "AutoGuard66" FORCE
AutoGuard66:
.incbin "auto_guard_066.bin"
.ENDS
ROMBLOCK 83, $16ca
.SECTION "AutoLayout45" FORCE
AutoLayout45:
.incbin "auto_layout_045.bin"
.ENDS
ROMBLOCK 83, $2d77
.SECTION "AutoGuard67" FORCE
AutoGuard67:
.incbin "auto_guard_067.bin"
.ENDS
ROMBLOCK 83, $2d91
.SECTION "AutoLayout46" FORCE
AutoLayout46:
.incbin "auto_layout_046.bin"
.ENDS
ROMBLOCK 83, $4435
.SECTION "AutoGuard68" FORCE
AutoGuard68:
.incbin "auto_guard_068.bin"
.ENDS
ROMBLOCK 83, $4453
.SECTION "AutoLayout47" FORCE
AutoLayout47:
.incbin "auto_layout_047.bin"
.ENDS
ROMBLOCK 83, $5afd
.SECTION "AutoGuard69" FORCE
AutoGuard69:
.incbin "auto_guard_069.bin"
.ENDS
ROMBLOCK 83, $5b1f
.SECTION "AutoGuard70" FORCE
AutoGuard70:
.incbin "auto_guard_070.bin"
.ENDS
ROMBLOCK 83, $5b41
.SECTION "AutoGuard71" FORCE
AutoGuard71:
.incbin "auto_guard_071.bin"
.ENDS
ROMBLOCK 83, $5b5f
.SECTION "AutoLayout48" FORCE
AutoLayout48:
.incbin "auto_layout_048.bin"
.ENDS
ROMBLOCK 83, $7257
.SECTION "AutoGuard72" FORCE
AutoGuard72:
.incbin "auto_guard_072.bin"
.ENDS
ROMBLOCK 84, $0000
.SECTION "AutoLayout49" FORCE
AutoLayout49:
.incbin "auto_layout_049.bin"
.ENDS
ROMBLOCK 84, $16ad
.SECTION "AutoGuard73" FORCE
AutoGuard73:
.incbin "auto_guard_073.bin"
.ENDS
ROMBLOCK 84, $16cb
.SECTION "AutoLayout50" FORCE
AutoLayout50:
.incbin "auto_layout_050.bin"
.ENDS
ROMBLOCK 84, $2d72
.SECTION "AutoGuard74" FORCE
AutoGuard74:
.incbin "auto_guard_074.bin"
.ENDS
ROMBLOCK 84, $2d88
.SECTION "AutoLayout51" FORCE
AutoLayout51:
.incbin "auto_layout_051.bin"
.ENDS
ROMBLOCK 84, $443e
.SECTION "AutoGuard75" FORCE
AutoGuard75:
.incbin "auto_guard_075.bin"
.ENDS
ROMBLOCK 84, $445c
.SECTION "AutoGuard76" FORCE
AutoGuard76:
.incbin "auto_guard_076.bin"
.ENDS
ROMBLOCK 84, $4476
.SECTION "AutoLayout52" FORCE
AutoLayout52:
.incbin "auto_layout_052.bin"
.ENDS
ROMBLOCK 84, $573f
.SECTION "AutoGuard77" FORCE
AutoGuard77:
.incbin "auto_guard_077.bin"
.ENDS
ROMBLOCK 84, $5759
.SECTION "AutoLayout53" FORCE
AutoLayout53:
.incbin "auto_layout_053.bin"
.ENDS
ROMBLOCK 84, $6a1f
.SECTION "AutoGuard78" FORCE
AutoGuard78:
.incbin "auto_guard_078.bin"
.ENDS
ROMBLOCK 84, $6a39
.SECTION "AutoGuard79" FORCE
AutoGuard79:
.incbin "auto_guard_079.bin"
.ENDS
ROMBLOCK 84, $6a53
.SECTION "AutoGuard80" FORCE
AutoGuard80:
.incbin "auto_guard_080.bin"
.ENDS
ROMBLOCK 84, $6a6d
.SECTION "AutoGuard81" FORCE
AutoGuard81:
.incbin "auto_guard_081.bin"
.ENDS
ROMBLOCK 84, $6a87
.SECTION "AutoGuard82" FORCE
AutoGuard82:
.incbin "auto_guard_082.bin"
.ENDS
ROMBLOCK 84, $6aa1
.SECTION "AutoGuard83" FORCE
AutoGuard83:
.incbin "auto_guard_083.bin"
.ENDS
ROMBLOCK 84, $6abb
.SECTION "AutoLayout54" FORCE
AutoLayout54:
.incbin "auto_layout_054.bin"
.ENDS
ROMBLOCK 84, $7cdc
.SECTION "AutoGuard84" FORCE
AutoGuard84:
.incbin "auto_guard_084.bin"
.ENDS
ROMBLOCK 84, $7cf6
.SECTION "AutoGuard85" FORCE
AutoGuard85:
.incbin "auto_guard_085.bin"
.ENDS
ROMBLOCK 84, $7d10
.SECTION "AutoGuard86" FORCE
AutoGuard86:
.incbin "auto_guard_086.bin"
.ENDS
ROMBLOCK 84, $7d2a
.SECTION "AutoGuard87" FORCE
AutoGuard87:
.incbin "auto_guard_087.bin"
.ENDS
ROMBLOCK 84, $7d44
.SECTION "AutoGuard88" FORCE
AutoGuard88:
.incbin "auto_guard_088.bin"
.ENDS
ROMBLOCK 84, $7d5e
.SECTION "AutoGuard89" FORCE
AutoGuard89:
.incbin "auto_guard_089.bin"
.ENDS
ROMBLOCK 85, $0000
.SECTION "AutoLayout55" FORCE
AutoLayout55:
.incbin "auto_layout_055.bin"
.ENDS
ROMBLOCK 85, $178b
.SECTION "AutoGuard90" FORCE
AutoGuard90:
.incbin "auto_guard_090.bin"
.ENDS
ROMBLOCK 85, $17a9
.SECTION "AutoLayout56" FORCE
AutoLayout56:
.incbin "auto_layout_056.bin"
.ENDS
ROMBLOCK 85, $2f34
.SECTION "AutoGuard91" FORCE
AutoGuard91:
.incbin "auto_guard_091.bin"
.ENDS
ROMBLOCK 85, $2f52
.SECTION "AutoLayout57" FORCE
AutoLayout57:
.incbin "auto_layout_057.bin"
.ENDS
ROMBLOCK 85, $46da
.SECTION "AutoGuard92" FORCE
AutoGuard92:
.incbin "auto_guard_092.bin"
.ENDS
ROMBLOCK 85, $46f8
.SECTION "AutoLayout58" FORCE
AutoLayout58:
.incbin "auto_layout_058.bin"
.ENDS
ROMBLOCK 85, $5e7d
.SECTION "AutoGuard93" FORCE
AutoGuard93:
.incbin "auto_guard_093.bin"
.ENDS
ROMBLOCK 85, $5e9f
.SECTION "AutoLayout59" FORCE
AutoLayout59:
.incbin "auto_layout_059.bin"
.ENDS
ROMBLOCK 85, $7627
.SECTION "AutoGuard94" FORCE
AutoGuard94:
.incbin "auto_guard_094.bin"
.ENDS
ROMBLOCK 86, $0000
.SECTION "AutoLayout60" FORCE
AutoLayout60:
.incbin "auto_layout_060.bin"
.ENDS
ROMBLOCK 86, $178e
.SECTION "AutoGuard95" FORCE
AutoGuard95:
.incbin "auto_guard_095.bin"
.ENDS
ROMBLOCK 86, $17b0
.SECTION "AutoLayout61" FORCE
AutoLayout61:
.incbin "auto_layout_061.bin"
.ENDS
ROMBLOCK 86, $2f3e
.SECTION "AutoGuard96" FORCE
AutoGuard96:
.incbin "auto_guard_096.bin"
.ENDS
ROMBLOCK 86, $2f60
.SECTION "AutoGuard97" FORCE
AutoGuard97:
.incbin "auto_guard_097.bin"
.ENDS
ROMBLOCK 86, $2f8e
.SECTION "AutoGuard98" FORCE
AutoGuard98:
.incbin "auto_guard_098.bin"
.ENDS
ROMBLOCK 86, $2fb4
.SECTION "AutoLayout62" FORCE
AutoLayout62:
.incbin "auto_layout_062.bin"
.ENDS
ROMBLOCK 86, $473c
.SECTION "AutoGuard99" FORCE
AutoGuard99:
.incbin "auto_guard_099.bin"
.ENDS
ROMBLOCK 86, $4762
.SECTION "AutoLayout63" FORCE
AutoLayout63:
.incbin "auto_layout_063.bin"
.ENDS
ROMBLOCK 86, $5ef6
.SECTION "AutoGuard100" FORCE
AutoGuard100:
.incbin "auto_guard_100.bin"
.ENDS
ROMBLOCK 86, $5f1c
.SECTION "AutoGuard101" FORCE
AutoGuard101:
.incbin "auto_guard_101.bin"
.ENDS
ROMBLOCK 86, $5f42
.SECTION "AutoLayout64" FORCE
AutoLayout64:
.incbin "auto_layout_064.bin"
.ENDS
ROMBLOCK 86, $76cd
.SECTION "AutoGuard102" FORCE
AutoGuard102:
.incbin "auto_guard_102.bin"
.ENDS
ROMBLOCK 87, $0000
.SECTION "AutoLayout65" FORCE
AutoLayout65:
.incbin "auto_layout_065.bin"
.ENDS
ROMBLOCK 87, $178b
.SECTION "AutoGuard103" FORCE
AutoGuard103:
.incbin "auto_guard_103.bin"
.ENDS
ROMBLOCK 87, $17b1
.SECTION "AutoGuard104" FORCE
AutoGuard104:
.incbin "auto_guard_104.bin"
.ENDS
ROMBLOCK 87, $17d7
.SECTION "AutoLayout66" FORCE
AutoLayout66:
.incbin "auto_layout_066.bin"
.ENDS
ROMBLOCK 87, $2f5c
.SECTION "AutoGuard105" FORCE
AutoGuard105:
.incbin "auto_guard_105.bin"
.ENDS
ROMBLOCK 87, $2f82
.SECTION "AutoLayout67" FORCE
AutoLayout67:
.incbin "auto_layout_067.bin"
.ENDS
ROMBLOCK 87, $4722
.SECTION "AutoGuard106" FORCE
AutoGuard106:
.incbin "auto_guard_106.bin"
.ENDS
ROMBLOCK 87, $4748
.SECTION "AutoGuard107" FORCE
AutoGuard107:
.incbin "auto_guard_107.bin"
.ENDS
ROMBLOCK 87, $476e
.SECTION "AutoLayout68" FORCE
AutoLayout68:
.incbin "auto_layout_068.bin"
.ENDS
ROMBLOCK 87, $5f0b
.SECTION "AutoGuard108" FORCE
AutoGuard108:
.incbin "auto_guard_108.bin"
.ENDS
ROMBLOCK 87, $5f31
.SECTION "AutoLayout69" FORCE
AutoLayout69:
.incbin "auto_layout_069.bin"
.ENDS
ROMBLOCK 87, $76b6
.SECTION "AutoGuard109" FORCE
AutoGuard109:
.incbin "auto_guard_109.bin"
.ENDS
ROMBLOCK 88, $0000
.SECTION "AutoLayout70" FORCE
AutoLayout70:
.incbin "auto_layout_070.bin"
.ENDS
ROMBLOCK 88, $178e
.SECTION "AutoGuard110" FORCE
AutoGuard110:
.incbin "auto_guard_110.bin"
.ENDS
ROMBLOCK 88, $17b0
.SECTION "AutoGuard111" FORCE
AutoGuard111:
.incbin "auto_guard_111.bin"
.ENDS
ROMBLOCK 88, $17d2
.SECTION "AutoLayout71" FORCE
AutoLayout71:
.incbin "auto_layout_071.bin"
.ENDS
ROMBLOCK 88, $2f63
.SECTION "AutoGuard112" FORCE
AutoGuard112:
.incbin "auto_guard_112.bin"
.ENDS
ROMBLOCK 88, $2f89
.SECTION "AutoGuard113" FORCE
AutoGuard113:
.incbin "auto_guard_113.bin"
.ENDS
ROMBLOCK 88, $2faf
.SECTION "AutoGuard114" FORCE
AutoGuard114:
.incbin "auto_guard_114.bin"
.ENDS
ROMBLOCK 88, $2fd5
.SECTION "AutoLayout72" FORCE
AutoLayout72:
.incbin "auto_layout_072.bin"
.ENDS
ROMBLOCK 88, $4766
.SECTION "AutoGuard115" FORCE
AutoGuard115:
.incbin "auto_guard_115.bin"
.ENDS
ROMBLOCK 88, $478c
.SECTION "AutoLayout73" FORCE
AutoLayout73:
.incbin "auto_layout_073.bin"
.ENDS
ROMBLOCK 88, $5f17
.SECTION "AutoGuard116" FORCE
AutoGuard116:
.incbin "auto_guard_116.bin"
.ENDS
ROMBLOCK 88, $5f39
.SECTION "AutoLayout74" FORCE
AutoLayout74:
.incbin "auto_layout_074.bin"
.ENDS
ROMBLOCK 88, $76ca
.SECTION "AutoGuard117" FORCE
AutoGuard117:
.incbin "auto_guard_117.bin"
.ENDS
ROMBLOCK 89, $0000
.SECTION "AutoLayout75" FORCE
AutoLayout75:
.incbin "auto_layout_075.bin"
.ENDS
ROMBLOCK 89, $178e
.SECTION "AutoGuard118" FORCE
AutoGuard118:
.incbin "auto_guard_118.bin"
.ENDS
ROMBLOCK 89, $17b0
.SECTION "AutoLayout76" FORCE
AutoLayout76:
.incbin "auto_layout_076.bin"
.ENDS
ROMBLOCK 89, $2f3b
.SECTION "AutoGuard119" FORCE
AutoGuard119:
.incbin "auto_guard_119.bin"
.ENDS
ROMBLOCK 89, $2f5d
.SECTION "AutoLayout77" FORCE
AutoLayout77:
.incbin "auto_layout_077.bin"
.ENDS
ROMBLOCK 89, $46e5
.SECTION "AutoGuard120" FORCE
AutoGuard120:
.incbin "auto_guard_120.bin"
.ENDS
ROMBLOCK 89, $470b
.SECTION "AutoLayout78" FORCE
AutoLayout78:
.incbin "auto_layout_078.bin"
.ENDS
ROMBLOCK 89, $5e99
.SECTION "AutoGuard121" FORCE
AutoGuard121:
.incbin "auto_guard_121.bin"
.ENDS
ROMBLOCK 89, $5ebf
.SECTION "AutoLayout79" FORCE
AutoLayout79:
.incbin "auto_layout_079.bin"
.ENDS
ROMBLOCK 89, $764a
.SECTION "AutoGuard122" FORCE
AutoGuard122:
.incbin "auto_guard_122.bin"
.ENDS
ROMBLOCK 90, $0000
.SECTION "AutoLayout80" FORCE
AutoLayout80:
.incbin "auto_layout_080.bin"
.ENDS
ROMBLOCK 90, $178b
.SECTION "AutoGuard123" FORCE
AutoGuard123:
.incbin "auto_guard_123.bin"
.ENDS
ROMBLOCK 90, $17ad
.SECTION "AutoGuard124" FORCE
AutoGuard124:
.incbin "auto_guard_124.bin"
.ENDS
ROMBLOCK 90, $17cf
.SECTION "AutoLayout81" FORCE
AutoLayout81:
.incbin "auto_layout_081.bin"
.ENDS
ROMBLOCK 90, $2f5a
.SECTION "AutoGuard125" FORCE
AutoGuard125:
.incbin "auto_guard_125.bin"
.ENDS
ROMBLOCK 90, $2f7c
.SECTION "AutoLayout82" FORCE
AutoLayout82:
.incbin "auto_layout_082.bin"
.ENDS
ROMBLOCK 90, $4704
.SECTION "AutoGuard126" FORCE
AutoGuard126:
.incbin "auto_guard_126.bin"
.ENDS
ROMBLOCK 90, $4726
.SECTION "AutoLayout83" FORCE
AutoLayout83:
.incbin "auto_layout_083.bin"
.ENDS
ROMBLOCK 90, $5eb1
.SECTION "AutoGuard127" FORCE
AutoGuard127:
.incbin "auto_guard_127.bin"
.ENDS
ROMBLOCK 90, $5ed3
.SECTION "AutoLayout84" FORCE
AutoLayout84:
.incbin "auto_layout_084.bin"
.ENDS
ROMBLOCK 90, $7664
.SECTION "AutoGuard128" FORCE
AutoGuard128:
.incbin "auto_guard_128.bin"
.ENDS
ROMBLOCK 90, $7686
.SECTION "AutoGuard129" FORCE
AutoGuard129:
.incbin "auto_guard_129.bin"
.ENDS
ROMBLOCK 91, $0000
.SECTION "AutoLayout85" FORCE
AutoLayout85:
.incbin "auto_layout_085.bin"
.ENDS
ROMBLOCK 91, $1794
.SECTION "AutoGuard130" FORCE
AutoGuard130:
.incbin "auto_guard_130.bin"
.ENDS
ROMBLOCK 91, $17b6
.SECTION "AutoGuard131" FORCE
AutoGuard131:
.incbin "auto_guard_131.bin"
.ENDS
ROMBLOCK 91, $17cc
.SECTION "AutoLayout86" FORCE
AutoLayout86:
.incbin "auto_layout_086.bin"
.ENDS
ROMBLOCK 91, $2f5a
.SECTION "AutoGuard132" FORCE
AutoGuard132:
.incbin "auto_guard_132.bin"
.ENDS
ROMBLOCK 91, $2f7c
.SECTION "AutoGuard133" FORCE
AutoGuard133:
.incbin "auto_guard_133.bin"
.ENDS
ROMBLOCK 91, $2f9e
.SECTION "AutoGuard134" FORCE
AutoGuard134:
.incbin "auto_guard_134.bin"
.ENDS
ROMBLOCK 91, $2fc4
.SECTION "AutoLayout87" FORCE
AutoLayout87:
.incbin "auto_layout_087.bin"
.ENDS
ROMBLOCK 91, $475b
.SECTION "AutoGuard135" FORCE
AutoGuard135:
.incbin "auto_guard_135.bin"
.ENDS
ROMBLOCK 91, $477d
.SECTION "AutoLayout88" FORCE
AutoLayout88:
.incbin "auto_layout_088.bin"
.ENDS
ROMBLOCK 91, $5f08
.SECTION "AutoGuard136" FORCE
AutoGuard136:
.incbin "auto_guard_136.bin"
.ENDS
ROMBLOCK 91, $5f1e
.SECTION "AutoGuard137" FORCE
AutoGuard137:
.incbin "auto_guard_137.bin"
.ENDS
ROMBLOCK 91, $5f34
.SECTION "AutoLayout89" FORCE
AutoLayout89:
.incbin "auto_layout_089.bin"
.ENDS
ROMBLOCK 91, $76c5
.SECTION "AutoGuard138" FORCE
AutoGuard138:
.incbin "auto_guard_138.bin"
.ENDS
ROMBLOCK 91, $76db
.SECTION "AutoGuard139" FORCE
AutoGuard139:
.incbin "auto_guard_139.bin"
.ENDS
ROMBLOCK 91, $7701
.SECTION "AutoGuard140" FORCE
AutoGuard140:
.incbin "auto_guard_140.bin"
.ENDS
ROMBLOCK 91, $7727
.SECTION "AutoGuard141" FORCE
AutoGuard141:
.incbin "auto_guard_141.bin"
.ENDS
ROMBLOCK 91, $774d
.SECTION "AutoGuard142" FORCE
AutoGuard142:
.incbin "auto_guard_142.bin"
.ENDS
ROMBLOCK 91, $776f
.SECTION "AutoGuard143" FORCE
AutoGuard143:
.incbin "auto_guard_143.bin"
.ENDS
ROMBLOCK 91, $7791
.SECTION "AutoGuard144" FORCE
AutoGuard144:
.incbin "auto_guard_144.bin"
.ENDS
ROMBLOCK 91, $77b3
.SECTION "AutoGuard145" FORCE
AutoGuard145:
.incbin "auto_guard_145.bin"
.ENDS
ROMBLOCK 92, $0000
.SECTION "AutoLayout90" FORCE
AutoLayout90:
.incbin "auto_layout_090.bin"
.ENDS
ROMBLOCK 92, $178e
.SECTION "AutoGuard146" FORCE
AutoGuard146:
.incbin "auto_guard_146.bin"
.ENDS
ROMBLOCK 92, $17b0
.SECTION "AutoLayout91" FORCE
AutoLayout91:
.incbin "auto_layout_091.bin"
.ENDS
ROMBLOCK 92, $2305
.SECTION "AutoGuard147" FORCE
AutoGuard147:
.incbin "auto_guard_147.bin"
.ENDS
ROMBLOCK 92, $231f
.SECTION "AutoGuard148" FORCE
AutoGuard148:
.incbin "auto_guard_148.bin"
.ENDS
ROMBLOCK 92, $2339
.SECTION "AutoLayout92" FORCE
AutoLayout92:
.incbin "auto_layout_092.bin"
.ENDS
ROMBLOCK 92, $2eee
.SECTION "AutoGuard149" FORCE
AutoGuard149:
.incbin "auto_guard_149.bin"
.ENDS
ROMBLOCK 92, $2f08
.SECTION "AutoLayout93" FORCE
AutoLayout93:
.incbin "auto_layout_093.bin"
.ENDS
ROMBLOCK 92, $3b41
.SECTION "AutoGuard150" FORCE
AutoGuard150:
.incbin "auto_guard_150.bin"
.ENDS
ROMBLOCK 92, $3b5b
.SECTION "AutoLayout94" FORCE
AutoLayout94:
.incbin "auto_layout_094.bin"
.ENDS
ROMBLOCK 92, $4716
.SECTION "AutoGuard151" FORCE
AutoGuard151:
.incbin "auto_guard_151.bin"
.ENDS
ROMBLOCK 92, $4730
.SECTION "AutoLayout95" FORCE
AutoLayout95:
.incbin "auto_layout_095.bin"
.ENDS
ROMBLOCK 92, $52e5
.SECTION "AutoGuard152" FORCE
AutoGuard152:
.incbin "auto_guard_152.bin"
.ENDS
ROMBLOCK 92, $52ff
.SECTION "AutoLayout96" FORCE
AutoLayout96:
.incbin "auto_layout_096.bin"
.ENDS
ROMBLOCK 92, $5e69
.SECTION "AutoGuard153" FORCE
AutoGuard153:
.incbin "auto_guard_153.bin"
.ENDS
ROMBLOCK 92, $5e83
.SECTION "AutoLayout97" FORCE
AutoLayout97:
.incbin "auto_layout_097.bin"
.ENDS
ROMBLOCK 92, $6a47
.SECTION "AutoGuard154" FORCE
AutoGuard154:
.incbin "auto_guard_154.bin"
.ENDS
ROMBLOCK 92, $6a61
.SECTION "AutoLayout98" FORCE
AutoLayout98:
.incbin "auto_layout_098.bin"
.ENDS
ROMBLOCK 92, $7619
.SECTION "AutoGuard155" FORCE
AutoGuard155:
.incbin "auto_guard_155.bin"
.ENDS
ROMBLOCK 93, $0000
.SECTION "AutoLayout99" FORCE
AutoLayout99:
.incbin "auto_layout_099.bin"
.ENDS
ROMBLOCK 93, $0b85
.SECTION "AutoGuard156" FORCE
AutoGuard156:
.incbin "auto_guard_156.bin"
.ENDS
ROMBLOCK 93, $0b9f
.SECTION "AutoLayout100" FORCE
AutoLayout100:
.incbin "auto_layout_100.bin"
.ENDS
ROMBLOCK 93, $1754
.SECTION "AutoGuard157" FORCE
AutoGuard157:
.incbin "auto_guard_157.bin"
.ENDS
ROMBLOCK 93, $176e
.SECTION "AutoLayout101" FORCE
AutoLayout101:
.incbin "auto_layout_101.bin"
.ENDS
ROMBLOCK 93, $22f0
.SECTION "AutoGuard158" FORCE
AutoGuard158:
.incbin "auto_guard_158.bin"
.ENDS
ROMBLOCK 93, $230a
.SECTION "AutoGuard159" FORCE
AutoGuard159:
.incbin "auto_guard_159.bin"
.ENDS
ROMBLOCK 93, $2324
.SECTION "AutoLayout102" FORCE
AutoLayout102:
.incbin "auto_layout_102.bin"
.ENDS
ROMBLOCK 93, $2ec7
.SECTION "AutoGuard160" FORCE
AutoGuard160:
.incbin "auto_guard_160.bin"
.ENDS
ROMBLOCK 93, $2ee1
.SECTION "AutoLayout103" FORCE
AutoLayout103:
.incbin "auto_layout_103.bin"
.ENDS
ROMBLOCK 93, $3dea
.SECTION "AutoGuard161" FORCE
AutoGuard161:
.incbin "auto_guard_161.bin"
.ENDS
ROMBLOCK 93, $3e04
.SECTION "AutoGuard162" FORCE
AutoGuard162:
.incbin "auto_guard_162.bin"
.ENDS
ROMBLOCK 93, $3e22
.SECTION "AutoGuard163" FORCE
AutoGuard163:
.incbin "auto_guard_163.bin"
.ENDS
ROMBLOCK 93, $3e3c
.SECTION "AutoGuard164" FORCE
AutoGuard164:
.incbin "auto_guard_164.bin"
.ENDS
ROMBLOCK 93, $3e56
.SECTION "AutoGuard165" FORCE
AutoGuard165:
.incbin "auto_guard_165.bin"
.ENDS
ROMBLOCK 93, $3e74
.SECTION "AutoLayout104" FORCE
AutoLayout104:
.incbin "auto_layout_104.bin"
.ENDS
ROMBLOCK 93, $4d98
.SECTION "AutoGuard166" FORCE
AutoGuard166:
.incbin "auto_guard_166.bin"
.ENDS
ROMBLOCK 93, $4dba
.SECTION "AutoGuard167" FORCE
AutoGuard167:
.incbin "auto_guard_167.bin"
.ENDS
ROMBLOCK 93, $4dd8
.SECTION "AutoGuard168" FORCE
AutoGuard168:
.incbin "auto_guard_168.bin"
.ENDS
ROMBLOCK 93, $4df6
.SECTION "AutoGuard169" FORCE
AutoGuard169:
.incbin "auto_guard_169.bin"
.ENDS
ROMBLOCK 93, $4e18
.SECTION "AutoGuard170" FORCE
AutoGuard170:
.incbin "auto_guard_170.bin"
.ENDS
ROMBLOCK 93, $4e36
.SECTION "AutoGuard171" FORCE
AutoGuard171:
.incbin "auto_guard_171.bin"
.ENDS
ROMBLOCK 93, $4e54
.SECTION "AutoGuard172" FORCE
AutoGuard172:
.incbin "auto_guard_172.bin"
.ENDS
ROMBLOCK 93, $4e76
.SECTION "AutoLayout105" FORCE
AutoLayout105:
.incbin "auto_layout_105.bin"
.ENDS
ROMBLOCK 93, $69b5
.SECTION "AutoGuard173" FORCE
AutoGuard173:
.incbin "auto_guard_173.bin"
.ENDS
ROMBLOCK 93, $69d7
.SECTION "AutoLayout106" FORCE
AutoLayout106:
.incbin "auto_layout_106.bin"
.ENDS
ROMBLOCK 93, $7df6
.SECTION "AutoGuard174" FORCE
AutoGuard174:
.incbin "auto_guard_174.bin"
.ENDS
ROMBLOCK 94, $0000
.SECTION "AutoLayout107" FORCE
AutoLayout107:
.incbin "auto_layout_107.bin"
.ENDS
ROMBLOCK 94, $140d
.SECTION "AutoGuard175" FORCE
AutoGuard175:
.incbin "auto_guard_175.bin"
.ENDS
ROMBLOCK 94, $1423
.SECTION "AutoLayout108" FORCE
AutoLayout108:
.incbin "auto_layout_108.bin"
.ENDS
ROMBLOCK 94, $282a
.SECTION "AutoGuard176" FORCE
AutoGuard176:
.incbin "auto_guard_176.bin"
.ENDS
ROMBLOCK 94, $2844
.SECTION "AutoLayout109" FORCE
AutoLayout109:
.incbin "auto_layout_109.bin"
.ENDS
ROMBLOCK 94, $3c51
.SECTION "AutoGuard177" FORCE
AutoGuard177:
.incbin "auto_guard_177.bin"
.ENDS
ROMBLOCK 94, $3c6b
.SECTION "AutoLayout110" FORCE
AutoLayout110:
.incbin "auto_layout_110.bin"
.ENDS
ROMBLOCK 94, $509c
.SECTION "AutoGuard178" FORCE
AutoGuard178:
.incbin "auto_guard_178.bin"
.ENDS
ROMBLOCK 94, $50ba
.SECTION "AutoLayout111" FORCE
AutoLayout111:
.incbin "auto_layout_111.bin"
.ENDS
ROMBLOCK 94, $64dc
.SECTION "AutoGuard179" FORCE
AutoGuard179:
.incbin "auto_guard_179.bin"
.ENDS
ROMBLOCK 94, $64f2
.SECTION "AutoLayout112" FORCE
AutoLayout112:
.incbin "auto_layout_112.bin"
.ENDS
ROMBLOCK 94, $790b
.SECTION "AutoGuard180" FORCE
AutoGuard180:
.incbin "auto_guard_180.bin"
.ENDS
ROMBLOCK 95, $0000
.SECTION "AutoLayout113" FORCE
AutoLayout113:
.incbin "auto_layout_113.bin"
.ENDS
ROMBLOCK 95, $1416
.SECTION "AutoGuard181" FORCE
AutoGuard181:
.incbin "auto_guard_181.bin"
.ENDS
ROMBLOCK 95, $143c
.SECTION "AutoLayout114" FORCE
AutoLayout114:
.incbin "auto_layout_114.bin"
.ENDS
ROMBLOCK 95, $2846
.SECTION "AutoGuard182" FORCE
AutoGuard182:
.incbin "auto_guard_182.bin"
.ENDS
ROMBLOCK 95, $2860
.SECTION "AutoLayout115" FORCE
AutoLayout115:
.incbin "auto_layout_115.bin"
.ENDS
ROMBLOCK 95, $3c6d
.SECTION "AutoGuard183" FORCE
AutoGuard183:
.incbin "auto_guard_183.bin"
.ENDS
ROMBLOCK 95, $3c83
.SECTION "AutoGuard184" FORCE
AutoGuard184:
.incbin "auto_guard_184.bin"
.ENDS
ROMBLOCK 95, $3c9d
.SECTION "AutoGuard185" FORCE
AutoGuard185:
.incbin "auto_guard_185.bin"
.ENDS
ROMBLOCK 95, $3cb3
.SECTION "AutoLayout116" FORCE
AutoLayout116:
.incbin "auto_layout_116.bin"
.ENDS
ROMBLOCK 95, $50cf
.SECTION "AutoGuard186" FORCE
AutoGuard186:
.incbin "auto_guard_186.bin"
.ENDS
ROMBLOCK 95, $50e5
.SECTION "AutoLayout117" FORCE
AutoLayout117:
.incbin "auto_layout_117.bin"
.ENDS
ROMBLOCK 95, $650a
.SECTION "AutoGuard187" FORCE
AutoGuard187:
.incbin "auto_guard_187.bin"
.ENDS
ROMBLOCK 95, $6524
.SECTION "AutoLayout118" FORCE
AutoLayout118:
.incbin "auto_layout_118.bin"
.ENDS
ROMBLOCK 95, $7934
.SECTION "AutoGuard188" FORCE
AutoGuard188:
.incbin "auto_guard_188.bin"
.ENDS
ROMBLOCK 96, $0000
.SECTION "AutoLayout119" FORCE
AutoLayout119:
.incbin "auto_layout_119.bin"
.ENDS
ROMBLOCK 96, $140a
.SECTION "AutoGuard189" FORCE
AutoGuard189:
.incbin "auto_guard_189.bin"
.ENDS
ROMBLOCK 96, $1420
.SECTION "AutoLayout120" FORCE
AutoLayout120:
.incbin "auto_layout_120.bin"
.ENDS
ROMBLOCK 96, $2851
.SECTION "AutoGuard190" FORCE
AutoGuard190:
.incbin "auto_guard_190.bin"
.ENDS
ROMBLOCK 96, $286b
.SECTION "AutoLayout121" FORCE
AutoLayout121:
.incbin "auto_layout_121.bin"
.ENDS
ROMBLOCK 96, $3ca2
.SECTION "AutoGuard191" FORCE
AutoGuard191:
.incbin "auto_guard_191.bin"
.ENDS
ROMBLOCK 96, $3cb8
.SECTION "AutoLayout122" FORCE
AutoLayout122:
.incbin "auto_layout_122.bin"
.ENDS
ROMBLOCK 96, $50ec
.SECTION "AutoGuard192" FORCE
AutoGuard192:
.incbin "auto_guard_192.bin"
.ENDS
ROMBLOCK 96, $5102
.SECTION "AutoLayout123" FORCE
AutoLayout123:
.incbin "auto_layout_123.bin"
.ENDS
ROMBLOCK 96, $654b
.SECTION "AutoGuard193" FORCE
AutoGuard193:
.incbin "auto_guard_193.bin"
.ENDS
ROMBLOCK 96, $6565
.SECTION "AutoLayout124" FORCE
AutoLayout124:
.incbin "auto_layout_124.bin"
.ENDS
ROMBLOCK 96, $79ab
.SECTION "AutoGuard194" FORCE
AutoGuard194:
.incbin "auto_guard_194.bin"
.ENDS
ROMBLOCK 97, $0000
.SECTION "AutoLayout125" FORCE
AutoLayout125:
.incbin "auto_layout_125.bin"
.ENDS
ROMBLOCK 97, $1431
.SECTION "AutoGuard195" FORCE
AutoGuard195:
.incbin "auto_guard_195.bin"
.ENDS
ROMBLOCK 97, $144b
.SECTION "AutoLayout126" FORCE
AutoLayout126:
.incbin "auto_layout_126.bin"
.ENDS
ROMBLOCK 97, $287c
.SECTION "AutoGuard196" FORCE
AutoGuard196:
.incbin "auto_guard_196.bin"
.ENDS
ROMBLOCK 97, $2896
.SECTION "AutoLayout127" FORCE
AutoLayout127:
.incbin "auto_layout_127.bin"
.ENDS
ROMBLOCK 97, $3cb2
.SECTION "AutoGuard197" FORCE
AutoGuard197:
.incbin "auto_guard_197.bin"
.ENDS
ROMBLOCK 97, $3cc8
.SECTION "AutoLayout128" FORCE
AutoLayout128:
.incbin "auto_layout_128.bin"
.ENDS
ROMBLOCK 97, $510e
.SECTION "AutoGuard198" FORCE
AutoGuard198:
.incbin "auto_guard_198.bin"
.ENDS
ROMBLOCK 97, $5124
.SECTION "AutoLayout129" FORCE
AutoLayout129:
.incbin "auto_layout_129.bin"
.ENDS
ROMBLOCK 97, $64d7
.SECTION "AutoGuard199" FORCE
AutoGuard199:
.incbin "auto_guard_199.bin"
.ENDS
ROMBLOCK 97, $64ed
.SECTION "AutoLayout130" FORCE
AutoLayout130:
.incbin "auto_layout_130.bin"
.ENDS
ROMBLOCK 97, $789d
.SECTION "AutoGuard200" FORCE
AutoGuard200:
.incbin "auto_guard_200.bin"
.ENDS
ROMBLOCK 98, $0000
.SECTION "AutoLayout131" FORCE
AutoLayout131:
.incbin "auto_layout_131.bin"
.ENDS
ROMBLOCK 98, $13b9
.SECTION "AutoGuard201" FORCE
AutoGuard201:
.incbin "auto_guard_201.bin"
.ENDS
ROMBLOCK 98, $13d3
.SECTION "AutoLayout132" FORCE
AutoLayout132:
.incbin "auto_layout_132.bin"
.ENDS
ROMBLOCK 98, $27a4
.SECTION "AutoGuard202" FORCE
AutoGuard202:
.incbin "auto_guard_202.bin"
.ENDS
ROMBLOCK 98, $27be
.SECTION "AutoGuard203" FORCE
AutoGuard203:
.incbin "auto_guard_203.bin"
.ENDS
ROMBLOCK 98, $27dc
.SECTION "AutoGuard204" FORCE
AutoGuard204:
.incbin "auto_guard_204.bin"
.ENDS
ROMBLOCK 98, $27f6
.SECTION "AutoGuard205" FORCE
AutoGuard205:
.incbin "auto_guard_205.bin"
.ENDS
ROMBLOCK 98, $280c
.SECTION "AutoLayout133" FORCE
AutoLayout133:
.incbin "auto_layout_133.bin"
.ENDS
ROMBLOCK 98, $3982
.SECTION "AutoGuard206" FORCE
AutoGuard206:
.incbin "auto_guard_206.bin"
.ENDS
ROMBLOCK 98, $39a4
.SECTION "AutoGuard207" FORCE
AutoGuard207:
.incbin "auto_guard_207.bin"
.ENDS
ROMBLOCK 98, $39be
.SECTION "AutoGuard208" FORCE
AutoGuard208:
.incbin "auto_guard_208.bin"
.ENDS
ROMBLOCK 98, $39d8
.SECTION "AutoLayout134" FORCE
AutoLayout134:
.incbin "auto_layout_134.bin"
.ENDS
ROMBLOCK 98, $4b66
.SECTION "AutoGuard209" FORCE
AutoGuard209:
.incbin "auto_guard_209.bin"
.ENDS
ROMBLOCK 98, $4b80
.SECTION "AutoGuard210" FORCE
AutoGuard210:
.incbin "auto_guard_210.bin"
.ENDS
ROMBLOCK 98, $4b9a
.SECTION "AutoLayout135" FORCE
AutoLayout135:
.incbin "auto_layout_135.bin"
.ENDS
ROMBLOCK 98, $5d31
.SECTION "AutoGuard211" FORCE
AutoGuard211:
.incbin "auto_guard_211.bin"
.ENDS
ROMBLOCK 98, $5d4b
.SECTION "AutoGuard212" FORCE
AutoGuard212:
.incbin "auto_guard_212.bin"
.ENDS
ROMBLOCK 98, $5d65
.SECTION "AutoGuard213" FORCE
AutoGuard213:
.incbin "auto_guard_213.bin"
.ENDS
ROMBLOCK 98, $5d7f
.SECTION "AutoGuard214" FORCE
AutoGuard214:
.incbin "auto_guard_214.bin"
.ENDS
ROMBLOCK 98, $5d99
.SECTION "AutoGuard215" FORCE
AutoGuard215:
.incbin "auto_guard_215.bin"
.ENDS
ROMBLOCK 98, $5db3
.SECTION "AutoGuard216" FORCE
AutoGuard216:
.incbin "auto_guard_216.bin"
.ENDS
ROMBLOCK 98, $5dcd
.SECTION "AutoGuard217" FORCE
AutoGuard217:
.incbin "auto_guard_217.bin"
.ENDS
ROMBLOCK 98, $5de7
.SECTION "AutoGuard218" FORCE
AutoGuard218:
.incbin "auto_guard_218.bin"
.ENDS
ROMBLOCK 98, $5e01
.SECTION "AutoGuard219" FORCE
AutoGuard219:
.incbin "auto_guard_219.bin"
.ENDS
ROMBLOCK 98, $5e1b
.SECTION "AutoGuard220" FORCE
AutoGuard220:
.incbin "auto_guard_220.bin"
.ENDS
ROMBLOCK 98, $5e35
.SECTION "AutoGuard221" FORCE
AutoGuard221:
.incbin "auto_guard_221.bin"
.ENDS
ROMBLOCK 98, $5e4f
.SECTION "AutoGuard222" FORCE
AutoGuard222:
.incbin "auto_guard_222.bin"
.ENDS
ROMBLOCK 98, $5e69
.SECTION "AutoGuard223" FORCE
AutoGuard223:
.incbin "auto_guard_223.bin"
.ENDS
ROMBLOCK 98, $5e83
.SECTION "AutoGuard224" FORCE
AutoGuard224:
.incbin "auto_guard_224.bin"
.ENDS
ROMBLOCK 98, $5ea5
.SECTION "AutoLayout136" FORCE
AutoLayout136:
.incbin "auto_layout_136.bin"
.ENDS
ROMBLOCK 98, $7039
.SECTION "AutoGuard225" FORCE
AutoGuard225:
.incbin "auto_guard_225.bin"
.ENDS
ROMBLOCK 99, $0000
.SECTION "AutoLayout137" FORCE
AutoLayout137:
.incbin "auto_layout_137.bin"
.ENDS
ROMBLOCK 99, $18cf
.SECTION "AutoGuard226" FORCE
AutoGuard226:
.incbin "auto_guard_226.bin"
.ENDS
ROMBLOCK 99, $18e5
.SECTION "AutoGuard227" FORCE
AutoGuard227:
.incbin "auto_guard_227.bin"
.ENDS
ROMBLOCK 99, $18ff
.SECTION "AutoGuard228" FORCE
AutoGuard228:
.incbin "auto_guard_228.bin"
.ENDS
ROMBLOCK 99, $1915
.SECTION "AutoLayout138" FORCE
AutoLayout138:
.incbin "auto_layout_138.bin"
.ENDS
ROMBLOCK 99, $2488
.SECTION "AutoGuard229" FORCE
AutoGuard229:
.incbin "auto_guard_229.bin"
.ENDS
ROMBLOCK 99, $249e
.SECTION "AutoLayout139" FORCE
AutoLayout139:
.incbin "auto_layout_139.bin"
.ENDS
ROMBLOCK 99, $2f96
.SECTION "AutoGuard230" FORCE
AutoGuard230:
.incbin "auto_guard_230.bin"
.ENDS
ROMBLOCK 99, $2fb0
.SECTION "AutoLayout140" FORCE
AutoLayout140:
.incbin "auto_layout_140.bin"
.ENDS
ROMBLOCK 99, $3b71
.SECTION "AutoGuard231" FORCE
AutoGuard231:
.incbin "auto_guard_231.bin"
.ENDS
ROMBLOCK 99, $3b87
.SECTION "AutoLayout141" FORCE
AutoLayout141:
.incbin "auto_layout_141.bin"
.ENDS
ROMBLOCK 99, $4712
.SECTION "AutoGuard232" FORCE
AutoGuard232:
.incbin "auto_guard_232.bin"
.ENDS
ROMBLOCK 99, $4728
.SECTION "AutoLayout142" FORCE
AutoLayout142:
.incbin "auto_layout_142.bin"
.ENDS
ROMBLOCK 99, $52ef
.SECTION "AutoGuard233" FORCE
AutoGuard233:
.incbin "auto_guard_233.bin"
.ENDS
ROMBLOCK 99, $5305
.SECTION "AutoLayout143" FORCE
AutoLayout143:
.incbin "auto_layout_143.bin"
.ENDS
ROMBLOCK 99, $5e93
.SECTION "AutoGuard234" FORCE
AutoGuard234:
.incbin "auto_guard_234.bin"
.ENDS
ROMBLOCK 99, $5ead
.SECTION "AutoLayout144" FORCE
AutoLayout144:
.incbin "auto_layout_144.bin"
.ENDS
ROMBLOCK 99, $68f7
.SECTION "AutoGuard235" FORCE
AutoGuard235:
.incbin "auto_guard_235.bin"
.ENDS
ROMBLOCK 99, $690d
.SECTION "AutoLayout145" FORCE
AutoLayout145:
.incbin "auto_layout_145.bin"
.ENDS
ROMBLOCK 99, $73d5
.SECTION "AutoGuard236" FORCE
AutoGuard236:
.incbin "auto_guard_236.bin"
.ENDS
ROMBLOCK 99, $73eb
.SECTION "AutoLayout146" FORCE
AutoLayout146:
.incbin "auto_layout_146.bin"
.ENDS
ROMBLOCK 99, $7f40
.SECTION "AutoGuard237" FORCE
AutoGuard237:
.incbin "auto_guard_237.bin"
.ENDS
ROMBLOCK 100, $0000
.SECTION "AutoLayout147" FORCE
AutoLayout147:
.incbin "auto_layout_147.bin"
.ENDS
ROMBLOCK 100, $09f3
.SECTION "AutoGuard238" FORCE
AutoGuard238:
.incbin "auto_guard_238.bin"
.ENDS
ROMBLOCK 100, $0a0d
.SECTION "AutoLayout148" FORCE
AutoLayout148:
.incbin "auto_layout_148.bin"
.ENDS
ROMBLOCK 100, $13a0
.SECTION "AutoGuard239" FORCE
AutoGuard239:
.incbin "auto_guard_239.bin"
.ENDS
ROMBLOCK 100, $13be
.SECTION "AutoLayout149" FORCE
AutoLayout149:
.incbin "auto_layout_149.bin"
.ENDS
ROMBLOCK 100, $1ddb
.SECTION "AutoGuard240" FORCE
AutoGuard240:
.incbin "auto_guard_240.bin"
.ENDS
ROMBLOCK 100, $1df5
.SECTION "AutoLayout150" FORCE
AutoLayout150:
.incbin "auto_layout_150.bin"
.ENDS
ROMBLOCK 100, $27e8
.SECTION "AutoGuard241" FORCE
AutoGuard241:
.incbin "auto_guard_241.bin"
.ENDS
ROMBLOCK 100, $2802
.SECTION "AutoLayout151" FORCE
AutoLayout151:
.incbin "auto_layout_151.bin"
.ENDS
ROMBLOCK 100, $3249
.SECTION "AutoGuard242" FORCE
AutoGuard242:
.incbin "auto_guard_242.bin"
.ENDS
ROMBLOCK 100, $3263
.SECTION "AutoLayout152" FORCE
AutoLayout152:
.incbin "auto_layout_152.bin"
.ENDS
ROMBLOCK 100, $3cec
.SECTION "AutoGuard243" FORCE
AutoGuard243:
.incbin "auto_guard_243.bin"
.ENDS
ROMBLOCK 100, $3d02
.SECTION "AutoLayout153" FORCE
AutoLayout153:
.incbin "auto_layout_153.bin"
.ENDS
ROMBLOCK 100, $482a
.SECTION "AutoGuard244" FORCE
AutoGuard244:
.incbin "auto_guard_244.bin"
.ENDS
ROMBLOCK 100, $4840
.SECTION "AutoLayout154" FORCE
AutoLayout154:
.incbin "auto_layout_154.bin"
.ENDS
ROMBLOCK 100, $565c
.SECTION "AutoGuard245" FORCE
AutoGuard245:
.incbin "auto_guard_245.bin"
.ENDS
ROMBLOCK 100, $5676
.SECTION "AutoGuard246" FORCE
AutoGuard246:
.incbin "auto_guard_246.bin"
.ENDS
ROMBLOCK 100, $5690
.SECTION "AutoGuard247" FORCE
AutoGuard247:
.incbin "auto_guard_247.bin"
.ENDS
ROMBLOCK 100, $56aa
.SECTION "AutoGuard248" FORCE
AutoGuard248:
.incbin "auto_guard_248.bin"
.ENDS
ROMBLOCK 100, $56c4
.SECTION "AutoGuard249" FORCE
AutoGuard249:
.incbin "auto_guard_249.bin"
.ENDS
ROMBLOCK 100, $56de
.SECTION "AutoGuard250" FORCE
AutoGuard250:
.incbin "auto_guard_250.bin"
.ENDS
ROMBLOCK 100, $56f8
.SECTION "AutoGuard251" FORCE
AutoGuard251:
.incbin "auto_guard_251.bin"
.ENDS
ROMBLOCK 100, $5712
.SECTION "AutoGuard252" FORCE
AutoGuard252:
.incbin "auto_guard_252.bin"
.ENDS
ROMBLOCK 100, $572c
.SECTION "AutoGuard253" FORCE
AutoGuard253:
.incbin "auto_guard_253.bin"
.ENDS
ROMBLOCK 100, $5746
.SECTION "AutoGuard254" FORCE
AutoGuard254:
.incbin "auto_guard_254.bin"
.ENDS
ROMBLOCK 100, $5760
.SECTION "AutoGuard255" FORCE
AutoGuard255:
.incbin "auto_guard_255.bin"
.ENDS
ROMBLOCK 100, $577a
.SECTION "AutoGuard256" FORCE
AutoGuard256:
.incbin "auto_guard_256.bin"
.ENDS
ROMBLOCK 100, $5794
.SECTION "AutoGuard257" FORCE
AutoGuard257:
.incbin "auto_guard_257.bin"
.ENDS
ROMBLOCK 100, $57ae
.SECTION "AutoGuard258" FORCE
AutoGuard258:
.incbin "auto_guard_258.bin"
.ENDS
ROMBLOCK 100, $57c8
.SECTION "AutoGuard259" FORCE
AutoGuard259:
.incbin "auto_guard_259.bin"
.ENDS
ROMBLOCK 100, $57e2
.SECTION "AutoGuard260" FORCE
AutoGuard260:
.incbin "auto_guard_260.bin"
.ENDS
ROMBLOCK 100, $57fc
.SECTION "AutoGuard261" FORCE
AutoGuard261:
.incbin "auto_guard_261.bin"
.ENDS
ROMBLOCK 100, $5816
.SECTION "AutoGuard262" FORCE
AutoGuard262:
.incbin "auto_guard_262.bin"
.ENDS
ROMBLOCK 100, $5830
.SECTION "AutoGuard263" FORCE
AutoGuard263:
.incbin "auto_guard_263.bin"
.ENDS
ROMBLOCK 100, $584a
.SECTION "AutoGuard264" FORCE
AutoGuard264:
.incbin "auto_guard_264.bin"
.ENDS
ROMBLOCK 100, $5864
.SECTION "AutoGuard265" FORCE
AutoGuard265:
.incbin "auto_guard_265.bin"
.ENDS
ROMBLOCK 100, $587e
.SECTION "AutoGuard266" FORCE
AutoGuard266:
.incbin "auto_guard_266.bin"
.ENDS
ROMBLOCK 100, $5898
.SECTION "AutoGuard267" FORCE
AutoGuard267:
.incbin "auto_guard_267.bin"
.ENDS
ROMBLOCK 100, $58b2
.SECTION "AutoGuard268" FORCE
AutoGuard268:
.incbin "auto_guard_268.bin"
.ENDS
ROMBLOCK 100, $58cc
.SECTION "AutoGuard269" FORCE
AutoGuard269:
.incbin "auto_guard_269.bin"
.ENDS
ROMBLOCK 100, $58e6
.SECTION "AutoGuard270" FORCE
AutoGuard270:
.incbin "auto_guard_270.bin"
.ENDS
ROMBLOCK 100, $5900
.SECTION "AutoGuard271" FORCE
AutoGuard271:
.incbin "auto_guard_271.bin"
.ENDS
ROMBLOCK 100, $591a
.SECTION "AutoGuard272" FORCE
AutoGuard272:
.incbin "auto_guard_272.bin"
.ENDS
ROMBLOCK 100, $5934
.SECTION "AutoGuard273" FORCE
AutoGuard273:
.incbin "auto_guard_273.bin"
.ENDS
ROMBLOCK 100, $594e
.SECTION "AutoGuard274" FORCE
AutoGuard274:
.incbin "auto_guard_274.bin"
.ENDS
ROMBLOCK 100, $5968
.SECTION "AutoGuard275" FORCE
AutoGuard275:
.incbin "auto_guard_275.bin"
.ENDS
ROMBLOCK 100, $5982
.SECTION "AutoGuard276" FORCE
AutoGuard276:
.incbin "auto_guard_276.bin"
.ENDS
ROMBLOCK 100, $599c
.SECTION "AutoGuard277" FORCE
AutoGuard277:
.incbin "auto_guard_277.bin"
.ENDS
ROMBLOCK 100, $59b6
.SECTION "AutoGuard278" FORCE
AutoGuard278:
.incbin "auto_guard_278.bin"
.ENDS
ROMBLOCK 100, $59d0
.SECTION "AutoGuard279" FORCE
AutoGuard279:
.incbin "auto_guard_279.bin"
.ENDS
ROMBLOCK 100, $59ea
.SECTION "AutoGuard280" FORCE
AutoGuard280:
.incbin "auto_guard_280.bin"
.ENDS
ROMBLOCK 100, $5a04
.SECTION "AutoGuard281" FORCE
AutoGuard281:
.incbin "auto_guard_281.bin"
.ENDS
ROMBLOCK 100, $5a1e
.SECTION "AutoGuard282" FORCE
AutoGuard282:
.incbin "auto_guard_282.bin"
.ENDS
ROMBLOCK 100, $5a38
.SECTION "AutoGuard283" FORCE
AutoGuard283:
.incbin "auto_guard_283.bin"
.ENDS
ROMBLOCK 100, $5a52
.SECTION "AutoGuard284" FORCE
AutoGuard284:
.incbin "auto_guard_284.bin"
.ENDS
ROMBLOCK 100, $5a6c
.SECTION "AutoGuard285" FORCE
AutoGuard285:
.incbin "auto_guard_285.bin"
.ENDS
ROMBLOCK 100, $5a86
.SECTION "AutoGuard286" FORCE
AutoGuard286:
.incbin "auto_guard_286.bin"
.ENDS
ROMBLOCK 100, $5aa0
.SECTION "AutoGuard287" FORCE
AutoGuard287:
.incbin "auto_guard_287.bin"
.ENDS
ROMBLOCK 100, $5aba
.SECTION "AutoGuard288" FORCE
AutoGuard288:
.incbin "auto_guard_288.bin"
.ENDS
ROMBLOCK 100, $5ad4
.SECTION "AutoGuard289" FORCE
AutoGuard289:
.incbin "auto_guard_289.bin"
.ENDS
ROMBLOCK 100, $5aee
.SECTION "AutoGuard290" FORCE
AutoGuard290:
.incbin "auto_guard_290.bin"
.ENDS
ROMBLOCK 100, $5b08
.SECTION "AutoGuard291" FORCE
AutoGuard291:
.incbin "auto_guard_291.bin"
.ENDS
ROMBLOCK 100, $5b22
.SECTION "AutoGuard292" FORCE
AutoGuard292:
.incbin "auto_guard_292.bin"
.ENDS
ROMBLOCK 100, $5b3c
.SECTION "AutoGuard293" FORCE
AutoGuard293:
.incbin "auto_guard_293.bin"
.ENDS
ROMBLOCK 100, $5b56
.SECTION "AutoGuard294" FORCE
AutoGuard294:
.incbin "auto_guard_294.bin"
.ENDS
ROMBLOCK 100, $5b70
.SECTION "AutoGuard295" FORCE
AutoGuard295:
.incbin "auto_guard_295.bin"
.ENDS
ROMBLOCK 100, $5b8a
.SECTION "AutoGuard296" FORCE
AutoGuard296:
.incbin "auto_guard_296.bin"
.ENDS
ROMBLOCK 100, $5ba4
.SECTION "AutoGuard297" FORCE
AutoGuard297:
.incbin "auto_guard_297.bin"
.ENDS
ROMBLOCK 100, $5bbe
.SECTION "AutoGuard298" FORCE
AutoGuard298:
.incbin "auto_guard_298.bin"
.ENDS
ROMBLOCK 100, $5bd8
.SECTION "AutoGuard299" FORCE
AutoGuard299:
.incbin "auto_guard_299.bin"
.ENDS
ROMBLOCK 100, $5bf2
.SECTION "AutoGuard300" FORCE
AutoGuard300:
.incbin "auto_guard_300.bin"
.ENDS
ROMBLOCK 100, $5c0c
.SECTION "AutoGuard301" FORCE
AutoGuard301:
.incbin "auto_guard_301.bin"
.ENDS
ROMBLOCK 100, $5c26
.SECTION "AutoGuard302" FORCE
AutoGuard302:
.incbin "auto_guard_302.bin"
.ENDS
ROMBLOCK 100, $5c40
.SECTION "AutoGuard303" FORCE
AutoGuard303:
.incbin "auto_guard_303.bin"
.ENDS
ROMBLOCK 100, $5c5a
.SECTION "AutoGuard304" FORCE
AutoGuard304:
.incbin "auto_guard_304.bin"
.ENDS
ROMBLOCK 100, $5c74
.SECTION "AutoGuard305" FORCE
AutoGuard305:
.incbin "auto_guard_305.bin"
.ENDS
ROMBLOCK 100, $5c8e
.SECTION "AutoGuard306" FORCE
AutoGuard306:
.incbin "auto_guard_306.bin"
.ENDS
ROMBLOCK 100, $5ca8
.SECTION "AutoGuard307" FORCE
AutoGuard307:
.incbin "auto_guard_307.bin"
.ENDS
ROMBLOCK 100, $5cc2
.SECTION "AutoGuard308" FORCE
AutoGuard308:
.incbin "auto_guard_308.bin"
.ENDS
ROMBLOCK 100, $5cdc
.SECTION "AutoGuard309" FORCE
AutoGuard309:
.incbin "auto_guard_309.bin"
.ENDS
ROMBLOCK 100, $5cf6
.SECTION "AutoGuard310" FORCE
AutoGuard310:
.incbin "auto_guard_310.bin"
.ENDS
ROMBLOCK 100, $5d10
.SECTION "AutoGuard311" FORCE
AutoGuard311:
.incbin "auto_guard_311.bin"
.ENDS
ROMBLOCK 100, $5d2a
.SECTION "AutoGuard312" FORCE
AutoGuard312:
.incbin "auto_guard_312.bin"
.ENDS
ROMBLOCK 100, $5d44
.SECTION "AutoGuard313" FORCE
AutoGuard313:
.incbin "auto_guard_313.bin"
.ENDS
ROMBLOCK 100, $5d5e
.SECTION "AutoGuard314" FORCE
AutoGuard314:
.incbin "auto_guard_314.bin"
.ENDS
ROMBLOCK 100, $5d78
.SECTION "AutoGuard315" FORCE
AutoGuard315:
.incbin "auto_guard_315.bin"
.ENDS
ROMBLOCK 100, $5d92
.SECTION "AutoGuard316" FORCE
AutoGuard316:
.incbin "auto_guard_316.bin"
.ENDS
ROMBLOCK 100, $5dac
.SECTION "AutoGuard317" FORCE
AutoGuard317:
.incbin "auto_guard_317.bin"
.ENDS
ROMBLOCK 100, $5dc6
.SECTION "AutoGuard318" FORCE
AutoGuard318:
.incbin "auto_guard_318.bin"
.ENDS
ROMBLOCK 100, $5de0
.SECTION "AutoGuard319" FORCE
AutoGuard319:
.incbin "auto_guard_319.bin"
.ENDS
ROMBLOCK 100, $5dfa
.SECTION "AutoGuard320" FORCE
AutoGuard320:
.incbin "auto_guard_320.bin"
.ENDS
ROMBLOCK 100, $5e14
.SECTION "AutoGuard321" FORCE
AutoGuard321:
.incbin "auto_guard_321.bin"
.ENDS
ROMBLOCK 100, $5e2e
.SECTION "AutoGuard322" FORCE
AutoGuard322:
.incbin "auto_guard_322.bin"
.ENDS
ROMBLOCK 100, $5e48
.SECTION "AutoGuard323" FORCE
AutoGuard323:
.incbin "auto_guard_323.bin"
.ENDS
ROMBLOCK 100, $5e62
.SECTION "AutoGuard324" FORCE
AutoGuard324:
.incbin "auto_guard_324.bin"
.ENDS
ROMBLOCK 100, $5e7c
.SECTION "AutoGuard325" FORCE
AutoGuard325:
.incbin "auto_guard_325.bin"
.ENDS
ROMBLOCK 100, $5e96
.SECTION "AutoGuard326" FORCE
AutoGuard326:
.incbin "auto_guard_326.bin"
.ENDS
ROMBLOCK 100, $5eb0
.SECTION "AutoGuard327" FORCE
AutoGuard327:
.incbin "auto_guard_327.bin"
.ENDS
ROMBLOCK 100, $5eca
.SECTION "AutoGuard328" FORCE
AutoGuard328:
.incbin "auto_guard_328.bin"
.ENDS
ROMBLOCK 100, $5ee4
.SECTION "AutoGuard329" FORCE
AutoGuard329:
.incbin "auto_guard_329.bin"
.ENDS
ROMBLOCK 100, $5efe
.SECTION "AutoGuard330" FORCE
AutoGuard330:
.incbin "auto_guard_330.bin"
.ENDS
ROMBLOCK 100, $5f18
.SECTION "AutoGuard331" FORCE
AutoGuard331:
.incbin "auto_guard_331.bin"
.ENDS
ROMBLOCK 100, $5f32
.SECTION "AutoGuard332" FORCE
AutoGuard332:
.incbin "auto_guard_332.bin"
.ENDS
ROMBLOCK 100, $5f4c
.SECTION "AutoGuard333" FORCE
AutoGuard333:
.incbin "auto_guard_333.bin"
.ENDS
ROMBLOCK 100, $5f66
.SECTION "AutoGuard334" FORCE
AutoGuard334:
.incbin "auto_guard_334.bin"
.ENDS
ROMBLOCK 100, $5f80
.SECTION "AutoGuard335" FORCE
AutoGuard335:
.incbin "auto_guard_335.bin"
.ENDS
ROMBLOCK 100, $5f9a
.SECTION "AutoGuard336" FORCE
AutoGuard336:
.incbin "auto_guard_336.bin"
.ENDS
ROMBLOCK 100, $5fb4
.SECTION "AutoGuard337" FORCE
AutoGuard337:
.incbin "auto_guard_337.bin"
.ENDS
ROMBLOCK 100, $5fce
.SECTION "AutoGuard338" FORCE
AutoGuard338:
.incbin "auto_guard_338.bin"
.ENDS
ROMBLOCK 100, $5fe8
.SECTION "AutoGuard339" FORCE
AutoGuard339:
.incbin "auto_guard_339.bin"
.ENDS
