AutoExactPointers:
.IFDEF HIROMBUILD
.dw $8000
.db $e3
.ELSE
.dw $8000
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8006
.db $e3
.ELSE
.dw $8006
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $800c
.db $e3
.ELSE
.dw $800c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8012
.db $e3
.ELSE
.dw $8012
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8018
.db $e3
.ELSE
.dw $8018
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8022
.db $e3
.ELSE
.dw $8022
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8028
.db $e3
.ELSE
.dw $8028
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $802e
.db $e3
.ELSE
.dw $802e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8034
.db $e3
.ELSE
.dw $8034
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $803a
.db $e3
.ELSE
.dw $803a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8040
.db $e3
.ELSE
.dw $8040
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8046
.db $e3
.ELSE
.dw $8046
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $804c
.db $e3
.ELSE
.dw $804c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8052
.db $e3
.ELSE
.dw $8052
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8058
.db $e3
.ELSE
.dw $8058
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $805e
.db $e3
.ELSE
.dw $805e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8064
.db $e3
.ELSE
.dw $8064
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $806a
.db $e3
.ELSE
.dw $806a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8070
.db $e3
.ELSE
.dw $8070
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $80ca
.db $e3
.ELSE
.dw $80ca
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $80d0
.db $e3
.ELSE
.dw $80d0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $80da
.db $e3
.ELSE
.dw $80da
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $80e4
.db $e3
.ELSE
.dw $80e4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $810e
.db $e3
.ELSE
.dw $810e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8114
.db $e3
.ELSE
.dw $8114
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $811e
.db $e3
.ELSE
.dw $811e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8124
.db $e3
.ELSE
.dw $8124
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $813a
.db $e3
.ELSE
.dw $813a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8140
.db $e3
.ELSE
.dw $8140
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $814e
.db $e3
.ELSE
.dw $814e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8154
.db $e3
.ELSE
.dw $8154
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $815a
.db $e3
.ELSE
.dw $815a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8164
.db $e3
.ELSE
.dw $8164
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $816e
.db $e3
.ELSE
.dw $816e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8174
.db $e3
.ELSE
.dw $8174
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $817a
.db $e3
.ELSE
.dw $817a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8184
.db $e3
.ELSE
.dw $8184
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $818a
.db $e3
.ELSE
.dw $818a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8190
.db $e3
.ELSE
.dw $8190
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $819e
.db $e3
.ELSE
.dw $819e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81a4
.db $e3
.ELSE
.dw $81a4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81ae
.db $e3
.ELSE
.dw $81ae
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81c0
.db $e3
.ELSE
.dw $81c0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81c6
.db $e3
.ELSE
.dw $81c6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81cc
.db $e3
.ELSE
.dw $81cc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81d2
.db $e3
.ELSE
.dw $81d2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81d8
.db $e3
.ELSE
.dw $81d8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81de
.db $e3
.ELSE
.dw $81de
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81e4
.db $e3
.ELSE
.dw $81e4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81ea
.db $e3
.ELSE
.dw $81ea
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81f0
.db $e3
.ELSE
.dw $81f0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $81fe
.db $e3
.ELSE
.dw $81fe
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8230
.db $e3
.ELSE
.dw $8230
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $823e
.db $e3
.ELSE
.dw $823e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8244
.db $e3
.ELSE
.dw $8244
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8262
.db $e3
.ELSE
.dw $8262
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8274
.db $e3
.ELSE
.dw $8274
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $828a
.db $e3
.ELSE
.dw $828a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8290
.db $e3
.ELSE
.dw $8290
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8296
.db $e3
.ELSE
.dw $8296
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $82a8
.db $e3
.ELSE
.dw $82a8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $82de
.db $e3
.ELSE
.dw $82de
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $82e4
.db $e3
.ELSE
.dw $82e4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $82ee
.db $e3
.ELSE
.dw $82ee
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $82f4
.db $e3
.ELSE
.dw $82f4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $82fe
.db $e3
.ELSE
.dw $82fe
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8304
.db $e3
.ELSE
.dw $8304
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $830a
.db $e3
.ELSE
.dw $830a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $831c
.db $e3
.ELSE
.dw $831c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $832a
.db $e3
.ELSE
.dw $832a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8334
.db $e3
.ELSE
.dw $8334
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $833a
.db $e3
.ELSE
.dw $833a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8340
.db $e3
.ELSE
.dw $8340
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8346
.db $e3
.ELSE
.dw $8346
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $834c
.db $e3
.ELSE
.dw $834c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8352
.db $e3
.ELSE
.dw $8352
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8358
.db $e3
.ELSE
.dw $8358
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $835e
.db $e3
.ELSE
.dw $835e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8368
.db $e3
.ELSE
.dw $8368
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8376
.db $e3
.ELSE
.dw $8376
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8388
.db $e3
.ELSE
.dw $8388
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $838e
.db $e3
.ELSE
.dw $838e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8394
.db $e3
.ELSE
.dw $8394
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83a2
.db $e3
.ELSE
.dw $83a2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83a8
.db $e3
.ELSE
.dw $83a8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83ae
.db $e3
.ELSE
.dw $83ae
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83c0
.db $e3
.ELSE
.dw $83c0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83ca
.db $e3
.ELSE
.dw $83ca
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83d0
.db $e3
.ELSE
.dw $83d0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83d6
.db $e3
.ELSE
.dw $83d6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83dc
.db $e3
.ELSE
.dw $83dc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83e2
.db $e3
.ELSE
.dw $83e2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83e8
.db $e3
.ELSE
.dw $83e8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83f2
.db $e3
.ELSE
.dw $83f2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83f8
.db $e3
.ELSE
.dw $83f8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $83fe
.db $e3
.ELSE
.dw $83fe
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8404
.db $e3
.ELSE
.dw $8404
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $840a
.db $e3
.ELSE
.dw $840a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8410
.db $e3
.ELSE
.dw $8410
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8416
.db $e3
.ELSE
.dw $8416
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $841c
.db $e3
.ELSE
.dw $841c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8422
.db $e3
.ELSE
.dw $8422
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $842c
.db $e3
.ELSE
.dw $842c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8432
.db $e3
.ELSE
.dw $8432
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8438
.db $e3
.ELSE
.dw $8438
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $843e
.db $e3
.ELSE
.dw $843e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8444
.db $e3
.ELSE
.dw $8444
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $844a
.db $e3
.ELSE
.dw $844a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8450
.db $e3
.ELSE
.dw $8450
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8456
.db $e3
.ELSE
.dw $8456
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $845c
.db $e3
.ELSE
.dw $845c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8462
.db $e3
.ELSE
.dw $8462
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8468
.db $e3
.ELSE
.dw $8468
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $846e
.db $e3
.ELSE
.dw $846e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8474
.db $e3
.ELSE
.dw $8474
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $847a
.db $e3
.ELSE
.dw $847a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8480
.db $e3
.ELSE
.dw $8480
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8486
.db $e3
.ELSE
.dw $8486
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $849c
.db $e3
.ELSE
.dw $849c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84a2
.db $e3
.ELSE
.dw $84a2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84ac
.db $e3
.ELSE
.dw $84ac
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84b2
.db $e3
.ELSE
.dw $84b2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84bc
.db $e3
.ELSE
.dw $84bc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84c2
.db $e3
.ELSE
.dw $84c2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84c8
.db $e3
.ELSE
.dw $84c8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84ce
.db $e3
.ELSE
.dw $84ce
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84d4
.db $e3
.ELSE
.dw $84d4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84da
.db $e3
.ELSE
.dw $84da
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84e0
.db $e3
.ELSE
.dw $84e0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84e6
.db $e3
.ELSE
.dw $84e6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84ec
.db $e3
.ELSE
.dw $84ec
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84f2
.db $e3
.ELSE
.dw $84f2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84f8
.db $e3
.ELSE
.dw $84f8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $84fe
.db $e3
.ELSE
.dw $84fe
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8504
.db $e3
.ELSE
.dw $8504
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $850a
.db $e3
.ELSE
.dw $850a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8510
.db $e3
.ELSE
.dw $8510
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8516
.db $e3
.ELSE
.dw $8516
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $851c
.db $e3
.ELSE
.dw $851c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8522
.db $e3
.ELSE
.dw $8522
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8528
.db $e3
.ELSE
.dw $8528
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $852e
.db $e3
.ELSE
.dw $852e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8534
.db $e3
.ELSE
.dw $8534
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $853a
.db $e3
.ELSE
.dw $853a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8540
.db $e3
.ELSE
.dw $8540
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8546
.db $e3
.ELSE
.dw $8546
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $854c
.db $e3
.ELSE
.dw $854c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8552
.db $e3
.ELSE
.dw $8552
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8558
.db $e3
.ELSE
.dw $8558
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $855e
.db $e3
.ELSE
.dw $855e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8564
.db $e3
.ELSE
.dw $8564
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $856a
.db $e3
.ELSE
.dw $856a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8570
.db $e3
.ELSE
.dw $8570
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8576
.db $e3
.ELSE
.dw $8576
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $857c
.db $e3
.ELSE
.dw $857c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8586
.db $e3
.ELSE
.dw $8586
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $858c
.db $e3
.ELSE
.dw $858c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8592
.db $e3
.ELSE
.dw $8592
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8598
.db $e3
.ELSE
.dw $8598
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $859e
.db $e3
.ELSE
.dw $859e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85a4
.db $e3
.ELSE
.dw $85a4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85aa
.db $e3
.ELSE
.dw $85aa
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85b0
.db $e3
.ELSE
.dw $85b0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85b6
.db $e3
.ELSE
.dw $85b6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85bc
.db $e3
.ELSE
.dw $85bc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85c2
.db $e3
.ELSE
.dw $85c2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85c8
.db $e3
.ELSE
.dw $85c8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85d2
.db $e3
.ELSE
.dw $85d2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85dc
.db $e3
.ELSE
.dw $85dc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85e2
.db $e3
.ELSE
.dw $85e2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85ec
.db $e3
.ELSE
.dw $85ec
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85f2
.db $e3
.ELSE
.dw $85f2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85f8
.db $e3
.ELSE
.dw $85f8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $85fe
.db $e3
.ELSE
.dw $85fe
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $860c
.db $e3
.ELSE
.dw $860c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8612
.db $e3
.ELSE
.dw $8612
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8618
.db $e3
.ELSE
.dw $8618
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8622
.db $e3
.ELSE
.dw $8622
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8628
.db $e3
.ELSE
.dw $8628
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $862e
.db $e3
.ELSE
.dw $862e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8698
.db $e3
.ELSE
.dw $8698
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $869e
.db $e3
.ELSE
.dw $869e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86a4
.db $e3
.ELSE
.dw $86a4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86be
.db $e3
.ELSE
.dw $86be
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86c4
.db $e3
.ELSE
.dw $86c4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86ca
.db $e3
.ELSE
.dw $86ca
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86d0
.db $e3
.ELSE
.dw $86d0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86d6
.db $e3
.ELSE
.dw $86d6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86dc
.db $e3
.ELSE
.dw $86dc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86e2
.db $e3
.ELSE
.dw $86e2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86e8
.db $e3
.ELSE
.dw $86e8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $86ee
.db $e3
.ELSE
.dw $86ee
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8724
.db $e3
.ELSE
.dw $8724
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8732
.db $e3
.ELSE
.dw $8732
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8738
.db $e3
.ELSE
.dw $8738
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8742
.db $e3
.ELSE
.dw $8742
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8748
.db $e3
.ELSE
.dw $8748
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8752
.db $e3
.ELSE
.dw $8752
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8758
.db $e3
.ELSE
.dw $8758
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $875e
.db $e3
.ELSE
.dw $875e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8768
.db $e3
.ELSE
.dw $8768
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $876e
.db $e3
.ELSE
.dw $876e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $877c
.db $e3
.ELSE
.dw $877c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8782
.db $e3
.ELSE
.dw $8782
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8788
.db $e3
.ELSE
.dw $8788
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8792
.db $e3
.ELSE
.dw $8792
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $879c
.db $e3
.ELSE
.dw $879c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87a2
.db $e3
.ELSE
.dw $87a2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87a8
.db $e3
.ELSE
.dw $87a8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87ae
.db $e3
.ELSE
.dw $87ae
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87b4
.db $e3
.ELSE
.dw $87b4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87ba
.db $e3
.ELSE
.dw $87ba
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87c4
.db $e3
.ELSE
.dw $87c4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87ca
.db $e3
.ELSE
.dw $87ca
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87d0
.db $e3
.ELSE
.dw $87d0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87d6
.db $e3
.ELSE
.dw $87d6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87dc
.db $e3
.ELSE
.dw $87dc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87e2
.db $e3
.ELSE
.dw $87e2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $87e8
.db $e3
.ELSE
.dw $87e8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $888e
.db $e3
.ELSE
.dw $888e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8894
.db $e3
.ELSE
.dw $8894
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $889a
.db $e3
.ELSE
.dw $889a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88a0
.db $e3
.ELSE
.dw $88a0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88a6
.db $e3
.ELSE
.dw $88a6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88ac
.db $e3
.ELSE
.dw $88ac
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88c6
.db $e3
.ELSE
.dw $88c6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88cc
.db $e3
.ELSE
.dw $88cc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88d2
.db $e3
.ELSE
.dw $88d2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88d8
.db $e3
.ELSE
.dw $88d8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88de
.db $e3
.ELSE
.dw $88de
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88e4
.db $e3
.ELSE
.dw $88e4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88ea
.db $e3
.ELSE
.dw $88ea
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88f0
.db $e3
.ELSE
.dw $88f0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88f6
.db $e3
.ELSE
.dw $88f6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $88fc
.db $e3
.ELSE
.dw $88fc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8902
.db $e3
.ELSE
.dw $8902
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8908
.db $e3
.ELSE
.dw $8908
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $890e
.db $e3
.ELSE
.dw $890e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8914
.db $e3
.ELSE
.dw $8914
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $891a
.db $e3
.ELSE
.dw $891a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8920
.db $e3
.ELSE
.dw $8920
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8926
.db $e3
.ELSE
.dw $8926
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $892c
.db $e3
.ELSE
.dw $892c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8932
.db $e3
.ELSE
.dw $8932
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8938
.db $e3
.ELSE
.dw $8938
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $893e
.db $e3
.ELSE
.dw $893e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8944
.db $e3
.ELSE
.dw $8944
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $898a
.db $e3
.ELSE
.dw $898a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8990
.db $e3
.ELSE
.dw $8990
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $899a
.db $e3
.ELSE
.dw $899a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $89a0
.db $e3
.ELSE
.dw $89a0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $89a6
.db $e3
.ELSE
.dw $89a6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $89b0
.db $e3
.ELSE
.dw $89b0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $89ba
.db $e3
.ELSE
.dw $89ba
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a24
.db $e3
.ELSE
.dw $8a24
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a2a
.db $e3
.ELSE
.dw $8a2a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a30
.db $e3
.ELSE
.dw $8a30
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a3a
.db $e3
.ELSE
.dw $8a3a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a40
.db $e3
.ELSE
.dw $8a40
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a46
.db $e3
.ELSE
.dw $8a46
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a4c
.db $e3
.ELSE
.dw $8a4c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a52
.db $e3
.ELSE
.dw $8a52
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a58
.db $e3
.ELSE
.dw $8a58
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a5e
.db $e3
.ELSE
.dw $8a5e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a64
.db $e3
.ELSE
.dw $8a64
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a6a
.db $e3
.ELSE
.dw $8a6a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a70
.db $e3
.ELSE
.dw $8a70
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a76
.db $e3
.ELSE
.dw $8a76
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a80
.db $e3
.ELSE
.dw $8a80
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a86
.db $e3
.ELSE
.dw $8a86
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a8c
.db $e3
.ELSE
.dw $8a8c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8a96
.db $e3
.ELSE
.dw $8a96
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8aa0
.db $e3
.ELSE
.dw $8aa0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8aa6
.db $e3
.ELSE
.dw $8aa6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8aac
.db $e3
.ELSE
.dw $8aac
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ab2
.db $e3
.ELSE
.dw $8ab2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ab8
.db $e3
.ELSE
.dw $8ab8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8abe
.db $e3
.ELSE
.dw $8abe
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ac4
.db $e3
.ELSE
.dw $8ac4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8aca
.db $e3
.ELSE
.dw $8aca
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ad0
.db $e3
.ELSE
.dw $8ad0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ad6
.db $e3
.ELSE
.dw $8ad6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8adc
.db $e3
.ELSE
.dw $8adc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ae2
.db $e3
.ELSE
.dw $8ae2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ae8
.db $e3
.ELSE
.dw $8ae8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8aee
.db $e3
.ELSE
.dw $8aee
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8af4
.db $e3
.ELSE
.dw $8af4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8afa
.db $e3
.ELSE
.dw $8afa
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b00
.db $e3
.ELSE
.dw $8b00
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b06
.db $e3
.ELSE
.dw $8b06
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b0c
.db $e3
.ELSE
.dw $8b0c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b12
.db $e3
.ELSE
.dw $8b12
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b18
.db $e3
.ELSE
.dw $8b18
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b1e
.db $e3
.ELSE
.dw $8b1e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b24
.db $e3
.ELSE
.dw $8b24
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b2a
.db $e3
.ELSE
.dw $8b2a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b30
.db $e3
.ELSE
.dw $8b30
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b36
.db $e3
.ELSE
.dw $8b36
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b3c
.db $e3
.ELSE
.dw $8b3c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b42
.db $e3
.ELSE
.dw $8b42
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b48
.db $e3
.ELSE
.dw $8b48
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b4e
.db $e3
.ELSE
.dw $8b4e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b54
.db $e3
.ELSE
.dw $8b54
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b5a
.db $e3
.ELSE
.dw $8b5a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b60
.db $e3
.ELSE
.dw $8b60
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b66
.db $e3
.ELSE
.dw $8b66
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b6c
.db $e3
.ELSE
.dw $8b6c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b72
.db $e3
.ELSE
.dw $8b72
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b78
.db $e3
.ELSE
.dw $8b78
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b7e
.db $e3
.ELSE
.dw $8b7e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b84
.db $e3
.ELSE
.dw $8b84
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b8a
.db $e3
.ELSE
.dw $8b8a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b90
.db $e3
.ELSE
.dw $8b90
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b96
.db $e3
.ELSE
.dw $8b96
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8b9c
.db $e3
.ELSE
.dw $8b9c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ba2
.db $e3
.ELSE
.dw $8ba2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ba8
.db $e3
.ELSE
.dw $8ba8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bae
.db $e3
.ELSE
.dw $8bae
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bb4
.db $e3
.ELSE
.dw $8bb4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bba
.db $e3
.ELSE
.dw $8bba
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bc0
.db $e3
.ELSE
.dw $8bc0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bc6
.db $e3
.ELSE
.dw $8bc6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bcc
.db $e3
.ELSE
.dw $8bcc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bd2
.db $e3
.ELSE
.dw $8bd2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bd8
.db $e3
.ELSE
.dw $8bd8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bde
.db $e3
.ELSE
.dw $8bde
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8be4
.db $e3
.ELSE
.dw $8be4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bea
.db $e3
.ELSE
.dw $8bea
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bf0
.db $e3
.ELSE
.dw $8bf0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bf6
.db $e3
.ELSE
.dw $8bf6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8bfc
.db $e3
.ELSE
.dw $8bfc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c02
.db $e3
.ELSE
.dw $8c02
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c08
.db $e3
.ELSE
.dw $8c08
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c0e
.db $e3
.ELSE
.dw $8c0e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c14
.db $e3
.ELSE
.dw $8c14
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c1a
.db $e3
.ELSE
.dw $8c1a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c20
.db $e3
.ELSE
.dw $8c20
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c26
.db $e3
.ELSE
.dw $8c26
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c2c
.db $e3
.ELSE
.dw $8c2c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c32
.db $e3
.ELSE
.dw $8c32
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c38
.db $e3
.ELSE
.dw $8c38
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c3e
.db $e3
.ELSE
.dw $8c3e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c44
.db $e3
.ELSE
.dw $8c44
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c4a
.db $e3
.ELSE
.dw $8c4a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c50
.db $e3
.ELSE
.dw $8c50
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c56
.db $e3
.ELSE
.dw $8c56
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c5c
.db $e3
.ELSE
.dw $8c5c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c62
.db $e3
.ELSE
.dw $8c62
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c68
.db $e3
.ELSE
.dw $8c68
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c6e
.db $e3
.ELSE
.dw $8c6e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c74
.db $e3
.ELSE
.dw $8c74
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c7a
.db $e3
.ELSE
.dw $8c7a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c80
.db $e3
.ELSE
.dw $8c80
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c86
.db $e3
.ELSE
.dw $8c86
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c8c
.db $e3
.ELSE
.dw $8c8c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c92
.db $e3
.ELSE
.dw $8c92
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c98
.db $e3
.ELSE
.dw $8c98
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8c9e
.db $e3
.ELSE
.dw $8c9e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ca4
.db $e3
.ELSE
.dw $8ca4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8caa
.db $e3
.ELSE
.dw $8caa
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cb0
.db $e3
.ELSE
.dw $8cb0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cb6
.db $e3
.ELSE
.dw $8cb6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cbc
.db $e3
.ELSE
.dw $8cbc
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cc2
.db $e3
.ELSE
.dw $8cc2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cc8
.db $e3
.ELSE
.dw $8cc8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cce
.db $e3
.ELSE
.dw $8cce
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cd4
.db $e3
.ELSE
.dw $8cd4
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cda
.db $e3
.ELSE
.dw $8cda
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ce0
.db $e3
.ELSE
.dw $8ce0
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8ce6
.db $e3
.ELSE
.dw $8ce6
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cec
.db $e3
.ELSE
.dw $8cec
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cf2
.db $e3
.ELSE
.dw $8cf2
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cf8
.db $e3
.ELSE
.dw $8cf8
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8cfe
.db $e3
.ELSE
.dw $8cfe
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d04
.db $e3
.ELSE
.dw $8d04
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d0a
.db $e3
.ELSE
.dw $8d0a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d10
.db $e3
.ELSE
.dw $8d10
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d16
.db $e3
.ELSE
.dw $8d16
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d1c
.db $e3
.ELSE
.dw $8d1c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d22
.db $e3
.ELSE
.dw $8d22
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d28
.db $e3
.ELSE
.dw $8d28
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d2e
.db $e3
.ELSE
.dw $8d2e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d34
.db $e3
.ELSE
.dw $8d34
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d3a
.db $e3
.ELSE
.dw $8d3a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d40
.db $e3
.ELSE
.dw $8d40
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d46
.db $e3
.ELSE
.dw $8d46
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d4c
.db $e3
.ELSE
.dw $8d4c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d52
.db $e3
.ELSE
.dw $8d52
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d58
.db $e3
.ELSE
.dw $8d58
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d5e
.db $e3
.ELSE
.dw $8d5e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d64
.db $e3
.ELSE
.dw $8d64
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d6a
.db $e3
.ELSE
.dw $8d6a
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d70
.db $e3
.ELSE
.dw $8d70
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d76
.db $e3
.ELSE
.dw $8d76
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d7c
.db $e3
.ELSE
.dw $8d7c
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d82
.db $e3
.ELSE
.dw $8d82
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d88
.db $e3
.ELSE
.dw $8d88
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d8e
.db $e3
.ELSE
.dw $8d8e
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d94
.db $e3
.ELSE
.dw $8d94
.db $47
.ENDIF
.IFDEF HIROMBUILD
.dw $8d9a
.db $e3
.ELSE
.dw $8d9a
.db $47
.ENDIF
