AutoGuardPointers:
.IFDEF HIROMBUILD
.dw $0cea
.db $e4
.ELSE
.dw $8cea
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $0d04
.db $e4
.ELSE
.dw $8d04
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $19ff
.db $e4
.ELSE
.dw $99ff
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1a19
.db $e4
.ELSE
.dw $9a19
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1a33
.db $e4
.ELSE
.dw $9a33
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1a4d
.db $e4
.ELSE
.dw $9a4d
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1a67
.db $e4
.ELSE
.dw $9a67
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1a81
.db $e4
.ELSE
.dw $9a81
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1a9b
.db $e4
.ELSE
.dw $9a9b
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1ab5
.db $e4
.ELSE
.dw $9ab5
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1acf
.db $e4
.ELSE
.dw $9acf
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1ae9
.db $e4
.ELSE
.dw $9ae9
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1b03
.db $e4
.ELSE
.dw $9b03
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1b1d
.db $e4
.ELSE
.dw $9b1d
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1b37
.db $e4
.ELSE
.dw $9b37
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1b51
.db $e4
.ELSE
.dw $9b51
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1b6b
.db $e4
.ELSE
.dw $9b6b
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $1b85
.db $e4
.ELSE
.dw $9b85
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $3744
.db $e4
.ELSE
.dw $b744
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $52fd
.db $e4
.ELSE
.dw $d2fd
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $6ec5
.db $e4
.ELSE
.dw $eec5
.db $48
.ENDIF
.IFDEF HIROMBUILD
.dw $9bb7
.db $e4
.ELSE
.dw $9bb7
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $b789
.db $e4
.ELSE
.dw $b789
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $b7a7
.db $e4
.ELSE
.dw $b7a7
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $b7c9
.db $e4
.ELSE
.dw $b7c9
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $b7ef
.db $e4
.ELSE
.dw $b7ef
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $c64c
.db $e4
.ELSE
.dw $c64c
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $c66a
.db $e4
.ELSE
.dw $c66a
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $c688
.db $e4
.ELSE
.dw $c688
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $c6a6
.db $e4
.ELSE
.dw $c6a6
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $dccc
.db $e4
.ELSE
.dw $dccc
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $f312
.db $e4
.ELSE
.dw $f312
.db $49
.ENDIF
.IFDEF HIROMBUILD
.dw $160b
.db $e5
.ELSE
.dw $960b
.db $4a
.ENDIF
.IFDEF HIROMBUILD
.dw $2c2d
.db $e5
.ELSE
.dw $ac2d
.db $4a
.ENDIF
.IFDEF HIROMBUILD
.dw $424f
.db $e5
.ELSE
.dw $c24f
.db $4a
.ENDIF
.IFDEF HIROMBUILD
.dw $58a4
.db $e5
.ELSE
.dw $d8a4
.db $4a
.ENDIF
.IFDEF HIROMBUILD
.dw $6ecf
.db $e5
.ELSE
.dw $eecf
.db $4a
.ENDIF
.IFDEF HIROMBUILD
.dw $962f
.db $e5
.ELSE
.dw $962f
.db $4b
.ENDIF
.IFDEF HIROMBUILD
.dw $b152
.db $e5
.ELSE
.dw $b152
.db $4b
.ENDIF
.IFDEF HIROMBUILD
.dw $cc6b
.db $e5
.ELSE
.dw $cc6b
.db $4b
.ENDIF
.IFDEF HIROMBUILD
.dw $e785
.db $e5
.ELSE
.dw $e785
.db $4b
.ENDIF
.IFDEF HIROMBUILD
.dw $1b06
.db $e6
.ELSE
.dw $9b06
.db $4c
.ENDIF
.IFDEF HIROMBUILD
.dw $362f
.db $e6
.ELSE
.dw $b62f
.db $4c
.ENDIF
.IFDEF HIROMBUILD
.dw $5164
.db $e6
.ELSE
.dw $d164
.db $4c
.ENDIF
.IFDEF HIROMBUILD
.dw $6c93
.db $e6
.ELSE
.dw $ec93
.db $4c
.ENDIF
.IFDEF HIROMBUILD
.dw $9bed
.db $e6
.ELSE
.dw $9bed
.db $4d
.ENDIF
.IFDEF HIROMBUILD
.dw $b71f
.db $e6
.ELSE
.dw $b71f
.db $4d
.ENDIF
.IFDEF HIROMBUILD
.dw $d24e
.db $e6
.ELSE
.dw $d24e
.db $4d
.ENDIF
.IFDEF HIROMBUILD
.dw $ed74
.db $e6
.ELSE
.dw $ed74
.db $4d
.ENDIF
.IFDEF HIROMBUILD
.dw $1b12
.db $e7
.ELSE
.dw $9b12
.db $4e
.ENDIF
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.IFDEF HIROMBUILD
.dw $39ce
.db $e7
.ELSE
.dw $b9ce
.db $4e
.ENDIF
.IFDEF HIROMBUILD
.dw $5f1a
.db $e7
.ELSE
.dw $df1a
.db $4e
.ENDIF
.IFDEF HIROMBUILD
.dw $a53b
.db $e7
.ELSE
.dw $a53b
.db $4f
.ENDIF
.IFDEF HIROMBUILD
.dw $c51a
.db $e7
.ELSE
.dw $c51a
.db $4f
.ENDIF
.dw 0
.db 0
.IFDEF HIROMBUILD
.dw $ec79
.db $e7
.ELSE
.dw $ec79
.db $4f
.ENDIF
.IFDEF HIROMBUILD
.dw $2727
.db $e8
.ELSE
.dw $a727
.db $50
.ENDIF
.IFDEF HIROMBUILD
.dw $4514
.db $e8
.ELSE
.dw $c514
.db $50
.ENDIF
.IFDEF HIROMBUILD
.dw $6393
.db $e8
.ELSE
.dw $e393
.db $50
.ENDIF
.IFDEF HIROMBUILD
.dw $9ee4
.db $e8
.ELSE
.dw $9ee4
.db $51
.ENDIF
.IFDEF HIROMBUILD
.dw $bd21
.db $e8
.ELSE
.dw $bd21
.db $51
.ENDIF
.IFDEF HIROMBUILD
.dw $db4c
.db $e8
.ELSE
.dw $db4c
.db $51
.ENDIF
.IFDEF HIROMBUILD
.dw $fa5e
.db $e8
.ELSE
.dw $fa5e
.db $51
.ENDIF
.IFDEF HIROMBUILD
.dw $1dbe
.db $e9
.ELSE
.dw $9dbe
.db $52
.ENDIF
.IFDEF HIROMBUILD
.dw $3c10
.db $e9
.ELSE
.dw $bc10
.db $52
.ENDIF
.IFDEF HIROMBUILD
.dw $52dd
.db $e9
.ELSE
.dw $d2dd
.db $52
.ENDIF
.IFDEF HIROMBUILD
.dw $69ad
.db $e9
.ELSE
.dw $e9ad
.db $52
.ENDIF
.IFDEF HIROMBUILD
.dw $96b0
.db $e9
.ELSE
.dw $96b0
.db $53
.ENDIF
.IFDEF HIROMBUILD
.dw $ad77
.db $e9
.ELSE
.dw $ad77
.db $53
.ENDIF
.IFDEF HIROMBUILD
.dw $c435
.db $e9
.ELSE
.dw $c435
.db $53
.ENDIF
.IFDEF HIROMBUILD
.dw $dafd
.db $e9
.ELSE
.dw $dafd
.db $53
.ENDIF
.IFDEF HIROMBUILD
.dw $db1f
.db $e9
.ELSE
.dw $db1f
.db $53
.ENDIF
.IFDEF HIROMBUILD
.dw $db41
.db $e9
.ELSE
.dw $db41
.db $53
.ENDIF
.IFDEF HIROMBUILD
.dw $f257
.db $e9
.ELSE
.dw $f257
.db $53
.ENDIF
.IFDEF HIROMBUILD
.dw $16ad
.db $ea
.ELSE
.dw $96ad
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $2d72
.db $ea
.ELSE
.dw $ad72
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $443e
.db $ea
.ELSE
.dw $c43e
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $445c
.db $ea
.ELSE
.dw $c45c
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $573f
.db $ea
.ELSE
.dw $d73f
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $6a1f
.db $ea
.ELSE
.dw $ea1f
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $6a39
.db $ea
.ELSE
.dw $ea39
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $6a53
.db $ea
.ELSE
.dw $ea53
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $6a6d
.db $ea
.ELSE
.dw $ea6d
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $6a87
.db $ea
.ELSE
.dw $ea87
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $6aa1
.db $ea
.ELSE
.dw $eaa1
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $7cdc
.db $ea
.ELSE
.dw $fcdc
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $7cf6
.db $ea
.ELSE
.dw $fcf6
.db $54
.ENDIF
.dw 0
.db 0
.IFDEF HIROMBUILD
.dw $7d10
.db $ea
.ELSE
.dw $fd10
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $7d2a
.db $ea
.ELSE
.dw $fd2a
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $7cdc
.db $ea
.ELSE
.dw $fcdc
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $7d44
.db $ea
.ELSE
.dw $fd44
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $7d5e
.db $ea
.ELSE
.dw $fd5e
.db $54
.ENDIF
.IFDEF HIROMBUILD
.dw $978b
.db $ea
.ELSE
.dw $978b
.db $55
.ENDIF
.IFDEF HIROMBUILD
.dw $af34
.db $ea
.ELSE
.dw $af34
.db $55
.ENDIF
.IFDEF HIROMBUILD
.dw $c6da
.db $ea
.ELSE
.dw $c6da
.db $55
.ENDIF
.IFDEF HIROMBUILD
.dw $de7d
.db $ea
.ELSE
.dw $de7d
.db $55
.ENDIF
.IFDEF HIROMBUILD
.dw $f627
.db $ea
.ELSE
.dw $f627
.db $55
.ENDIF
.IFDEF HIROMBUILD
.dw $178e
.db $eb
.ELSE
.dw $978e
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $2f3e
.db $eb
.ELSE
.dw $af3e
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $2f60
.db $eb
.ELSE
.dw $af60
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $2f8e
.db $eb
.ELSE
.dw $af8e
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $473c
.db $eb
.ELSE
.dw $c73c
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $5ef6
.db $eb
.ELSE
.dw $def6
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $5f1c
.db $eb
.ELSE
.dw $df1c
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $5ef6
.db $eb
.ELSE
.dw $def6
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $76cd
.db $eb
.ELSE
.dw $f6cd
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $978b
.db $eb
.ELSE
.dw $978b
.db $57
.ENDIF
.IFDEF HIROMBUILD
.dw $97b1
.db $eb
.ELSE
.dw $97b1
.db $57
.ENDIF
.IFDEF HIROMBUILD
.dw $af5c
.db $eb
.ELSE
.dw $af5c
.db $57
.ENDIF
.IFDEF HIROMBUILD
.dw $c722
.db $eb
.ELSE
.dw $c722
.db $57
.ENDIF
.IFDEF HIROMBUILD
.dw $c748
.db $eb
.ELSE
.dw $c748
.db $57
.ENDIF
.IFDEF HIROMBUILD
.dw $2f8e
.db $eb
.ELSE
.dw $af8e
.db $56
.ENDIF
.IFDEF HIROMBUILD
.dw $df0b
.db $eb
.ELSE
.dw $df0b
.db $57
.ENDIF
.IFDEF HIROMBUILD
.dw $f6b6
.db $eb
.ELSE
.dw $f6b6
.db $57
.ENDIF
.IFDEF HIROMBUILD
.dw $178e
.db $ec
.ELSE
.dw $978e
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $17b0
.db $ec
.ELSE
.dw $97b0
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $2f63
.db $ec
.ELSE
.dw $af63
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $2f89
.db $ec
.ELSE
.dw $af89
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $2f89
.db $ec
.ELSE
.dw $af89
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $2faf
.db $ec
.ELSE
.dw $afaf
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $4766
.db $ec
.ELSE
.dw $c766
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $2faf
.db $ec
.ELSE
.dw $afaf
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $5f17
.db $ec
.ELSE
.dw $df17
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $76ca
.db $ec
.ELSE
.dw $f6ca
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $978e
.db $ec
.ELSE
.dw $978e
.db $59
.ENDIF
.IFDEF HIROMBUILD
.dw $af3b
.db $ec
.ELSE
.dw $af3b
.db $59
.ENDIF
.IFDEF HIROMBUILD
.dw $c6e5
.db $ec
.ELSE
.dw $c6e5
.db $59
.ENDIF
.IFDEF HIROMBUILD
.dw $de99
.db $ec
.ELSE
.dw $de99
.db $59
.ENDIF
.IFDEF HIROMBUILD
.dw $f64a
.db $ec
.ELSE
.dw $f64a
.db $59
.ENDIF
.IFDEF HIROMBUILD
.dw $178b
.db $ed
.ELSE
.dw $978b
.db $5a
.ENDIF
.IFDEF HIROMBUILD
.dw $17ad
.db $ed
.ELSE
.dw $97ad
.db $5a
.ENDIF
.IFDEF HIROMBUILD
.dw $2f5a
.db $ed
.ELSE
.dw $af5a
.db $5a
.ENDIF
.IFDEF HIROMBUILD
.dw $4704
.db $ed
.ELSE
.dw $c704
.db $5a
.ENDIF
.IFDEF HIROMBUILD
.dw $5eb1
.db $ed
.ELSE
.dw $deb1
.db $5a
.ENDIF
.IFDEF HIROMBUILD
.dw $17b0
.db $ec
.ELSE
.dw $97b0
.db $58
.ENDIF
.IFDEF HIROMBUILD
.dw $7664
.db $ed
.ELSE
.dw $f664
.db $5a
.ENDIF
.IFDEF HIROMBUILD
.dw $7686
.db $ed
.ELSE
.dw $f686
.db $5a
.ENDIF
.IFDEF HIROMBUILD
.dw $9794
.db $ed
.ELSE
.dw $9794
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $97b6
.db $ed
.ELSE
.dw $97b6
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $af5a
.db $ed
.ELSE
.dw $af5a
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $af7c
.db $ed
.ELSE
.dw $af7c
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $af9e
.db $ed
.ELSE
.dw $af9e
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $c75b
.db $ed
.ELSE
.dw $c75b
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $df08
.db $ed
.ELSE
.dw $df08
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $df1e
.db $ed
.ELSE
.dw $df1e
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f6c5
.db $ed
.ELSE
.dw $f6c5
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f6db
.db $ed
.ELSE
.dw $f6db
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f701
.db $ed
.ELSE
.dw $f701
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f727
.db $ed
.ELSE
.dw $f727
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f74d
.db $ed
.ELSE
.dw $f74d
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f76f
.db $ed
.ELSE
.dw $f76f
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $af7c
.db $ed
.ELSE
.dw $af7c
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f791
.db $ed
.ELSE
.dw $f791
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $f7b3
.db $ed
.ELSE
.dw $f7b3
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $178e
.db $ee
.ELSE
.dw $978e
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $af7c
.db $ed
.ELSE
.dw $af7c
.db $5b
.ENDIF
.IFDEF HIROMBUILD
.dw $2305
.db $ee
.ELSE
.dw $a305
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $231f
.db $ee
.ELSE
.dw $a31f
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $2eee
.db $ee
.ELSE
.dw $aeee
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $3b41
.db $ee
.ELSE
.dw $bb41
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $4716
.db $ee
.ELSE
.dw $c716
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $52e5
.db $ee
.ELSE
.dw $d2e5
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $5e69
.db $ee
.ELSE
.dw $de69
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $6a47
.db $ee
.ELSE
.dw $ea47
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $7619
.db $ee
.ELSE
.dw $f619
.db $5c
.ENDIF
.IFDEF HIROMBUILD
.dw $8b85
.db $ee
.ELSE
.dw $8b85
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $9754
.db $ee
.ELSE
.dw $9754
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $a2f0
.db $ee
.ELSE
.dw $a2f0
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $a30a
.db $ee
.ELSE
.dw $a30a
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $aec7
.db $ee
.ELSE
.dw $aec7
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $bdea
.db $ee
.ELSE
.dw $bdea
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $be04
.db $ee
.ELSE
.dw $be04
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $be22
.db $ee
.ELSE
.dw $be22
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $be3c
.db $ee
.ELSE
.dw $be3c
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $be56
.db $ee
.ELSE
.dw $be56
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $cd98
.db $ee
.ELSE
.dw $cd98
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $cdba
.db $ee
.ELSE
.dw $cdba
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $cdd8
.db $ee
.ELSE
.dw $cdd8
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $cdf6
.db $ee
.ELSE
.dw $cdf6
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $ce18
.db $ee
.ELSE
.dw $ce18
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $ce36
.db $ee
.ELSE
.dw $ce36
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $ce54
.db $ee
.ELSE
.dw $ce54
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $e9b5
.db $ee
.ELSE
.dw $e9b5
.db $5d
.ENDIF
.dw 0
.db 0
.dw 0
.db 0
.IFDEF HIROMBUILD
.dw $fdf6
.db $ee
.ELSE
.dw $fdf6
.db $5d
.ENDIF
.IFDEF HIROMBUILD
.dw $140d
.db $ef
.ELSE
.dw $940d
.db $5e
.ENDIF
.IFDEF HIROMBUILD
.dw $282a
.db $ef
.ELSE
.dw $a82a
.db $5e
.ENDIF
.IFDEF HIROMBUILD
.dw $3c51
.db $ef
.ELSE
.dw $bc51
.db $5e
.ENDIF
.IFDEF HIROMBUILD
.dw $509c
.db $ef
.ELSE
.dw $d09c
.db $5e
.ENDIF
.IFDEF HIROMBUILD
.dw $64dc
.db $ef
.ELSE
.dw $e4dc
.db $5e
.ENDIF
.IFDEF HIROMBUILD
.dw $790b
.db $ef
.ELSE
.dw $f90b
.db $5e
.ENDIF
.IFDEF HIROMBUILD
.dw $9416
.db $ef
.ELSE
.dw $9416
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $a846
.db $ef
.ELSE
.dw $a846
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $bc6d
.db $ef
.ELSE
.dw $bc6d
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $bc83
.db $ef
.ELSE
.dw $bc83
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $bc9d
.db $ef
.ELSE
.dw $bc9d
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $d0cf
.db $ef
.ELSE
.dw $d0cf
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $e50a
.db $ef
.ELSE
.dw $e50a
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $f934
.db $ef
.ELSE
.dw $f934
.db $5f
.ENDIF
.IFDEF HIROMBUILD
.dw $140a
.db $f0
.ELSE
.dw $940a
.db $60
.ENDIF
.IFDEF HIROMBUILD
.dw $2851
.db $f0
.ELSE
.dw $a851
.db $60
.ENDIF
.IFDEF HIROMBUILD
.dw $3ca2
.db $f0
.ELSE
.dw $bca2
.db $60
.ENDIF
.IFDEF HIROMBUILD
.dw $50ec
.db $f0
.ELSE
.dw $d0ec
.db $60
.ENDIF
.IFDEF HIROMBUILD
.dw $654b
.db $f0
.ELSE
.dw $e54b
.db $60
.ENDIF
.IFDEF HIROMBUILD
.dw $79ab
.db $f0
.ELSE
.dw $f9ab
.db $60
.ENDIF
.IFDEF HIROMBUILD
.dw $9431
.db $f0
.ELSE
.dw $9431
.db $61
.ENDIF
.IFDEF HIROMBUILD
.dw $a87c
.db $f0
.ELSE
.dw $a87c
.db $61
.ENDIF
.IFDEF HIROMBUILD
.dw $bcb2
.db $f0
.ELSE
.dw $bcb2
.db $61
.ENDIF
.IFDEF HIROMBUILD
.dw $d10e
.db $f0
.ELSE
.dw $d10e
.db $61
.ENDIF
.IFDEF HIROMBUILD
.dw $e4d7
.db $f0
.ELSE
.dw $e4d7
.db $61
.ENDIF
.IFDEF HIROMBUILD
.dw $f89d
.db $f0
.ELSE
.dw $f89d
.db $61
.ENDIF
.IFDEF HIROMBUILD
.dw $13b9
.db $f1
.ELSE
.dw $93b9
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $27a4
.db $f1
.ELSE
.dw $a7a4
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $27be
.db $f1
.ELSE
.dw $a7be
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $27dc
.db $f1
.ELSE
.dw $a7dc
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $27f6
.db $f1
.ELSE
.dw $a7f6
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $3982
.db $f1
.ELSE
.dw $b982
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $39a4
.db $f1
.ELSE
.dw $b9a4
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $39be
.db $f1
.ELSE
.dw $b9be
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $4b66
.db $f1
.ELSE
.dw $cb66
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $4b80
.db $f1
.ELSE
.dw $cb80
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5d31
.db $f1
.ELSE
.dw $dd31
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5d4b
.db $f1
.ELSE
.dw $dd4b
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5d65
.db $f1
.ELSE
.dw $dd65
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5d7f
.db $f1
.ELSE
.dw $dd7f
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5d99
.db $f1
.ELSE
.dw $dd99
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5db3
.db $f1
.ELSE
.dw $ddb3
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5dcd
.db $f1
.ELSE
.dw $ddcd
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5de7
.db $f1
.ELSE
.dw $dde7
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5e01
.db $f1
.ELSE
.dw $de01
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5e1b
.db $f1
.ELSE
.dw $de1b
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5e35
.db $f1
.ELSE
.dw $de35
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5e4f
.db $f1
.ELSE
.dw $de4f
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5e69
.db $f1
.ELSE
.dw $de69
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $5e83
.db $f1
.ELSE
.dw $de83
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $7039
.db $f1
.ELSE
.dw $f039
.db $62
.ENDIF
.IFDEF HIROMBUILD
.dw $98cf
.db $f1
.ELSE
.dw $98cf
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $98e5
.db $f1
.ELSE
.dw $98e5
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $98ff
.db $f1
.ELSE
.dw $98ff
.db $63
.ENDIF
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.IFDEF HIROMBUILD
.dw $a488
.db $f1
.ELSE
.dw $a488
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $af96
.db $f1
.ELSE
.dw $af96
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $bb71
.db $f1
.ELSE
.dw $bb71
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $c712
.db $f1
.ELSE
.dw $c712
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $d2ef
.db $f1
.ELSE
.dw $d2ef
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $de93
.db $f1
.ELSE
.dw $de93
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $e8f7
.db $f1
.ELSE
.dw $e8f7
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $f3d5
.db $f1
.ELSE
.dw $f3d5
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $ff40
.db $f1
.ELSE
.dw $ff40
.db $63
.ENDIF
.IFDEF HIROMBUILD
.dw $09f3
.db $f2
.ELSE
.dw $89f3
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $13a0
.db $f2
.ELSE
.dw $93a0
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $1ddb
.db $f2
.ELSE
.dw $9ddb
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $27e8
.db $f2
.ELSE
.dw $a7e8
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $3249
.db $f2
.ELSE
.dw $b249
.db $64
.ENDIF
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.dw 0
.db 0
.IFDEF HIROMBUILD
.dw $3cec
.db $f2
.ELSE
.dw $bcec
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $482a
.db $f2
.ELSE
.dw $c82a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $565c
.db $f2
.ELSE
.dw $d65c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5676
.db $f2
.ELSE
.dw $d676
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5690
.db $f2
.ELSE
.dw $d690
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $56aa
.db $f2
.ELSE
.dw $d6aa
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $56c4
.db $f2
.ELSE
.dw $d6c4
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $56de
.db $f2
.ELSE
.dw $d6de
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $56f8
.db $f2
.ELSE
.dw $d6f8
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5712
.db $f2
.ELSE
.dw $d712
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $572c
.db $f2
.ELSE
.dw $d72c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5746
.db $f2
.ELSE
.dw $d746
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5760
.db $f2
.ELSE
.dw $d760
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $577a
.db $f2
.ELSE
.dw $d77a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5794
.db $f2
.ELSE
.dw $d794
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $57ae
.db $f2
.ELSE
.dw $d7ae
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $57c8
.db $f2
.ELSE
.dw $d7c8
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $57e2
.db $f2
.ELSE
.dw $d7e2
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $57fc
.db $f2
.ELSE
.dw $d7fc
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5816
.db $f2
.ELSE
.dw $d816
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5830
.db $f2
.ELSE
.dw $d830
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $584a
.db $f2
.ELSE
.dw $d84a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5864
.db $f2
.ELSE
.dw $d864
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $587e
.db $f2
.ELSE
.dw $d87e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5898
.db $f2
.ELSE
.dw $d898
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $58b2
.db $f2
.ELSE
.dw $d8b2
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $58cc
.db $f2
.ELSE
.dw $d8cc
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $58e6
.db $f2
.ELSE
.dw $d8e6
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5900
.db $f2
.ELSE
.dw $d900
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $591a
.db $f2
.ELSE
.dw $d91a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5934
.db $f2
.ELSE
.dw $d934
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $594e
.db $f2
.ELSE
.dw $d94e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5968
.db $f2
.ELSE
.dw $d968
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5982
.db $f2
.ELSE
.dw $d982
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $599c
.db $f2
.ELSE
.dw $d99c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $59b6
.db $f2
.ELSE
.dw $d9b6
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $59d0
.db $f2
.ELSE
.dw $d9d0
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $59ea
.db $f2
.ELSE
.dw $d9ea
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5a04
.db $f2
.ELSE
.dw $da04
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5a1e
.db $f2
.ELSE
.dw $da1e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5a38
.db $f2
.ELSE
.dw $da38
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5a52
.db $f2
.ELSE
.dw $da52
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5a6c
.db $f2
.ELSE
.dw $da6c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5a86
.db $f2
.ELSE
.dw $da86
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5aa0
.db $f2
.ELSE
.dw $daa0
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5aba
.db $f2
.ELSE
.dw $daba
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5ad4
.db $f2
.ELSE
.dw $dad4
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5aee
.db $f2
.ELSE
.dw $daee
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5b08
.db $f2
.ELSE
.dw $db08
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5b22
.db $f2
.ELSE
.dw $db22
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5b3c
.db $f2
.ELSE
.dw $db3c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5b56
.db $f2
.ELSE
.dw $db56
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5b70
.db $f2
.ELSE
.dw $db70
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5b8a
.db $f2
.ELSE
.dw $db8a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5ba4
.db $f2
.ELSE
.dw $dba4
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5bbe
.db $f2
.ELSE
.dw $dbbe
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5bd8
.db $f2
.ELSE
.dw $dbd8
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5bf2
.db $f2
.ELSE
.dw $dbf2
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5c0c
.db $f2
.ELSE
.dw $dc0c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5c26
.db $f2
.ELSE
.dw $dc26
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5c40
.db $f2
.ELSE
.dw $dc40
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5c5a
.db $f2
.ELSE
.dw $dc5a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5c74
.db $f2
.ELSE
.dw $dc74
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5c8e
.db $f2
.ELSE
.dw $dc8e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5ca8
.db $f2
.ELSE
.dw $dca8
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5cc2
.db $f2
.ELSE
.dw $dcc2
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5cdc
.db $f2
.ELSE
.dw $dcdc
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5cf6
.db $f2
.ELSE
.dw $dcf6
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d10
.db $f2
.ELSE
.dw $dd10
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d2a
.db $f2
.ELSE
.dw $dd2a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d44
.db $f2
.ELSE
.dw $dd44
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d5e
.db $f2
.ELSE
.dw $dd5e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d78
.db $f2
.ELSE
.dw $dd78
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d92
.db $f2
.ELSE
.dw $dd92
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5dac
.db $f2
.ELSE
.dw $ddac
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5dc6
.db $f2
.ELSE
.dw $ddc6
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5de0
.db $f2
.ELSE
.dw $dde0
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5dfa
.db $f2
.ELSE
.dw $ddfa
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e14
.db $f2
.ELSE
.dw $de14
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e2e
.db $f2
.ELSE
.dw $de2e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e48
.db $f2
.ELSE
.dw $de48
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e62
.db $f2
.ELSE
.dw $de62
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e7c
.db $f2
.ELSE
.dw $de7c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e96
.db $f2
.ELSE
.dw $de96
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5eb0
.db $f2
.ELSE
.dw $deb0
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5eca
.db $f2
.ELSE
.dw $deca
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5ee4
.db $f2
.ELSE
.dw $dee4
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5efe
.db $f2
.ELSE
.dw $defe
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f18
.db $f2
.ELSE
.dw $df18
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f32
.db $f2
.ELSE
.dw $df32
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f4c
.db $f2
.ELSE
.dw $df4c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f66
.db $f2
.ELSE
.dw $df66
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f80
.db $f2
.ELSE
.dw $df80
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f9a
.db $f2
.ELSE
.dw $df9a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5fb4
.db $f2
.ELSE
.dw $dfb4
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5fce
.db $f2
.ELSE
.dw $dfce
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5fe8
.db $f2
.ELSE
.dw $dfe8
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5cdc
.db $f2
.ELSE
.dw $dcdc
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5cf6
.db $f2
.ELSE
.dw $dcf6
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d10
.db $f2
.ELSE
.dw $dd10
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d2a
.db $f2
.ELSE
.dw $dd2a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d44
.db $f2
.ELSE
.dw $dd44
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d5e
.db $f2
.ELSE
.dw $dd5e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d78
.db $f2
.ELSE
.dw $dd78
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5d92
.db $f2
.ELSE
.dw $dd92
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5dac
.db $f2
.ELSE
.dw $ddac
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5dc6
.db $f2
.ELSE
.dw $ddc6
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5de0
.db $f2
.ELSE
.dw $dde0
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5dfa
.db $f2
.ELSE
.dw $ddfa
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e14
.db $f2
.ELSE
.dw $de14
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e2e
.db $f2
.ELSE
.dw $de2e
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e48
.db $f2
.ELSE
.dw $de48
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e62
.db $f2
.ELSE
.dw $de62
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e7c
.db $f2
.ELSE
.dw $de7c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5e96
.db $f2
.ELSE
.dw $de96
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5eb0
.db $f2
.ELSE
.dw $deb0
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5eca
.db $f2
.ELSE
.dw $deca
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5ee4
.db $f2
.ELSE
.dw $dee4
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5efe
.db $f2
.ELSE
.dw $defe
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f18
.db $f2
.ELSE
.dw $df18
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f32
.db $f2
.ELSE
.dw $df32
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f4c
.db $f2
.ELSE
.dw $df4c
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f66
.db $f2
.ELSE
.dw $df66
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f80
.db $f2
.ELSE
.dw $df80
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5f9a
.db $f2
.ELSE
.dw $df9a
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5fb4
.db $f2
.ELSE
.dw $dfb4
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5fce
.db $f2
.ELSE
.dw $dfce
.db $64
.ENDIF
.IFDEF HIROMBUILD
.dw $5fe8
.db $f2
.ELSE
.dw $dfe8
.db $64
.ENDIF
