.DEFINE CONTROL_PROFILE_COUNT 400
ControlProfilePointers:
.IFDEF HIROMBUILD
.dw $0000
.db $c4
.ELSE
.dw $8000
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $0a78
.db $c4
.ELSE
.dw $8a78
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $14f0
.db $c4
.ELSE
.dw $94f0
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $1f68
.db $c4
.ELSE
.dw $9f68
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $29e0
.db $c4
.ELSE
.dw $a9e0
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $3458
.db $c4
.ELSE
.dw $b458
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $3ed0
.db $c4
.ELSE
.dw $bed0
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $4948
.db $c4
.ELSE
.dw $c948
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $53c0
.db $c4
.ELSE
.dw $d3c0
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $5e38
.db $c4
.ELSE
.dw $de38
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $68b0
.db $c4
.ELSE
.dw $e8b0
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $7328
.db $c4
.ELSE
.dw $f328
.db $08
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $c4
.ELSE
.dw $8000
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $8a78
.db $c4
.ELSE
.dw $8a78
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $94f0
.db $c4
.ELSE
.dw $94f0
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $9f68
.db $c4
.ELSE
.dw $9f68
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $a9e0
.db $c4
.ELSE
.dw $a9e0
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $b458
.db $c4
.ELSE
.dw $b458
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $bed0
.db $c4
.ELSE
.dw $bed0
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $d7f0
.db $c4
.ELSE
.dw $d7f0
.db $09
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $c5
.ELSE
.dw $8000
.db $0a
.ENDIF
.IFDEF HIROMBUILD
.dw $1948
.db $c5
.ELSE
.dw $9948
.db $0a
.ENDIF
.IFDEF HIROMBUILD
.dw $3290
.db $c5
.ELSE
.dw $b290
.db $0a
.ENDIF
.IFDEF HIROMBUILD
.dw $4bd8
.db $c5
.ELSE
.dw $cbd8
.db $0a
.ENDIF
.IFDEF HIROMBUILD
.dw $6520
.db $c5
.ELSE
.dw $e520
.db $0a
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $c5
.ELSE
.dw $8000
.db $0b
.ENDIF
.IFDEF HIROMBUILD
.dw $9948
.db $c5
.ELSE
.dw $9948
.db $0b
.ENDIF
.IFDEF HIROMBUILD
.dw $aa64
.db $c5
.ELSE
.dw $aa64
.db $0b
.ENDIF
.IFDEF HIROMBUILD
.dw $bb80
.db $c5
.ELSE
.dw $bb80
.db $0b
.ENDIF
.IFDEF HIROMBUILD
.dw $cc9c
.db $c5
.ELSE
.dw $cc9c
.db $0b
.ENDIF
.IFDEF HIROMBUILD
.dw $ddb8
.db $c5
.ELSE
.dw $ddb8
.db $0b
.ENDIF
.IFDEF HIROMBUILD
.dw $ede4
.db $c5
.ELSE
.dw $ede4
.db $0b
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $c6
.ELSE
.dw $8000
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $102c
.db $c6
.ELSE
.dw $902c
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $2058
.db $c6
.ELSE
.dw $a058
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $3084
.db $c6
.ELSE
.dw $b084
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $40b0
.db $c6
.ELSE
.dw $c0b0
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $42b2
.db $c6
.ELSE
.dw $c2b2
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $52de
.db $c6
.ELSE
.dw $d2de
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $54e8
.db $c6
.ELSE
.dw $d4e8
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $56f2
.db $c6
.ELSE
.dw $d6f2
.db $0c
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $c6
.ELSE
.dw $8000
.db $0d
.ENDIF
.IFDEF HIROMBUILD
.dw $9878
.db $c6
.ELSE
.dw $9878
.db $0d
.ENDIF
.IFDEF HIROMBUILD
.dw $9a82
.db $c6
.ELSE
.dw $9a82
.db $0d
.ENDIF
.IFDEF HIROMBUILD
.dw $b2fa
.db $c6
.ELSE
.dw $b2fa
.db $0d
.ENDIF
.IFDEF HIROMBUILD
.dw $cb72
.db $c6
.ELSE
.dw $cb72
.db $0d
.ENDIF
.IFDEF HIROMBUILD
.dw $e3ea
.db $c6
.ELSE
.dw $e3ea
.db $0d
.ENDIF
.IFDEF HIROMBUILD
.dw $e5f4
.db $c6
.ELSE
.dw $e5f4
.db $0d
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $c7
.ELSE
.dw $8000
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $1878
.db $c7
.ELSE
.dw $9878
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $1a82
.db $c7
.ELSE
.dw $9a82
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $1cac
.db $c7
.ELSE
.dw $9cac
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $1ed6
.db $c7
.ELSE
.dw $9ed6
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $2100
.db $c7
.ELSE
.dw $a100
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $232a
.db $c7
.ELSE
.dw $a32a
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $2554
.db $c7
.ELSE
.dw $a554
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $277e
.db $c7
.ELSE
.dw $a77e
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $29a8
.db $c7
.ELSE
.dw $a9a8
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $3d34
.db $c7
.ELSE
.dw $bd34
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $42ca
.db $c7
.ELSE
.dw $c2ca
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $565a
.db $c7
.ELSE
.dw $d65a
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $69e6
.db $c7
.ELSE
.dw $e9e6
.db $0e
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $c7
.ELSE
.dw $8000
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $93dc
.db $c7
.ELSE
.dw $93dc
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $a790
.db $c7
.ELSE
.dw $a790
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $a9b2
.db $c7
.ELSE
.dw $a9b2
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $abd4
.db $c7
.ELSE
.dw $abd4
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $adf6
.db $c7
.ELSE
.dw $adf6
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $b018
.db $c7
.ELSE
.dw $b018
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $b23a
.db $c7
.ELSE
.dw $b23a
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $b45c
.db $c7
.ELSE
.dw $b45c
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $b67e
.db $c7
.ELSE
.dw $b67e
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $b8a0
.db $c7
.ELSE
.dw $b8a0
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $cae8
.db $c7
.ELSE
.dw $cae8
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $dd30
.db $c7
.ELSE
.dw $dd30
.db $0f
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $c8
.ELSE
.dw $8000
.db $10
.ENDIF
.IFDEF HIROMBUILD
.dw $1248
.db $c8
.ELSE
.dw $9248
.db $10
.ENDIF
.IFDEF HIROMBUILD
.dw $2490
.db $c8
.ELSE
.dw $a490
.db $10
.ENDIF
.IFDEF HIROMBUILD
.dw $36d8
.db $c8
.ELSE
.dw $b6d8
.db $10
.ENDIF
.IFDEF HIROMBUILD
.dw $4920
.db $c8
.ELSE
.dw $c920
.db $10
.ENDIF
.IFDEF HIROMBUILD
.dw $5b68
.db $c8
.ELSE
.dw $db68
.db $10
.ENDIF
.IFDEF HIROMBUILD
.dw $6db0
.db $c8
.ELSE
.dw $edb0
.db $10
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $c8
.ELSE
.dw $8000
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $8226
.db $c8
.ELSE
.dw $8226
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $946e
.db $c8
.ELSE
.dw $946e
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $a6b6
.db $c8
.ELSE
.dw $a6b6
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $b0be
.db $c8
.ELSE
.dw $b0be
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $bac6
.db $c8
.ELSE
.dw $bac6
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $c4ce
.db $c8
.ELSE
.dw $c4ce
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $ced6
.db $c8
.ELSE
.dw $ced6
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $d8de
.db $c8
.ELSE
.dw $d8de
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $e2e6
.db $c8
.ELSE
.dw $e2e6
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $ecee
.db $c8
.ELSE
.dw $ecee
.db $11
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $c9
.ELSE
.dw $8000
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $0a08
.db $c9
.ELSE
.dw $8a08
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $1410
.db $c9
.ELSE
.dw $9410
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $1e18
.db $c9
.ELSE
.dw $9e18
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $2820
.db $c9
.ELSE
.dw $a820
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $3228
.db $c9
.ELSE
.dw $b228
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $3c30
.db $c9
.ELSE
.dw $bc30
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $4638
.db $c9
.ELSE
.dw $c638
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $5368
.db $c9
.ELSE
.dw $d368
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $6098
.db $c9
.ELSE
.dw $e098
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $6dc8
.db $c9
.ELSE
.dw $edc8
.db $12
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $c9
.ELSE
.dw $8000
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $8d30
.db $c9
.ELSE
.dw $8d30
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $9a60
.db $c9
.ELSE
.dw $9a60
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $a790
.db $c9
.ELSE
.dw $a790
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $b4c0
.db $c9
.ELSE
.dw $b4c0
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $bbb2
.db $c9
.ELSE
.dw $bbb2
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $c2a4
.db $c9
.ELSE
.dw $c2a4
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $c996
.db $c9
.ELSE
.dw $c996
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $d088
.db $c9
.ELSE
.dw $d088
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $d77a
.db $c9
.ELSE
.dw $d77a
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $de6c
.db $c9
.ELSE
.dw $de6c
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $e55e
.db $c9
.ELSE
.dw $e55e
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $ec50
.db $c9
.ELSE
.dw $ec50
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $f342
.db $c9
.ELSE
.dw $f342
.db $13
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $ca
.ELSE
.dw $8000
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $06f2
.db $ca
.ELSE
.dw $86f2
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $0de4
.db $ca
.ELSE
.dw $8de4
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $14d6
.db $ca
.ELSE
.dw $94d6
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $1bc8
.db $ca
.ELSE
.dw $9bc8
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $22ba
.db $ca
.ELSE
.dw $a2ba
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $29ac
.db $ca
.ELSE
.dw $a9ac
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $309e
.db $ca
.ELSE
.dw $b09e
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $3790
.db $ca
.ELSE
.dw $b790
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $3e82
.db $ca
.ELSE
.dw $be82
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $4574
.db $ca
.ELSE
.dw $c574
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $4c66
.db $ca
.ELSE
.dw $cc66
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $5358
.db $ca
.ELSE
.dw $d358
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $5a4a
.db $ca
.ELSE
.dw $da4a
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $613c
.db $ca
.ELSE
.dw $e13c
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $682e
.db $ca
.ELSE
.dw $e82e
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $6f20
.db $ca
.ELSE
.dw $ef20
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $7612
.db $ca
.ELSE
.dw $f612
.db $14
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $ca
.ELSE
.dw $8000
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $86f2
.db $ca
.ELSE
.dw $86f2
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $8de4
.db $ca
.ELSE
.dw $8de4
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $94d6
.db $ca
.ELSE
.dw $94d6
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $9bc8
.db $ca
.ELSE
.dw $9bc8
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $a2ba
.db $ca
.ELSE
.dw $a2ba
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $a9ac
.db $ca
.ELSE
.dw $a9ac
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $b09e
.db $ca
.ELSE
.dw $b09e
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $b790
.db $ca
.ELSE
.dw $b790
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $be82
.db $ca
.ELSE
.dw $be82
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $c574
.db $ca
.ELSE
.dw $c574
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $d2a4
.db $ca
.ELSE
.dw $d2a4
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $dfd4
.db $ca
.ELSE
.dw $dfd4
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $e6c6
.db $ca
.ELSE
.dw $e6c6
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $edb8
.db $ca
.ELSE
.dw $edb8
.db $15
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $cb
.ELSE
.dw $8000
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $0d30
.db $cb
.ELSE
.dw $8d30
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $1a60
.db $cb
.ELSE
.dw $9a60
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $2790
.db $cb
.ELSE
.dw $a790
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $2e82
.db $cb
.ELSE
.dw $ae82
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $3574
.db $cb
.ELSE
.dw $b574
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $3c66
.db $cb
.ELSE
.dw $bc66
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $4358
.db $cb
.ELSE
.dw $c358
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $4a4a
.db $cb
.ELSE
.dw $ca4a
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $513c
.db $cb
.ELSE
.dw $d13c
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $582e
.db $cb
.ELSE
.dw $d82e
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $5f20
.db $cb
.ELSE
.dw $df20
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $6612
.db $cb
.ELSE
.dw $e612
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $6d04
.db $cb
.ELSE
.dw $ed04
.db $16
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $cb
.ELSE
.dw $8000
.db $17
.ENDIF
.IFDEF HIROMBUILD
.dw $90c4
.db $cb
.ELSE
.dw $90c4
.db $17
.ENDIF
.IFDEF HIROMBUILD
.dw $a188
.db $cb
.ELSE
.dw $a188
.db $17
.ENDIF
.IFDEF HIROMBUILD
.dw $b24c
.db $cb
.ELSE
.dw $b24c
.db $17
.ENDIF
.IFDEF HIROMBUILD
.dw $c310
.db $cb
.ELSE
.dw $c310
.db $17
.ENDIF
.IFDEF HIROMBUILD
.dw $d3d4
.db $cb
.ELSE
.dw $d3d4
.db $17
.ENDIF
.IFDEF HIROMBUILD
.dw $e498
.db $cb
.ELSE
.dw $e498
.db $17
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $cc
.ELSE
.dw $8000
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $10c4
.db $cc
.ELSE
.dw $90c4
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $2188
.db $cc
.ELSE
.dw $a188
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $324c
.db $cc
.ELSE
.dw $b24c
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $4310
.db $cc
.ELSE
.dw $c310
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $53d4
.db $cc
.ELSE
.dw $d3d4
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $6498
.db $cc
.ELSE
.dw $e498
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $6f84
.db $cc
.ELSE
.dw $ef84
.db $18
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $cc
.ELSE
.dw $8000
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $8aec
.db $cc
.ELSE
.dw $8aec
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $95d8
.db $cc
.ELSE
.dw $95d8
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $a0c4
.db $cc
.ELSE
.dw $a0c4
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $abb0
.db $cc
.ELSE
.dw $abb0
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $b69c
.db $cc
.ELSE
.dw $b69c
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $c188
.db $cc
.ELSE
.dw $c188
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $cc74
.db $cc
.ELSE
.dw $cc74
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $d760
.db $cc
.ELSE
.dw $d760
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $e24c
.db $cc
.ELSE
.dw $e24c
.db $19
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $cd
.ELSE
.dw $8000
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $1920
.db $cd
.ELSE
.dw $9920
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $2650
.db $cd
.ELSE
.dw $a650
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $3380
.db $cd
.ELSE
.dw $b380
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $3e24
.db $cd
.ELSE
.dw $be24
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $48c8
.db $cd
.ELSE
.dw $c8c8
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $536c
.db $cd
.ELSE
.dw $d36c
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $5e10
.db $cd
.ELSE
.dw $de10
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $68b4
.db $cd
.ELSE
.dw $e8b4
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $7358
.db $cd
.ELSE
.dw $f358
.db $1a
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $cd
.ELSE
.dw $8000
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $8aa4
.db $cd
.ELSE
.dw $8aa4
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $9548
.db $cd
.ELSE
.dw $9548
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $9fec
.db $cd
.ELSE
.dw $9fec
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $aa90
.db $cd
.ELSE
.dw $aa90
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $b534
.db $cd
.ELSE
.dw $b534
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $bfd8
.db $cd
.ELSE
.dw $bfd8
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $ca7c
.db $cd
.ELSE
.dw $ca7c
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $d520
.db $cd
.ELSE
.dw $d520
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $dfc4
.db $cd
.ELSE
.dw $dfc4
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $ea68
.db $cd
.ELSE
.dw $ea68
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $f50c
.db $cd
.ELSE
.dw $f50c
.db $1b
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $ce
.ELSE
.dw $8000
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $0aa4
.db $ce
.ELSE
.dw $8aa4
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $1548
.db $ce
.ELSE
.dw $9548
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $1fec
.db $ce
.ELSE
.dw $9fec
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $2a90
.db $ce
.ELSE
.dw $aa90
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $3534
.db $ce
.ELSE
.dw $b534
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $3fd8
.db $ce
.ELSE
.dw $bfd8
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $48ea
.db $ce
.ELSE
.dw $c8ea
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $51fc
.db $ce
.ELSE
.dw $d1fc
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $5e34
.db $ce
.ELSE
.dw $de34
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $6a6c
.db $ce
.ELSE
.dw $ea6c
.db $1c
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $ce
.ELSE
.dw $8000
.db $1d
.ENDIF
.IFDEF HIROMBUILD
.dw $8c38
.db $ce
.ELSE
.dw $8c38
.db $1d
.ENDIF
.IFDEF HIROMBUILD
.dw $954a
.db $ce
.ELSE
.dw $954a
.db $1d
.ENDIF
.IFDEF HIROMBUILD
.dw $add6
.db $ce
.ELSE
.dw $add6
.db $1d
.ENDIF
.IFDEF HIROMBUILD
.dw $c662
.db $ce
.ELSE
.dw $c662
.db $1d
.ENDIF
.IFDEF HIROMBUILD
.dw $deee
.db $ce
.ELSE
.dw $deee
.db $1d
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $cf
.ELSE
.dw $8000
.db $1e
.ENDIF
.IFDEF HIROMBUILD
.dw $188c
.db $cf
.ELSE
.dw $988c
.db $1e
.ENDIF
.IFDEF HIROMBUILD
.dw $3118
.db $cf
.ELSE
.dw $b118
.db $1e
.ENDIF
.IFDEF HIROMBUILD
.dw $49a4
.db $cf
.ELSE
.dw $c9a4
.db $1e
.ENDIF
.IFDEF HIROMBUILD
.dw $6230
.db $cf
.ELSE
.dw $e230
.db $1e
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $cf
.ELSE
.dw $8000
.db $1f
.ENDIF
.IFDEF HIROMBUILD
.dw $988c
.db $cf
.ELSE
.dw $988c
.db $1f
.ENDIF
.IFDEF HIROMBUILD
.dw $b118
.db $cf
.ELSE
.dw $b118
.db $1f
.ENDIF
.IFDEF HIROMBUILD
.dw $c9a4
.db $cf
.ELSE
.dw $c9a4
.db $1f
.ENDIF
.IFDEF HIROMBUILD
.dw $e230
.db $cf
.ELSE
.dw $e230
.db $1f
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $d0
.ELSE
.dw $8000
.db $20
.ENDIF
.IFDEF HIROMBUILD
.dw $188c
.db $d0
.ELSE
.dw $988c
.db $20
.ENDIF
.IFDEF HIROMBUILD
.dw $3118
.db $d0
.ELSE
.dw $b118
.db $20
.ENDIF
.IFDEF HIROMBUILD
.dw $49a4
.db $d0
.ELSE
.dw $c9a4
.db $20
.ENDIF
.IFDEF HIROMBUILD
.dw $6230
.db $d0
.ELSE
.dw $e230
.db $20
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $d0
.ELSE
.dw $8000
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $988c
.db $d0
.ELSE
.dw $988c
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $ba24
.db $d0
.ELSE
.dw $ba24
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $d36c
.db $d0
.ELSE
.dw $d36c
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $d57a
.db $d0
.ELSE
.dw $d57a
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $df32
.db $d0
.ELSE
.dw $df32
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $e8ea
.db $d0
.ELSE
.dw $e8ea
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $f2a2
.db $d0
.ELSE
.dw $f2a2
.db $21
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $d1
.ELSE
.dw $8000
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $09b8
.db $d1
.ELSE
.dw $89b8
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $1448
.db $d1
.ELSE
.dw $9448
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $189a
.db $d1
.ELSE
.dw $989a
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $232a
.db $d1
.ELSE
.dw $a32a
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $2dba
.db $d1
.ELSE
.dw $adba
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $384a
.db $d1
.ELSE
.dw $b84a
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $42da
.db $d1
.ELSE
.dw $c2da
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $4d6a
.db $d1
.ELSE
.dw $cd6a
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $57fa
.db $d1
.ELSE
.dw $d7fa
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $628a
.db $d1
.ELSE
.dw $e28a
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $7086
.db $d1
.ELSE
.dw $f086
.db $22
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $d1
.ELSE
.dw $8000
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $8dfc
.db $d1
.ELSE
.dw $8dfc
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $9bf8
.db $d1
.ELSE
.dw $9bf8
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $a9f4
.db $d1
.ELSE
.dw $a9f4
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $ade4
.db $d1
.ELSE
.dw $ade4
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $b1d4
.db $d1
.ELSE
.dw $b1d4
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $b5c4
.db $d1
.ELSE
.dw $b5c4
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $b9b4
.db $d1
.ELSE
.dw $b9b4
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $bda4
.db $d1
.ELSE
.dw $bda4
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $c80c
.db $d1
.ELSE
.dw $c80c
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $ca06
.db $d1
.ELSE
.dw $ca06
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $e276
.db $d1
.ELSE
.dw $e276
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $fae6
.db $d1
.ELSE
.dw $fae6
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $fd08
.db $d1
.ELSE
.dw $fd08
.db $23
.ENDIF
.IFDEF HIROMBUILD
.dw $0000
.db $d2
.ELSE
.dw $8000
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $0222
.db $d2
.ELSE
.dw $8222
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $0444
.db $d2
.ELSE
.dw $8444
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $0666
.db $d2
.ELSE
.dw $8666
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $0888
.db $d2
.ELSE
.dw $8888
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $0aaa
.db $d2
.ELSE
.dw $8aaa
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $0ccc
.db $d2
.ELSE
.dw $8ccc
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $0eee
.db $d2
.ELSE
.dw $8eee
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1110
.db $d2
.ELSE
.dw $9110
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1332
.db $d2
.ELSE
.dw $9332
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1554
.db $d2
.ELSE
.dw $9554
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1776
.db $d2
.ELSE
.dw $9776
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1998
.db $d2
.ELSE
.dw $9998
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1bba
.db $d2
.ELSE
.dw $9bba
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1ddc
.db $d2
.ELSE
.dw $9ddc
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $1ffe
.db $d2
.ELSE
.dw $9ffe
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $2220
.db $d2
.ELSE
.dw $a220
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $2442
.db $d2
.ELSE
.dw $a442
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $2664
.db $d2
.ELSE
.dw $a664
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $2886
.db $d2
.ELSE
.dw $a886
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $2aa8
.db $d2
.ELSE
.dw $aaa8
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $2cca
.db $d2
.ELSE
.dw $acca
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $2eec
.db $d2
.ELSE
.dw $aeec
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $310e
.db $d2
.ELSE
.dw $b10e
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $3330
.db $d2
.ELSE
.dw $b330
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $3552
.db $d2
.ELSE
.dw $b552
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $3774
.db $d2
.ELSE
.dw $b774
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $3996
.db $d2
.ELSE
.dw $b996
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $3bb8
.db $d2
.ELSE
.dw $bbb8
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $3dda
.db $d2
.ELSE
.dw $bdda
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $3fd4
.db $d2
.ELSE
.dw $bfd4
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $41ce
.db $d2
.ELSE
.dw $c1ce
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $43c8
.db $d2
.ELSE
.dw $c3c8
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $45c2
.db $d2
.ELSE
.dw $c5c2
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $47bc
.db $d2
.ELSE
.dw $c7bc
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $49b6
.db $d2
.ELSE
.dw $c9b6
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $4bb0
.db $d2
.ELSE
.dw $cbb0
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $4daa
.db $d2
.ELSE
.dw $cdaa
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $4fa4
.db $d2
.ELSE
.dw $cfa4
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $519e
.db $d2
.ELSE
.dw $d19e
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $5398
.db $d2
.ELSE
.dw $d398
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $5592
.db $d2
.ELSE
.dw $d592
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $578c
.db $d2
.ELSE
.dw $d78c
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $5986
.db $d2
.ELSE
.dw $d986
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $5b80
.db $d2
.ELSE
.dw $db80
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $5d7a
.db $d2
.ELSE
.dw $dd7a
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $5f74
.db $d2
.ELSE
.dw $df74
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $616e
.db $d2
.ELSE
.dw $e16e
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $6368
.db $d2
.ELSE
.dw $e368
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $6562
.db $d2
.ELSE
.dw $e562
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $675c
.db $d2
.ELSE
.dw $e75c
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $6956
.db $d2
.ELSE
.dw $e956
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $6b50
.db $d2
.ELSE
.dw $eb50
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $6d4a
.db $d2
.ELSE
.dw $ed4a
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $6f44
.db $d2
.ELSE
.dw $ef44
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $713e
.db $d2
.ELSE
.dw $f13e
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $7338
.db $d2
.ELSE
.dw $f338
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $7532
.db $d2
.ELSE
.dw $f532
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $772c
.db $d2
.ELSE
.dw $f72c
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $7926
.db $d2
.ELSE
.dw $f926
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $7b20
.db $d2
.ELSE
.dw $fb20
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $7d1e
.db $d2
.ELSE
.dw $fd1e
.db $24
.ENDIF
.IFDEF HIROMBUILD
.dw $8000
.db $d2
.ELSE
.dw $8000
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $81fe
.db $d2
.ELSE
.dw $81fe
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $83fc
.db $d2
.ELSE
.dw $83fc
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $85fa
.db $d2
.ELSE
.dw $85fa
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $87f8
.db $d2
.ELSE
.dw $87f8
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $89f6
.db $d2
.ELSE
.dw $89f6
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $8bf4
.db $d2
.ELSE
.dw $8bf4
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $8df2
.db $d2
.ELSE
.dw $8df2
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $8ff0
.db $d2
.ELSE
.dw $8ff0
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $91ee
.db $d2
.ELSE
.dw $91ee
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $93ec
.db $d2
.ELSE
.dw $93ec
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $95ea
.db $d2
.ELSE
.dw $95ea
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $97e8
.db $d2
.ELSE
.dw $97e8
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $99e6
.db $d2
.ELSE
.dw $99e6
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $9be4
.db $d2
.ELSE
.dw $9be4
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $9de2
.db $d2
.ELSE
.dw $9de2
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $9fe0
.db $d2
.ELSE
.dw $9fe0
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $a1de
.db $d2
.ELSE
.dw $a1de
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $a3dc
.db $d2
.ELSE
.dw $a3dc
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $a5da
.db $d2
.ELSE
.dw $a5da
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $a7d8
.db $d2
.ELSE
.dw $a7d8
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $a9d6
.db $d2
.ELSE
.dw $a9d6
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $abd4
.db $d2
.ELSE
.dw $abd4
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $add2
.db $d2
.ELSE
.dw $add2
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $afd0
.db $d2
.ELSE
.dw $afd0
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $b1ce
.db $d2
.ELSE
.dw $b1ce
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $b3cc
.db $d2
.ELSE
.dw $b3cc
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $b5ca
.db $d2
.ELSE
.dw $b5ca
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $b7c8
.db $d2
.ELSE
.dw $b7c8
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $b9c6
.db $d2
.ELSE
.dw $b9c6
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $bbc4
.db $d2
.ELSE
.dw $bbc4
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $bdc2
.db $d2
.ELSE
.dw $bdc2
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $bfc0
.db $d2
.ELSE
.dw $bfc0
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $c1be
.db $d2
.ELSE
.dw $c1be
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $c3bc
.db $d2
.ELSE
.dw $c3bc
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $c5ba
.db $d2
.ELSE
.dw $c5ba
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $c7b8
.db $d2
.ELSE
.dw $c7b8
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $c9b6
.db $d2
.ELSE
.dw $c9b6
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $cbb4
.db $d2
.ELSE
.dw $cbb4
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $cdb2
.db $d2
.ELSE
.dw $cdb2
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $cfb0
.db $d2
.ELSE
.dw $cfb0
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $d1ae
.db $d2
.ELSE
.dw $d1ae
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $d3ac
.db $d2
.ELSE
.dw $d3ac
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $d5aa
.db $d2
.ELSE
.dw $d5aa
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $d7a8
.db $d2
.ELSE
.dw $d7a8
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $d9a6
.db $d2
.ELSE
.dw $d9a6
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $dba4
.db $d2
.ELSE
.dw $dba4
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $dda2
.db $d2
.ELSE
.dw $dda2
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $dfa0
.db $d2
.ELSE
.dw $dfa0
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $e19e
.db $d2
.ELSE
.dw $e19e
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $e39c
.db $d2
.ELSE
.dw $e39c
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $e59a
.db $d2
.ELSE
.dw $e59a
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $e798
.db $d2
.ELSE
.dw $e798
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $e996
.db $d2
.ELSE
.dw $e996
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $eb94
.db $d2
.ELSE
.dw $eb94
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $ed92
.db $d2
.ELSE
.dw $ed92
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $ef90
.db $d2
.ELSE
.dw $ef90
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $f18e
.db $d2
.ELSE
.dw $f18e
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $f38c
.db $d2
.ELSE
.dw $f38c
.db $25
.ENDIF
.IFDEF HIROMBUILD
.dw $f58a
.db $d2
.ELSE
.dw $f58a
.db $25
.ENDIF
