ROMBLOCK 8, $0000
.SECTION "ControlRecord0" FORCE
ControlRecord0:
.incbin "control_record_000.bin"
.ENDS
ROMBLOCK 8, $0a78
.SECTION "ControlRecord1" FORCE
ControlRecord1:
.incbin "control_record_001.bin"
.ENDS
ROMBLOCK 8, $14f0
.SECTION "ControlRecord2" FORCE
ControlRecord2:
.incbin "control_record_002.bin"
.ENDS
ROMBLOCK 8, $1f68
.SECTION "ControlRecord3" FORCE
ControlRecord3:
.incbin "control_record_003.bin"
.ENDS
ROMBLOCK 8, $29e0
.SECTION "ControlRecord4" FORCE
ControlRecord4:
.incbin "control_record_004.bin"
.ENDS
ROMBLOCK 8, $3458
.SECTION "ControlRecord5" FORCE
ControlRecord5:
.incbin "control_record_005.bin"
.ENDS
ROMBLOCK 8, $3ed0
.SECTION "ControlRecord6" FORCE
ControlRecord6:
.incbin "control_record_006.bin"
.ENDS
ROMBLOCK 8, $4948
.SECTION "ControlRecord7" FORCE
ControlRecord7:
.incbin "control_record_007.bin"
.ENDS
ROMBLOCK 8, $53c0
.SECTION "ControlRecord8" FORCE
ControlRecord8:
.incbin "control_record_008.bin"
.ENDS
ROMBLOCK 8, $5e38
.SECTION "ControlRecord9" FORCE
ControlRecord9:
.incbin "control_record_009.bin"
.ENDS
ROMBLOCK 8, $68b0
.SECTION "ControlRecord10" FORCE
ControlRecord10:
.incbin "control_record_010.bin"
.ENDS
ROMBLOCK 8, $7328
.SECTION "ControlRecord11" FORCE
ControlRecord11:
.incbin "control_record_011.bin"
.ENDS
ROMBLOCK 9, $0000
.SECTION "ControlRecord12" FORCE
ControlRecord12:
.incbin "control_record_012.bin"
.ENDS
ROMBLOCK 9, $0a78
.SECTION "ControlRecord13" FORCE
ControlRecord13:
.incbin "control_record_013.bin"
.ENDS
ROMBLOCK 9, $14f0
.SECTION "ControlRecord14" FORCE
ControlRecord14:
.incbin "control_record_014.bin"
.ENDS
ROMBLOCK 9, $1f68
.SECTION "ControlRecord15" FORCE
ControlRecord15:
.incbin "control_record_015.bin"
.ENDS
ROMBLOCK 9, $29e0
.SECTION "ControlRecord16" FORCE
ControlRecord16:
.incbin "control_record_016.bin"
.ENDS
ROMBLOCK 9, $3458
.SECTION "ControlRecord17" FORCE
ControlRecord17:
.incbin "control_record_017.bin"
.ENDS
ROMBLOCK 9, $3ed0
.SECTION "ControlRecord18" FORCE
ControlRecord18:
.incbin "control_record_018.bin"
.ENDS
ROMBLOCK 9, $57f0
.SECTION "ControlRecord19" FORCE
ControlRecord19:
.incbin "control_record_019.bin"
.ENDS
ROMBLOCK 10, $0000
.SECTION "ControlRecord20" FORCE
ControlRecord20:
.incbin "control_record_020.bin"
.ENDS
ROMBLOCK 10, $1948
.SECTION "ControlRecord21" FORCE
ControlRecord21:
.incbin "control_record_021.bin"
.ENDS
ROMBLOCK 10, $3290
.SECTION "ControlRecord22" FORCE
ControlRecord22:
.incbin "control_record_022.bin"
.ENDS
ROMBLOCK 10, $4bd8
.SECTION "ControlRecord23" FORCE
ControlRecord23:
.incbin "control_record_023.bin"
.ENDS
ROMBLOCK 10, $6520
.SECTION "ControlRecord24" FORCE
ControlRecord24:
.incbin "control_record_024.bin"
.ENDS
ROMBLOCK 11, $0000
.SECTION "ControlRecord25" FORCE
ControlRecord25:
.incbin "control_record_025.bin"
.ENDS
ROMBLOCK 11, $1948
.SECTION "ControlRecord26" FORCE
ControlRecord26:
.incbin "control_record_026.bin"
.ENDS
ROMBLOCK 11, $2a64
.SECTION "ControlRecord27" FORCE
ControlRecord27:
.incbin "control_record_027.bin"
.ENDS
ROMBLOCK 11, $3b80
.SECTION "ControlRecord28" FORCE
ControlRecord28:
.incbin "control_record_028.bin"
.ENDS
ROMBLOCK 11, $4c9c
.SECTION "ControlRecord29" FORCE
ControlRecord29:
.incbin "control_record_029.bin"
.ENDS
ROMBLOCK 11, $5db8
.SECTION "ControlRecord30" FORCE
ControlRecord30:
.incbin "control_record_030.bin"
.ENDS
ROMBLOCK 11, $6de4
.SECTION "ControlRecord31" FORCE
ControlRecord31:
.incbin "control_record_031.bin"
.ENDS
ROMBLOCK 12, $0000
.SECTION "ControlRecord32" FORCE
ControlRecord32:
.incbin "control_record_032.bin"
.ENDS
ROMBLOCK 12, $102c
.SECTION "ControlRecord33" FORCE
ControlRecord33:
.incbin "control_record_033.bin"
.ENDS
ROMBLOCK 12, $2058
.SECTION "ControlRecord34" FORCE
ControlRecord34:
.incbin "control_record_034.bin"
.ENDS
ROMBLOCK 12, $3084
.SECTION "ControlRecord35" FORCE
ControlRecord35:
.incbin "control_record_035.bin"
.ENDS
ROMBLOCK 12, $40b0
.SECTION "ControlRecord36" FORCE
ControlRecord36:
.incbin "control_record_036.bin"
.ENDS
ROMBLOCK 12, $42b2
.SECTION "ControlRecord37" FORCE
ControlRecord37:
.incbin "control_record_037.bin"
.ENDS
ROMBLOCK 12, $52de
.SECTION "ControlRecord38" FORCE
ControlRecord38:
.incbin "control_record_038.bin"
.ENDS
ROMBLOCK 12, $54e8
.SECTION "ControlRecord39" FORCE
ControlRecord39:
.incbin "control_record_039.bin"
.ENDS
ROMBLOCK 12, $56f2
.SECTION "ControlRecord40" FORCE
ControlRecord40:
.incbin "control_record_040.bin"
.ENDS
ROMBLOCK 13, $0000
.SECTION "ControlRecord41" FORCE
ControlRecord41:
.incbin "control_record_041.bin"
.ENDS
ROMBLOCK 13, $1878
.SECTION "ControlRecord42" FORCE
ControlRecord42:
.incbin "control_record_042.bin"
.ENDS
ROMBLOCK 13, $1a82
.SECTION "ControlRecord43" FORCE
ControlRecord43:
.incbin "control_record_043.bin"
.ENDS
ROMBLOCK 13, $32fa
.SECTION "ControlRecord44" FORCE
ControlRecord44:
.incbin "control_record_044.bin"
.ENDS
ROMBLOCK 13, $4b72
.SECTION "ControlRecord45" FORCE
ControlRecord45:
.incbin "control_record_045.bin"
.ENDS
ROMBLOCK 13, $63ea
.SECTION "ControlRecord46" FORCE
ControlRecord46:
.incbin "control_record_046.bin"
.ENDS
ROMBLOCK 13, $65f4
.SECTION "ControlRecord47" FORCE
ControlRecord47:
.incbin "control_record_047.bin"
.ENDS
ROMBLOCK 14, $0000
.SECTION "ControlRecord48" FORCE
ControlRecord48:
.incbin "control_record_048.bin"
.ENDS
ROMBLOCK 14, $1878
.SECTION "ControlRecord49" FORCE
ControlRecord49:
.incbin "control_record_049.bin"
.ENDS
ROMBLOCK 14, $1a82
.SECTION "ControlRecord50" FORCE
ControlRecord50:
.incbin "control_record_050.bin"
.ENDS
ROMBLOCK 14, $1cac
.SECTION "ControlRecord51" FORCE
ControlRecord51:
.incbin "control_record_051.bin"
.ENDS
ROMBLOCK 14, $1ed6
.SECTION "ControlRecord52" FORCE
ControlRecord52:
.incbin "control_record_052.bin"
.ENDS
ROMBLOCK 14, $2100
.SECTION "ControlRecord53" FORCE
ControlRecord53:
.incbin "control_record_053.bin"
.ENDS
ROMBLOCK 14, $232a
.SECTION "ControlRecord54" FORCE
ControlRecord54:
.incbin "control_record_054.bin"
.ENDS
ROMBLOCK 14, $2554
.SECTION "ControlRecord55" FORCE
ControlRecord55:
.incbin "control_record_055.bin"
.ENDS
ROMBLOCK 14, $277e
.SECTION "ControlRecord56" FORCE
ControlRecord56:
.incbin "control_record_056.bin"
.ENDS
ROMBLOCK 14, $29a8
.SECTION "ControlRecord57" FORCE
ControlRecord57:
.incbin "control_record_057.bin"
.ENDS
ROMBLOCK 14, $3d34
.SECTION "ControlRecord58" FORCE
ControlRecord58:
.incbin "control_record_058.bin"
.ENDS
ROMBLOCK 14, $42ca
.SECTION "ControlRecord59" FORCE
ControlRecord59:
.incbin "control_record_059.bin"
.ENDS
ROMBLOCK 14, $565a
.SECTION "ControlRecord60" FORCE
ControlRecord60:
.incbin "control_record_060.bin"
.ENDS
ROMBLOCK 14, $69e6
.SECTION "ControlRecord61" FORCE
ControlRecord61:
.incbin "control_record_061.bin"
.ENDS
ROMBLOCK 15, $0000
.SECTION "ControlRecord62" FORCE
ControlRecord62:
.incbin "control_record_062.bin"
.ENDS
ROMBLOCK 15, $13dc
.SECTION "ControlRecord63" FORCE
ControlRecord63:
.incbin "control_record_063.bin"
.ENDS
ROMBLOCK 15, $2790
.SECTION "ControlRecord64" FORCE
ControlRecord64:
.incbin "control_record_064.bin"
.ENDS
ROMBLOCK 15, $29b2
.SECTION "ControlRecord65" FORCE
ControlRecord65:
.incbin "control_record_065.bin"
.ENDS
ROMBLOCK 15, $2bd4
.SECTION "ControlRecord66" FORCE
ControlRecord66:
.incbin "control_record_066.bin"
.ENDS
ROMBLOCK 15, $2df6
.SECTION "ControlRecord67" FORCE
ControlRecord67:
.incbin "control_record_067.bin"
.ENDS
ROMBLOCK 15, $3018
.SECTION "ControlRecord68" FORCE
ControlRecord68:
.incbin "control_record_068.bin"
.ENDS
ROMBLOCK 15, $323a
.SECTION "ControlRecord69" FORCE
ControlRecord69:
.incbin "control_record_069.bin"
.ENDS
ROMBLOCK 15, $345c
.SECTION "ControlRecord70" FORCE
ControlRecord70:
.incbin "control_record_070.bin"
.ENDS
ROMBLOCK 15, $367e
.SECTION "ControlRecord71" FORCE
ControlRecord71:
.incbin "control_record_071.bin"
.ENDS
ROMBLOCK 15, $38a0
.SECTION "ControlRecord72" FORCE
ControlRecord72:
.incbin "control_record_072.bin"
.ENDS
ROMBLOCK 15, $4ae8
.SECTION "ControlRecord73" FORCE
ControlRecord73:
.incbin "control_record_073.bin"
.ENDS
ROMBLOCK 15, $5d30
.SECTION "ControlRecord74" FORCE
ControlRecord74:
.incbin "control_record_074.bin"
.ENDS
ROMBLOCK 16, $0000
.SECTION "ControlRecord75" FORCE
ControlRecord75:
.incbin "control_record_075.bin"
.ENDS
ROMBLOCK 16, $1248
.SECTION "ControlRecord76" FORCE
ControlRecord76:
.incbin "control_record_076.bin"
.ENDS
ROMBLOCK 16, $2490
.SECTION "ControlRecord77" FORCE
ControlRecord77:
.incbin "control_record_077.bin"
.ENDS
ROMBLOCK 16, $36d8
.SECTION "ControlRecord78" FORCE
ControlRecord78:
.incbin "control_record_078.bin"
.ENDS
ROMBLOCK 16, $4920
.SECTION "ControlRecord79" FORCE
ControlRecord79:
.incbin "control_record_079.bin"
.ENDS
ROMBLOCK 16, $5b68
.SECTION "ControlRecord80" FORCE
ControlRecord80:
.incbin "control_record_080.bin"
.ENDS
ROMBLOCK 16, $6db0
.SECTION "ControlRecord81" FORCE
ControlRecord81:
.incbin "control_record_081.bin"
.ENDS
ROMBLOCK 17, $0000
.SECTION "ControlRecord82" FORCE
ControlRecord82:
.incbin "control_record_082.bin"
.ENDS
ROMBLOCK 17, $0226
.SECTION "ControlRecord83" FORCE
ControlRecord83:
.incbin "control_record_083.bin"
.ENDS
ROMBLOCK 17, $146e
.SECTION "ControlRecord84" FORCE
ControlRecord84:
.incbin "control_record_084.bin"
.ENDS
ROMBLOCK 17, $26b6
.SECTION "ControlRecord85" FORCE
ControlRecord85:
.incbin "control_record_085.bin"
.ENDS
ROMBLOCK 17, $30be
.SECTION "ControlRecord86" FORCE
ControlRecord86:
.incbin "control_record_086.bin"
.ENDS
ROMBLOCK 17, $3ac6
.SECTION "ControlRecord87" FORCE
ControlRecord87:
.incbin "control_record_087.bin"
.ENDS
ROMBLOCK 17, $44ce
.SECTION "ControlRecord88" FORCE
ControlRecord88:
.incbin "control_record_088.bin"
.ENDS
ROMBLOCK 17, $4ed6
.SECTION "ControlRecord89" FORCE
ControlRecord89:
.incbin "control_record_089.bin"
.ENDS
ROMBLOCK 17, $58de
.SECTION "ControlRecord90" FORCE
ControlRecord90:
.incbin "control_record_090.bin"
.ENDS
ROMBLOCK 17, $62e6
.SECTION "ControlRecord91" FORCE
ControlRecord91:
.incbin "control_record_091.bin"
.ENDS
ROMBLOCK 17, $6cee
.SECTION "ControlRecord92" FORCE
ControlRecord92:
.incbin "control_record_092.bin"
.ENDS
ROMBLOCK 18, $0000
.SECTION "ControlRecord93" FORCE
ControlRecord93:
.incbin "control_record_093.bin"
.ENDS
ROMBLOCK 18, $0a08
.SECTION "ControlRecord94" FORCE
ControlRecord94:
.incbin "control_record_094.bin"
.ENDS
ROMBLOCK 18, $1410
.SECTION "ControlRecord95" FORCE
ControlRecord95:
.incbin "control_record_095.bin"
.ENDS
ROMBLOCK 18, $1e18
.SECTION "ControlRecord96" FORCE
ControlRecord96:
.incbin "control_record_096.bin"
.ENDS
ROMBLOCK 18, $2820
.SECTION "ControlRecord97" FORCE
ControlRecord97:
.incbin "control_record_097.bin"
.ENDS
ROMBLOCK 18, $3228
.SECTION "ControlRecord98" FORCE
ControlRecord98:
.incbin "control_record_098.bin"
.ENDS
ROMBLOCK 18, $3c30
.SECTION "ControlRecord99" FORCE
ControlRecord99:
.incbin "control_record_099.bin"
.ENDS
ROMBLOCK 18, $4638
.SECTION "ControlRecord100" FORCE
ControlRecord100:
.incbin "control_record_100.bin"
.ENDS
ROMBLOCK 18, $5368
.SECTION "ControlRecord101" FORCE
ControlRecord101:
.incbin "control_record_101.bin"
.ENDS
ROMBLOCK 18, $6098
.SECTION "ControlRecord102" FORCE
ControlRecord102:
.incbin "control_record_102.bin"
.ENDS
ROMBLOCK 18, $6dc8
.SECTION "ControlRecord103" FORCE
ControlRecord103:
.incbin "control_record_103.bin"
.ENDS
ROMBLOCK 19, $0000
.SECTION "ControlRecord104" FORCE
ControlRecord104:
.incbin "control_record_104.bin"
.ENDS
ROMBLOCK 19, $0d30
.SECTION "ControlRecord105" FORCE
ControlRecord105:
.incbin "control_record_105.bin"
.ENDS
ROMBLOCK 19, $1a60
.SECTION "ControlRecord106" FORCE
ControlRecord106:
.incbin "control_record_106.bin"
.ENDS
ROMBLOCK 19, $2790
.SECTION "ControlRecord107" FORCE
ControlRecord107:
.incbin "control_record_107.bin"
.ENDS
ROMBLOCK 19, $34c0
.SECTION "ControlRecord108" FORCE
ControlRecord108:
.incbin "control_record_108.bin"
.ENDS
ROMBLOCK 19, $3bb2
.SECTION "ControlRecord109" FORCE
ControlRecord109:
.incbin "control_record_109.bin"
.ENDS
ROMBLOCK 19, $42a4
.SECTION "ControlRecord110" FORCE
ControlRecord110:
.incbin "control_record_110.bin"
.ENDS
ROMBLOCK 19, $4996
.SECTION "ControlRecord111" FORCE
ControlRecord111:
.incbin "control_record_111.bin"
.ENDS
ROMBLOCK 19, $5088
.SECTION "ControlRecord112" FORCE
ControlRecord112:
.incbin "control_record_112.bin"
.ENDS
ROMBLOCK 19, $577a
.SECTION "ControlRecord113" FORCE
ControlRecord113:
.incbin "control_record_113.bin"
.ENDS
ROMBLOCK 19, $5e6c
.SECTION "ControlRecord114" FORCE
ControlRecord114:
.incbin "control_record_114.bin"
.ENDS
ROMBLOCK 19, $655e
.SECTION "ControlRecord115" FORCE
ControlRecord115:
.incbin "control_record_115.bin"
.ENDS
ROMBLOCK 19, $6c50
.SECTION "ControlRecord116" FORCE
ControlRecord116:
.incbin "control_record_116.bin"
.ENDS
ROMBLOCK 19, $7342
.SECTION "ControlRecord117" FORCE
ControlRecord117:
.incbin "control_record_117.bin"
.ENDS
ROMBLOCK 20, $0000
.SECTION "ControlRecord118" FORCE
ControlRecord118:
.incbin "control_record_118.bin"
.ENDS
ROMBLOCK 20, $06f2
.SECTION "ControlRecord119" FORCE
ControlRecord119:
.incbin "control_record_119.bin"
.ENDS
ROMBLOCK 20, $0de4
.SECTION "ControlRecord120" FORCE
ControlRecord120:
.incbin "control_record_120.bin"
.ENDS
ROMBLOCK 20, $14d6
.SECTION "ControlRecord121" FORCE
ControlRecord121:
.incbin "control_record_121.bin"
.ENDS
ROMBLOCK 20, $1bc8
.SECTION "ControlRecord122" FORCE
ControlRecord122:
.incbin "control_record_122.bin"
.ENDS
ROMBLOCK 20, $22ba
.SECTION "ControlRecord123" FORCE
ControlRecord123:
.incbin "control_record_123.bin"
.ENDS
ROMBLOCK 20, $29ac
.SECTION "ControlRecord124" FORCE
ControlRecord124:
.incbin "control_record_124.bin"
.ENDS
ROMBLOCK 20, $309e
.SECTION "ControlRecord125" FORCE
ControlRecord125:
.incbin "control_record_125.bin"
.ENDS
ROMBLOCK 20, $3790
.SECTION "ControlRecord126" FORCE
ControlRecord126:
.incbin "control_record_126.bin"
.ENDS
ROMBLOCK 20, $3e82
.SECTION "ControlRecord127" FORCE
ControlRecord127:
.incbin "control_record_127.bin"
.ENDS
ROMBLOCK 20, $4574
.SECTION "ControlRecord128" FORCE
ControlRecord128:
.incbin "control_record_128.bin"
.ENDS
ROMBLOCK 20, $4c66
.SECTION "ControlRecord129" FORCE
ControlRecord129:
.incbin "control_record_129.bin"
.ENDS
ROMBLOCK 20, $5358
.SECTION "ControlRecord130" FORCE
ControlRecord130:
.incbin "control_record_130.bin"
.ENDS
ROMBLOCK 20, $5a4a
.SECTION "ControlRecord131" FORCE
ControlRecord131:
.incbin "control_record_131.bin"
.ENDS
ROMBLOCK 20, $613c
.SECTION "ControlRecord132" FORCE
ControlRecord132:
.incbin "control_record_132.bin"
.ENDS
ROMBLOCK 20, $682e
.SECTION "ControlRecord133" FORCE
ControlRecord133:
.incbin "control_record_133.bin"
.ENDS
ROMBLOCK 20, $6f20
.SECTION "ControlRecord134" FORCE
ControlRecord134:
.incbin "control_record_134.bin"
.ENDS
ROMBLOCK 20, $7612
.SECTION "ControlRecord135" FORCE
ControlRecord135:
.incbin "control_record_135.bin"
.ENDS
ROMBLOCK 21, $0000
.SECTION "ControlRecord136" FORCE
ControlRecord136:
.incbin "control_record_136.bin"
.ENDS
ROMBLOCK 21, $06f2
.SECTION "ControlRecord137" FORCE
ControlRecord137:
.incbin "control_record_137.bin"
.ENDS
ROMBLOCK 21, $0de4
.SECTION "ControlRecord138" FORCE
ControlRecord138:
.incbin "control_record_138.bin"
.ENDS
ROMBLOCK 21, $14d6
.SECTION "ControlRecord139" FORCE
ControlRecord139:
.incbin "control_record_139.bin"
.ENDS
ROMBLOCK 21, $1bc8
.SECTION "ControlRecord140" FORCE
ControlRecord140:
.incbin "control_record_140.bin"
.ENDS
ROMBLOCK 21, $22ba
.SECTION "ControlRecord141" FORCE
ControlRecord141:
.incbin "control_record_141.bin"
.ENDS
ROMBLOCK 21, $29ac
.SECTION "ControlRecord142" FORCE
ControlRecord142:
.incbin "control_record_142.bin"
.ENDS
ROMBLOCK 21, $309e
.SECTION "ControlRecord143" FORCE
ControlRecord143:
.incbin "control_record_143.bin"
.ENDS
ROMBLOCK 21, $3790
.SECTION "ControlRecord144" FORCE
ControlRecord144:
.incbin "control_record_144.bin"
.ENDS
ROMBLOCK 21, $3e82
.SECTION "ControlRecord145" FORCE
ControlRecord145:
.incbin "control_record_145.bin"
.ENDS
ROMBLOCK 21, $4574
.SECTION "ControlRecord146" FORCE
ControlRecord146:
.incbin "control_record_146.bin"
.ENDS
ROMBLOCK 21, $52a4
.SECTION "ControlRecord147" FORCE
ControlRecord147:
.incbin "control_record_147.bin"
.ENDS
ROMBLOCK 21, $5fd4
.SECTION "ControlRecord148" FORCE
ControlRecord148:
.incbin "control_record_148.bin"
.ENDS
ROMBLOCK 21, $66c6
.SECTION "ControlRecord149" FORCE
ControlRecord149:
.incbin "control_record_149.bin"
.ENDS
ROMBLOCK 21, $6db8
.SECTION "ControlRecord150" FORCE
ControlRecord150:
.incbin "control_record_150.bin"
.ENDS
ROMBLOCK 22, $0000
.SECTION "ControlRecord151" FORCE
ControlRecord151:
.incbin "control_record_151.bin"
.ENDS
ROMBLOCK 22, $0d30
.SECTION "ControlRecord152" FORCE
ControlRecord152:
.incbin "control_record_152.bin"
.ENDS
ROMBLOCK 22, $1a60
.SECTION "ControlRecord153" FORCE
ControlRecord153:
.incbin "control_record_153.bin"
.ENDS
ROMBLOCK 22, $2790
.SECTION "ControlRecord154" FORCE
ControlRecord154:
.incbin "control_record_154.bin"
.ENDS
ROMBLOCK 22, $2e82
.SECTION "ControlRecord155" FORCE
ControlRecord155:
.incbin "control_record_155.bin"
.ENDS
ROMBLOCK 22, $3574
.SECTION "ControlRecord156" FORCE
ControlRecord156:
.incbin "control_record_156.bin"
.ENDS
ROMBLOCK 22, $3c66
.SECTION "ControlRecord157" FORCE
ControlRecord157:
.incbin "control_record_157.bin"
.ENDS
ROMBLOCK 22, $4358
.SECTION "ControlRecord158" FORCE
ControlRecord158:
.incbin "control_record_158.bin"
.ENDS
ROMBLOCK 22, $4a4a
.SECTION "ControlRecord159" FORCE
ControlRecord159:
.incbin "control_record_159.bin"
.ENDS
ROMBLOCK 22, $513c
.SECTION "ControlRecord160" FORCE
ControlRecord160:
.incbin "control_record_160.bin"
.ENDS
ROMBLOCK 22, $582e
.SECTION "ControlRecord161" FORCE
ControlRecord161:
.incbin "control_record_161.bin"
.ENDS
ROMBLOCK 22, $5f20
.SECTION "ControlRecord162" FORCE
ControlRecord162:
.incbin "control_record_162.bin"
.ENDS
ROMBLOCK 22, $6612
.SECTION "ControlRecord163" FORCE
ControlRecord163:
.incbin "control_record_163.bin"
.ENDS
ROMBLOCK 22, $6d04
.SECTION "ControlRecord164" FORCE
ControlRecord164:
.incbin "control_record_164.bin"
.ENDS
ROMBLOCK 23, $0000
.SECTION "ControlRecord165" FORCE
ControlRecord165:
.incbin "control_record_165.bin"
.ENDS
ROMBLOCK 23, $10c4
.SECTION "ControlRecord166" FORCE
ControlRecord166:
.incbin "control_record_166.bin"
.ENDS
ROMBLOCK 23, $2188
.SECTION "ControlRecord167" FORCE
ControlRecord167:
.incbin "control_record_167.bin"
.ENDS
ROMBLOCK 23, $324c
.SECTION "ControlRecord168" FORCE
ControlRecord168:
.incbin "control_record_168.bin"
.ENDS
ROMBLOCK 23, $4310
.SECTION "ControlRecord169" FORCE
ControlRecord169:
.incbin "control_record_169.bin"
.ENDS
ROMBLOCK 23, $53d4
.SECTION "ControlRecord170" FORCE
ControlRecord170:
.incbin "control_record_170.bin"
.ENDS
ROMBLOCK 23, $6498
.SECTION "ControlRecord171" FORCE
ControlRecord171:
.incbin "control_record_171.bin"
.ENDS
ROMBLOCK 24, $0000
.SECTION "ControlRecord172" FORCE
ControlRecord172:
.incbin "control_record_172.bin"
.ENDS
ROMBLOCK 24, $10c4
.SECTION "ControlRecord173" FORCE
ControlRecord173:
.incbin "control_record_173.bin"
.ENDS
ROMBLOCK 24, $2188
.SECTION "ControlRecord174" FORCE
ControlRecord174:
.incbin "control_record_174.bin"
.ENDS
ROMBLOCK 24, $324c
.SECTION "ControlRecord175" FORCE
ControlRecord175:
.incbin "control_record_175.bin"
.ENDS
ROMBLOCK 24, $4310
.SECTION "ControlRecord176" FORCE
ControlRecord176:
.incbin "control_record_176.bin"
.ENDS
ROMBLOCK 24, $53d4
.SECTION "ControlRecord177" FORCE
ControlRecord177:
.incbin "control_record_177.bin"
.ENDS
ROMBLOCK 24, $6498
.SECTION "ControlRecord178" FORCE
ControlRecord178:
.incbin "control_record_178.bin"
.ENDS
ROMBLOCK 24, $6f84
.SECTION "ControlRecord179" FORCE
ControlRecord179:
.incbin "control_record_179.bin"
.ENDS
ROMBLOCK 25, $0000
.SECTION "ControlRecord180" FORCE
ControlRecord180:
.incbin "control_record_180.bin"
.ENDS
ROMBLOCK 25, $0aec
.SECTION "ControlRecord181" FORCE
ControlRecord181:
.incbin "control_record_181.bin"
.ENDS
ROMBLOCK 25, $15d8
.SECTION "ControlRecord182" FORCE
ControlRecord182:
.incbin "control_record_182.bin"
.ENDS
ROMBLOCK 25, $20c4
.SECTION "ControlRecord183" FORCE
ControlRecord183:
.incbin "control_record_183.bin"
.ENDS
ROMBLOCK 25, $2bb0
.SECTION "ControlRecord184" FORCE
ControlRecord184:
.incbin "control_record_184.bin"
.ENDS
ROMBLOCK 25, $369c
.SECTION "ControlRecord185" FORCE
ControlRecord185:
.incbin "control_record_185.bin"
.ENDS
ROMBLOCK 25, $4188
.SECTION "ControlRecord186" FORCE
ControlRecord186:
.incbin "control_record_186.bin"
.ENDS
ROMBLOCK 25, $4c74
.SECTION "ControlRecord187" FORCE
ControlRecord187:
.incbin "control_record_187.bin"
.ENDS
ROMBLOCK 25, $5760
.SECTION "ControlRecord188" FORCE
ControlRecord188:
.incbin "control_record_188.bin"
.ENDS
ROMBLOCK 25, $624c
.SECTION "ControlRecord189" FORCE
ControlRecord189:
.incbin "control_record_189.bin"
.ENDS
ROMBLOCK 26, $0000
.SECTION "ControlRecord190" FORCE
ControlRecord190:
.incbin "control_record_190.bin"
.ENDS
ROMBLOCK 26, $1920
.SECTION "ControlRecord191" FORCE
ControlRecord191:
.incbin "control_record_191.bin"
.ENDS
ROMBLOCK 26, $2650
.SECTION "ControlRecord192" FORCE
ControlRecord192:
.incbin "control_record_192.bin"
.ENDS
ROMBLOCK 26, $3380
.SECTION "ControlRecord193" FORCE
ControlRecord193:
.incbin "control_record_193.bin"
.ENDS
ROMBLOCK 26, $3e24
.SECTION "ControlRecord194" FORCE
ControlRecord194:
.incbin "control_record_194.bin"
.ENDS
ROMBLOCK 26, $48c8
.SECTION "ControlRecord195" FORCE
ControlRecord195:
.incbin "control_record_195.bin"
.ENDS
ROMBLOCK 26, $536c
.SECTION "ControlRecord196" FORCE
ControlRecord196:
.incbin "control_record_196.bin"
.ENDS
ROMBLOCK 26, $5e10
.SECTION "ControlRecord197" FORCE
ControlRecord197:
.incbin "control_record_197.bin"
.ENDS
ROMBLOCK 26, $68b4
.SECTION "ControlRecord198" FORCE
ControlRecord198:
.incbin "control_record_198.bin"
.ENDS
ROMBLOCK 26, $7358
.SECTION "ControlRecord199" FORCE
ControlRecord199:
.incbin "control_record_199.bin"
.ENDS
ROMBLOCK 27, $0000
.SECTION "ControlRecord200" FORCE
ControlRecord200:
.incbin "control_record_200.bin"
.ENDS
ROMBLOCK 27, $0aa4
.SECTION "ControlRecord201" FORCE
ControlRecord201:
.incbin "control_record_201.bin"
.ENDS
ROMBLOCK 27, $1548
.SECTION "ControlRecord202" FORCE
ControlRecord202:
.incbin "control_record_202.bin"
.ENDS
ROMBLOCK 27, $1fec
.SECTION "ControlRecord203" FORCE
ControlRecord203:
.incbin "control_record_203.bin"
.ENDS
ROMBLOCK 27, $2a90
.SECTION "ControlRecord204" FORCE
ControlRecord204:
.incbin "control_record_204.bin"
.ENDS
ROMBLOCK 27, $3534
.SECTION "ControlRecord205" FORCE
ControlRecord205:
.incbin "control_record_205.bin"
.ENDS
ROMBLOCK 27, $3fd8
.SECTION "ControlRecord206" FORCE
ControlRecord206:
.incbin "control_record_206.bin"
.ENDS
ROMBLOCK 27, $4a7c
.SECTION "ControlRecord207" FORCE
ControlRecord207:
.incbin "control_record_207.bin"
.ENDS
ROMBLOCK 27, $5520
.SECTION "ControlRecord208" FORCE
ControlRecord208:
.incbin "control_record_208.bin"
.ENDS
ROMBLOCK 27, $5fc4
.SECTION "ControlRecord209" FORCE
ControlRecord209:
.incbin "control_record_209.bin"
.ENDS
ROMBLOCK 27, $6a68
.SECTION "ControlRecord210" FORCE
ControlRecord210:
.incbin "control_record_210.bin"
.ENDS
ROMBLOCK 27, $750c
.SECTION "ControlRecord211" FORCE
ControlRecord211:
.incbin "control_record_211.bin"
.ENDS
ROMBLOCK 28, $0000
.SECTION "ControlRecord212" FORCE
ControlRecord212:
.incbin "control_record_212.bin"
.ENDS
ROMBLOCK 28, $0aa4
.SECTION "ControlRecord213" FORCE
ControlRecord213:
.incbin "control_record_213.bin"
.ENDS
ROMBLOCK 28, $1548
.SECTION "ControlRecord214" FORCE
ControlRecord214:
.incbin "control_record_214.bin"
.ENDS
ROMBLOCK 28, $1fec
.SECTION "ControlRecord215" FORCE
ControlRecord215:
.incbin "control_record_215.bin"
.ENDS
ROMBLOCK 28, $2a90
.SECTION "ControlRecord216" FORCE
ControlRecord216:
.incbin "control_record_216.bin"
.ENDS
ROMBLOCK 28, $3534
.SECTION "ControlRecord217" FORCE
ControlRecord217:
.incbin "control_record_217.bin"
.ENDS
ROMBLOCK 28, $3fd8
.SECTION "ControlRecord218" FORCE
ControlRecord218:
.incbin "control_record_218.bin"
.ENDS
ROMBLOCK 28, $48ea
.SECTION "ControlRecord219" FORCE
ControlRecord219:
.incbin "control_record_219.bin"
.ENDS
ROMBLOCK 28, $51fc
.SECTION "ControlRecord220" FORCE
ControlRecord220:
.incbin "control_record_220.bin"
.ENDS
ROMBLOCK 28, $5e34
.SECTION "ControlRecord221" FORCE
ControlRecord221:
.incbin "control_record_221.bin"
.ENDS
ROMBLOCK 28, $6a6c
.SECTION "ControlRecord222" FORCE
ControlRecord222:
.incbin "control_record_222.bin"
.ENDS
ROMBLOCK 29, $0000
.SECTION "ControlRecord223" FORCE
ControlRecord223:
.incbin "control_record_223.bin"
.ENDS
ROMBLOCK 29, $0c38
.SECTION "ControlRecord224" FORCE
ControlRecord224:
.incbin "control_record_224.bin"
.ENDS
ROMBLOCK 29, $154a
.SECTION "ControlRecord225" FORCE
ControlRecord225:
.incbin "control_record_225.bin"
.ENDS
ROMBLOCK 29, $2dd6
.SECTION "ControlRecord226" FORCE
ControlRecord226:
.incbin "control_record_226.bin"
.ENDS
ROMBLOCK 29, $4662
.SECTION "ControlRecord227" FORCE
ControlRecord227:
.incbin "control_record_227.bin"
.ENDS
ROMBLOCK 29, $5eee
.SECTION "ControlRecord228" FORCE
ControlRecord228:
.incbin "control_record_228.bin"
.ENDS
ROMBLOCK 30, $0000
.SECTION "ControlRecord229" FORCE
ControlRecord229:
.incbin "control_record_229.bin"
.ENDS
ROMBLOCK 30, $188c
.SECTION "ControlRecord230" FORCE
ControlRecord230:
.incbin "control_record_230.bin"
.ENDS
ROMBLOCK 30, $3118
.SECTION "ControlRecord231" FORCE
ControlRecord231:
.incbin "control_record_231.bin"
.ENDS
ROMBLOCK 30, $49a4
.SECTION "ControlRecord232" FORCE
ControlRecord232:
.incbin "control_record_232.bin"
.ENDS
ROMBLOCK 30, $6230
.SECTION "ControlRecord233" FORCE
ControlRecord233:
.incbin "control_record_233.bin"
.ENDS
ROMBLOCK 31, $0000
.SECTION "ControlRecord234" FORCE
ControlRecord234:
.incbin "control_record_234.bin"
.ENDS
ROMBLOCK 31, $188c
.SECTION "ControlRecord235" FORCE
ControlRecord235:
.incbin "control_record_235.bin"
.ENDS
ROMBLOCK 31, $3118
.SECTION "ControlRecord236" FORCE
ControlRecord236:
.incbin "control_record_236.bin"
.ENDS
ROMBLOCK 31, $49a4
.SECTION "ControlRecord237" FORCE
ControlRecord237:
.incbin "control_record_237.bin"
.ENDS
ROMBLOCK 31, $6230
.SECTION "ControlRecord238" FORCE
ControlRecord238:
.incbin "control_record_238.bin"
.ENDS
ROMBLOCK 32, $0000
.SECTION "ControlRecord239" FORCE
ControlRecord239:
.incbin "control_record_239.bin"
.ENDS
ROMBLOCK 32, $188c
.SECTION "ControlRecord240" FORCE
ControlRecord240:
.incbin "control_record_240.bin"
.ENDS
ROMBLOCK 32, $3118
.SECTION "ControlRecord241" FORCE
ControlRecord241:
.incbin "control_record_241.bin"
.ENDS
ROMBLOCK 32, $49a4
.SECTION "ControlRecord242" FORCE
ControlRecord242:
.incbin "control_record_242.bin"
.ENDS
ROMBLOCK 32, $6230
.SECTION "ControlRecord243" FORCE
ControlRecord243:
.incbin "control_record_243.bin"
.ENDS
ROMBLOCK 33, $0000
.SECTION "ControlRecord244" FORCE
ControlRecord244:
.incbin "control_record_244.bin"
.ENDS
ROMBLOCK 33, $188c
.SECTION "ControlRecord245" FORCE
ControlRecord245:
.incbin "control_record_245.bin"
.ENDS
ROMBLOCK 33, $3a24
.SECTION "ControlRecord246" FORCE
ControlRecord246:
.incbin "control_record_246.bin"
.ENDS
ROMBLOCK 33, $536c
.SECTION "ControlRecord247" FORCE
ControlRecord247:
.incbin "control_record_247.bin"
.ENDS
ROMBLOCK 33, $557a
.SECTION "ControlRecord248" FORCE
ControlRecord248:
.incbin "control_record_248.bin"
.ENDS
ROMBLOCK 33, $5f32
.SECTION "ControlRecord249" FORCE
ControlRecord249:
.incbin "control_record_249.bin"
.ENDS
ROMBLOCK 33, $68ea
.SECTION "ControlRecord250" FORCE
ControlRecord250:
.incbin "control_record_250.bin"
.ENDS
ROMBLOCK 33, $72a2
.SECTION "ControlRecord251" FORCE
ControlRecord251:
.incbin "control_record_251.bin"
.ENDS
ROMBLOCK 34, $0000
.SECTION "ControlRecord252" FORCE
ControlRecord252:
.incbin "control_record_252.bin"
.ENDS
ROMBLOCK 34, $09b8
.SECTION "ControlRecord253" FORCE
ControlRecord253:
.incbin "control_record_253.bin"
.ENDS
ROMBLOCK 34, $1448
.SECTION "ControlRecord254" FORCE
ControlRecord254:
.incbin "control_record_254.bin"
.ENDS
ROMBLOCK 34, $189a
.SECTION "ControlRecord255" FORCE
ControlRecord255:
.incbin "control_record_255.bin"
.ENDS
ROMBLOCK 34, $232a
.SECTION "ControlRecord256" FORCE
ControlRecord256:
.incbin "control_record_256.bin"
.ENDS
ROMBLOCK 34, $2dba
.SECTION "ControlRecord257" FORCE
ControlRecord257:
.incbin "control_record_257.bin"
.ENDS
ROMBLOCK 34, $384a
.SECTION "ControlRecord258" FORCE
ControlRecord258:
.incbin "control_record_258.bin"
.ENDS
ROMBLOCK 34, $42da
.SECTION "ControlRecord259" FORCE
ControlRecord259:
.incbin "control_record_259.bin"
.ENDS
ROMBLOCK 34, $4d6a
.SECTION "ControlRecord260" FORCE
ControlRecord260:
.incbin "control_record_260.bin"
.ENDS
ROMBLOCK 34, $57fa
.SECTION "ControlRecord261" FORCE
ControlRecord261:
.incbin "control_record_261.bin"
.ENDS
ROMBLOCK 34, $628a
.SECTION "ControlRecord262" FORCE
ControlRecord262:
.incbin "control_record_262.bin"
.ENDS
ROMBLOCK 34, $7086
.SECTION "ControlRecord263" FORCE
ControlRecord263:
.incbin "control_record_263.bin"
.ENDS
ROMBLOCK 35, $0000
.SECTION "ControlRecord264" FORCE
ControlRecord264:
.incbin "control_record_264.bin"
.ENDS
ROMBLOCK 35, $0dfc
.SECTION "ControlRecord265" FORCE
ControlRecord265:
.incbin "control_record_265.bin"
.ENDS
ROMBLOCK 35, $1bf8
.SECTION "ControlRecord266" FORCE
ControlRecord266:
.incbin "control_record_266.bin"
.ENDS
ROMBLOCK 35, $29f4
.SECTION "ControlRecord267" FORCE
ControlRecord267:
.incbin "control_record_267.bin"
.ENDS
ROMBLOCK 35, $2de4
.SECTION "ControlRecord268" FORCE
ControlRecord268:
.incbin "control_record_268.bin"
.ENDS
ROMBLOCK 35, $31d4
.SECTION "ControlRecord269" FORCE
ControlRecord269:
.incbin "control_record_269.bin"
.ENDS
ROMBLOCK 35, $35c4
.SECTION "ControlRecord270" FORCE
ControlRecord270:
.incbin "control_record_270.bin"
.ENDS
ROMBLOCK 35, $39b4
.SECTION "ControlRecord271" FORCE
ControlRecord271:
.incbin "control_record_271.bin"
.ENDS
ROMBLOCK 35, $3da4
.SECTION "ControlRecord272" FORCE
ControlRecord272:
.incbin "control_record_272.bin"
.ENDS
ROMBLOCK 35, $480c
.SECTION "ControlRecord273" FORCE
ControlRecord273:
.incbin "control_record_273.bin"
.ENDS
ROMBLOCK 35, $4a06
.SECTION "ControlRecord274" FORCE
ControlRecord274:
.incbin "control_record_274.bin"
.ENDS
ROMBLOCK 35, $6276
.SECTION "ControlRecord275" FORCE
ControlRecord275:
.incbin "control_record_275.bin"
.ENDS
ROMBLOCK 35, $7ae6
.SECTION "ControlRecord276" FORCE
ControlRecord276:
.incbin "control_record_276.bin"
.ENDS
ROMBLOCK 35, $7d08
.SECTION "ControlRecord277" FORCE
ControlRecord277:
.incbin "control_record_277.bin"
.ENDS
ROMBLOCK 36, $0000
.SECTION "ControlRecord278" FORCE
ControlRecord278:
.incbin "control_record_278.bin"
.ENDS
ROMBLOCK 36, $0222
.SECTION "ControlRecord279" FORCE
ControlRecord279:
.incbin "control_record_279.bin"
.ENDS
ROMBLOCK 36, $0444
.SECTION "ControlRecord280" FORCE
ControlRecord280:
.incbin "control_record_280.bin"
.ENDS
ROMBLOCK 36, $0666
.SECTION "ControlRecord281" FORCE
ControlRecord281:
.incbin "control_record_281.bin"
.ENDS
ROMBLOCK 36, $0888
.SECTION "ControlRecord282" FORCE
ControlRecord282:
.incbin "control_record_282.bin"
.ENDS
ROMBLOCK 36, $0aaa
.SECTION "ControlRecord283" FORCE
ControlRecord283:
.incbin "control_record_283.bin"
.ENDS
ROMBLOCK 36, $0ccc
.SECTION "ControlRecord284" FORCE
ControlRecord284:
.incbin "control_record_284.bin"
.ENDS
ROMBLOCK 36, $0eee
.SECTION "ControlRecord285" FORCE
ControlRecord285:
.incbin "control_record_285.bin"
.ENDS
ROMBLOCK 36, $1110
.SECTION "ControlRecord286" FORCE
ControlRecord286:
.incbin "control_record_286.bin"
.ENDS
ROMBLOCK 36, $1332
.SECTION "ControlRecord287" FORCE
ControlRecord287:
.incbin "control_record_287.bin"
.ENDS
ROMBLOCK 36, $1554
.SECTION "ControlRecord288" FORCE
ControlRecord288:
.incbin "control_record_288.bin"
.ENDS
ROMBLOCK 36, $1776
.SECTION "ControlRecord289" FORCE
ControlRecord289:
.incbin "control_record_289.bin"
.ENDS
ROMBLOCK 36, $1998
.SECTION "ControlRecord290" FORCE
ControlRecord290:
.incbin "control_record_290.bin"
.ENDS
ROMBLOCK 36, $1bba
.SECTION "ControlRecord291" FORCE
ControlRecord291:
.incbin "control_record_291.bin"
.ENDS
ROMBLOCK 36, $1ddc
.SECTION "ControlRecord292" FORCE
ControlRecord292:
.incbin "control_record_292.bin"
.ENDS
ROMBLOCK 36, $1ffe
.SECTION "ControlRecord293" FORCE
ControlRecord293:
.incbin "control_record_293.bin"
.ENDS
ROMBLOCK 36, $2220
.SECTION "ControlRecord294" FORCE
ControlRecord294:
.incbin "control_record_294.bin"
.ENDS
ROMBLOCK 36, $2442
.SECTION "ControlRecord295" FORCE
ControlRecord295:
.incbin "control_record_295.bin"
.ENDS
ROMBLOCK 36, $2664
.SECTION "ControlRecord296" FORCE
ControlRecord296:
.incbin "control_record_296.bin"
.ENDS
ROMBLOCK 36, $2886
.SECTION "ControlRecord297" FORCE
ControlRecord297:
.incbin "control_record_297.bin"
.ENDS
ROMBLOCK 36, $2aa8
.SECTION "ControlRecord298" FORCE
ControlRecord298:
.incbin "control_record_298.bin"
.ENDS
ROMBLOCK 36, $2cca
.SECTION "ControlRecord299" FORCE
ControlRecord299:
.incbin "control_record_299.bin"
.ENDS
ROMBLOCK 36, $2eec
.SECTION "ControlRecord300" FORCE
ControlRecord300:
.incbin "control_record_300.bin"
.ENDS
ROMBLOCK 36, $310e
.SECTION "ControlRecord301" FORCE
ControlRecord301:
.incbin "control_record_301.bin"
.ENDS
ROMBLOCK 36, $3330
.SECTION "ControlRecord302" FORCE
ControlRecord302:
.incbin "control_record_302.bin"
.ENDS
ROMBLOCK 36, $3552
.SECTION "ControlRecord303" FORCE
ControlRecord303:
.incbin "control_record_303.bin"
.ENDS
ROMBLOCK 36, $3774
.SECTION "ControlRecord304" FORCE
ControlRecord304:
.incbin "control_record_304.bin"
.ENDS
ROMBLOCK 36, $3996
.SECTION "ControlRecord305" FORCE
ControlRecord305:
.incbin "control_record_305.bin"
.ENDS
ROMBLOCK 36, $3bb8
.SECTION "ControlRecord306" FORCE
ControlRecord306:
.incbin "control_record_306.bin"
.ENDS
ROMBLOCK 36, $3dda
.SECTION "ControlRecord307" FORCE
ControlRecord307:
.incbin "control_record_307.bin"
.ENDS
ROMBLOCK 36, $3fd4
.SECTION "ControlRecord308" FORCE
ControlRecord308:
.incbin "control_record_308.bin"
.ENDS
ROMBLOCK 36, $41ce
.SECTION "ControlRecord309" FORCE
ControlRecord309:
.incbin "control_record_309.bin"
.ENDS
ROMBLOCK 36, $43c8
.SECTION "ControlRecord310" FORCE
ControlRecord310:
.incbin "control_record_310.bin"
.ENDS
ROMBLOCK 36, $45c2
.SECTION "ControlRecord311" FORCE
ControlRecord311:
.incbin "control_record_311.bin"
.ENDS
ROMBLOCK 36, $47bc
.SECTION "ControlRecord312" FORCE
ControlRecord312:
.incbin "control_record_312.bin"
.ENDS
ROMBLOCK 36, $49b6
.SECTION "ControlRecord313" FORCE
ControlRecord313:
.incbin "control_record_313.bin"
.ENDS
ROMBLOCK 36, $4bb0
.SECTION "ControlRecord314" FORCE
ControlRecord314:
.incbin "control_record_314.bin"
.ENDS
ROMBLOCK 36, $4daa
.SECTION "ControlRecord315" FORCE
ControlRecord315:
.incbin "control_record_315.bin"
.ENDS
ROMBLOCK 36, $4fa4
.SECTION "ControlRecord316" FORCE
ControlRecord316:
.incbin "control_record_316.bin"
.ENDS
ROMBLOCK 36, $519e
.SECTION "ControlRecord317" FORCE
ControlRecord317:
.incbin "control_record_317.bin"
.ENDS
ROMBLOCK 36, $5398
.SECTION "ControlRecord318" FORCE
ControlRecord318:
.incbin "control_record_318.bin"
.ENDS
ROMBLOCK 36, $5592
.SECTION "ControlRecord319" FORCE
ControlRecord319:
.incbin "control_record_319.bin"
.ENDS
ROMBLOCK 36, $578c
.SECTION "ControlRecord320" FORCE
ControlRecord320:
.incbin "control_record_320.bin"
.ENDS
ROMBLOCK 36, $5986
.SECTION "ControlRecord321" FORCE
ControlRecord321:
.incbin "control_record_321.bin"
.ENDS
ROMBLOCK 36, $5b80
.SECTION "ControlRecord322" FORCE
ControlRecord322:
.incbin "control_record_322.bin"
.ENDS
ROMBLOCK 36, $5d7a
.SECTION "ControlRecord323" FORCE
ControlRecord323:
.incbin "control_record_323.bin"
.ENDS
ROMBLOCK 36, $5f74
.SECTION "ControlRecord324" FORCE
ControlRecord324:
.incbin "control_record_324.bin"
.ENDS
ROMBLOCK 36, $616e
.SECTION "ControlRecord325" FORCE
ControlRecord325:
.incbin "control_record_325.bin"
.ENDS
ROMBLOCK 36, $6368
.SECTION "ControlRecord326" FORCE
ControlRecord326:
.incbin "control_record_326.bin"
.ENDS
ROMBLOCK 36, $6562
.SECTION "ControlRecord327" FORCE
ControlRecord327:
.incbin "control_record_327.bin"
.ENDS
ROMBLOCK 36, $675c
.SECTION "ControlRecord328" FORCE
ControlRecord328:
.incbin "control_record_328.bin"
.ENDS
ROMBLOCK 36, $6956
.SECTION "ControlRecord329" FORCE
ControlRecord329:
.incbin "control_record_329.bin"
.ENDS
ROMBLOCK 36, $6b50
.SECTION "ControlRecord330" FORCE
ControlRecord330:
.incbin "control_record_330.bin"
.ENDS
ROMBLOCK 36, $6d4a
.SECTION "ControlRecord331" FORCE
ControlRecord331:
.incbin "control_record_331.bin"
.ENDS
ROMBLOCK 36, $6f44
.SECTION "ControlRecord332" FORCE
ControlRecord332:
.incbin "control_record_332.bin"
.ENDS
ROMBLOCK 36, $713e
.SECTION "ControlRecord333" FORCE
ControlRecord333:
.incbin "control_record_333.bin"
.ENDS
ROMBLOCK 36, $7338
.SECTION "ControlRecord334" FORCE
ControlRecord334:
.incbin "control_record_334.bin"
.ENDS
ROMBLOCK 36, $7532
.SECTION "ControlRecord335" FORCE
ControlRecord335:
.incbin "control_record_335.bin"
.ENDS
ROMBLOCK 36, $772c
.SECTION "ControlRecord336" FORCE
ControlRecord336:
.incbin "control_record_336.bin"
.ENDS
ROMBLOCK 36, $7926
.SECTION "ControlRecord337" FORCE
ControlRecord337:
.incbin "control_record_337.bin"
.ENDS
ROMBLOCK 36, $7b20
.SECTION "ControlRecord338" FORCE
ControlRecord338:
.incbin "control_record_338.bin"
.ENDS
ROMBLOCK 36, $7d1e
.SECTION "ControlRecord339" FORCE
ControlRecord339:
.incbin "control_record_339.bin"
.ENDS
ROMBLOCK 37, $0000
.SECTION "ControlRecord340" FORCE
ControlRecord340:
.incbin "control_record_340.bin"
.ENDS
ROMBLOCK 37, $01fe
.SECTION "ControlRecord341" FORCE
ControlRecord341:
.incbin "control_record_341.bin"
.ENDS
ROMBLOCK 37, $03fc
.SECTION "ControlRecord342" FORCE
ControlRecord342:
.incbin "control_record_342.bin"
.ENDS
ROMBLOCK 37, $05fa
.SECTION "ControlRecord343" FORCE
ControlRecord343:
.incbin "control_record_343.bin"
.ENDS
ROMBLOCK 37, $07f8
.SECTION "ControlRecord344" FORCE
ControlRecord344:
.incbin "control_record_344.bin"
.ENDS
ROMBLOCK 37, $09f6
.SECTION "ControlRecord345" FORCE
ControlRecord345:
.incbin "control_record_345.bin"
.ENDS
ROMBLOCK 37, $0bf4
.SECTION "ControlRecord346" FORCE
ControlRecord346:
.incbin "control_record_346.bin"
.ENDS
ROMBLOCK 37, $0df2
.SECTION "ControlRecord347" FORCE
ControlRecord347:
.incbin "control_record_347.bin"
.ENDS
ROMBLOCK 37, $0ff0
.SECTION "ControlRecord348" FORCE
ControlRecord348:
.incbin "control_record_348.bin"
.ENDS
ROMBLOCK 37, $11ee
.SECTION "ControlRecord349" FORCE
ControlRecord349:
.incbin "control_record_349.bin"
.ENDS
ROMBLOCK 37, $13ec
.SECTION "ControlRecord350" FORCE
ControlRecord350:
.incbin "control_record_350.bin"
.ENDS
ROMBLOCK 37, $15ea
.SECTION "ControlRecord351" FORCE
ControlRecord351:
.incbin "control_record_351.bin"
.ENDS
ROMBLOCK 37, $17e8
.SECTION "ControlRecord352" FORCE
ControlRecord352:
.incbin "control_record_352.bin"
.ENDS
ROMBLOCK 37, $19e6
.SECTION "ControlRecord353" FORCE
ControlRecord353:
.incbin "control_record_353.bin"
.ENDS
ROMBLOCK 37, $1be4
.SECTION "ControlRecord354" FORCE
ControlRecord354:
.incbin "control_record_354.bin"
.ENDS
ROMBLOCK 37, $1de2
.SECTION "ControlRecord355" FORCE
ControlRecord355:
.incbin "control_record_355.bin"
.ENDS
ROMBLOCK 37, $1fe0
.SECTION "ControlRecord356" FORCE
ControlRecord356:
.incbin "control_record_356.bin"
.ENDS
ROMBLOCK 37, $21de
.SECTION "ControlRecord357" FORCE
ControlRecord357:
.incbin "control_record_357.bin"
.ENDS
ROMBLOCK 37, $23dc
.SECTION "ControlRecord358" FORCE
ControlRecord358:
.incbin "control_record_358.bin"
.ENDS
ROMBLOCK 37, $25da
.SECTION "ControlRecord359" FORCE
ControlRecord359:
.incbin "control_record_359.bin"
.ENDS
ROMBLOCK 37, $27d8
.SECTION "ControlRecord360" FORCE
ControlRecord360:
.incbin "control_record_360.bin"
.ENDS
ROMBLOCK 37, $29d6
.SECTION "ControlRecord361" FORCE
ControlRecord361:
.incbin "control_record_361.bin"
.ENDS
ROMBLOCK 37, $2bd4
.SECTION "ControlRecord362" FORCE
ControlRecord362:
.incbin "control_record_362.bin"
.ENDS
ROMBLOCK 37, $2dd2
.SECTION "ControlRecord363" FORCE
ControlRecord363:
.incbin "control_record_363.bin"
.ENDS
ROMBLOCK 37, $2fd0
.SECTION "ControlRecord364" FORCE
ControlRecord364:
.incbin "control_record_364.bin"
.ENDS
ROMBLOCK 37, $31ce
.SECTION "ControlRecord365" FORCE
ControlRecord365:
.incbin "control_record_365.bin"
.ENDS
ROMBLOCK 37, $33cc
.SECTION "ControlRecord366" FORCE
ControlRecord366:
.incbin "control_record_366.bin"
.ENDS
ROMBLOCK 37, $35ca
.SECTION "ControlRecord367" FORCE
ControlRecord367:
.incbin "control_record_367.bin"
.ENDS
ROMBLOCK 37, $37c8
.SECTION "ControlRecord368" FORCE
ControlRecord368:
.incbin "control_record_368.bin"
.ENDS
ROMBLOCK 37, $39c6
.SECTION "ControlRecord369" FORCE
ControlRecord369:
.incbin "control_record_369.bin"
.ENDS
ROMBLOCK 37, $3bc4
.SECTION "ControlRecord370" FORCE
ControlRecord370:
.incbin "control_record_370.bin"
.ENDS
ROMBLOCK 37, $3dc2
.SECTION "ControlRecord371" FORCE
ControlRecord371:
.incbin "control_record_371.bin"
.ENDS
ROMBLOCK 37, $3fc0
.SECTION "ControlRecord372" FORCE
ControlRecord372:
.incbin "control_record_372.bin"
.ENDS
ROMBLOCK 37, $41be
.SECTION "ControlRecord373" FORCE
ControlRecord373:
.incbin "control_record_373.bin"
.ENDS
ROMBLOCK 37, $43bc
.SECTION "ControlRecord374" FORCE
ControlRecord374:
.incbin "control_record_374.bin"
.ENDS
ROMBLOCK 37, $45ba
.SECTION "ControlRecord375" FORCE
ControlRecord375:
.incbin "control_record_375.bin"
.ENDS
ROMBLOCK 37, $47b8
.SECTION "ControlRecord376" FORCE
ControlRecord376:
.incbin "control_record_376.bin"
.ENDS
ROMBLOCK 37, $49b6
.SECTION "ControlRecord377" FORCE
ControlRecord377:
.incbin "control_record_377.bin"
.ENDS
ROMBLOCK 37, $4bb4
.SECTION "ControlRecord378" FORCE
ControlRecord378:
.incbin "control_record_378.bin"
.ENDS
ROMBLOCK 37, $4db2
.SECTION "ControlRecord379" FORCE
ControlRecord379:
.incbin "control_record_379.bin"
.ENDS
ROMBLOCK 37, $4fb0
.SECTION "ControlRecord380" FORCE
ControlRecord380:
.incbin "control_record_380.bin"
.ENDS
ROMBLOCK 37, $51ae
.SECTION "ControlRecord381" FORCE
ControlRecord381:
.incbin "control_record_381.bin"
.ENDS
ROMBLOCK 37, $53ac
.SECTION "ControlRecord382" FORCE
ControlRecord382:
.incbin "control_record_382.bin"
.ENDS
ROMBLOCK 37, $55aa
.SECTION "ControlRecord383" FORCE
ControlRecord383:
.incbin "control_record_383.bin"
.ENDS
ROMBLOCK 37, $57a8
.SECTION "ControlRecord384" FORCE
ControlRecord384:
.incbin "control_record_384.bin"
.ENDS
ROMBLOCK 37, $59a6
.SECTION "ControlRecord385" FORCE
ControlRecord385:
.incbin "control_record_385.bin"
.ENDS
ROMBLOCK 37, $5ba4
.SECTION "ControlRecord386" FORCE
ControlRecord386:
.incbin "control_record_386.bin"
.ENDS
ROMBLOCK 37, $5da2
.SECTION "ControlRecord387" FORCE
ControlRecord387:
.incbin "control_record_387.bin"
.ENDS
ROMBLOCK 37, $5fa0
.SECTION "ControlRecord388" FORCE
ControlRecord388:
.incbin "control_record_388.bin"
.ENDS
ROMBLOCK 37, $619e
.SECTION "ControlRecord389" FORCE
ControlRecord389:
.incbin "control_record_389.bin"
.ENDS
ROMBLOCK 37, $639c
.SECTION "ControlRecord390" FORCE
ControlRecord390:
.incbin "control_record_390.bin"
.ENDS
ROMBLOCK 37, $659a
.SECTION "ControlRecord391" FORCE
ControlRecord391:
.incbin "control_record_391.bin"
.ENDS
ROMBLOCK 37, $6798
.SECTION "ControlRecord392" FORCE
ControlRecord392:
.incbin "control_record_392.bin"
.ENDS
ROMBLOCK 37, $6996
.SECTION "ControlRecord393" FORCE
ControlRecord393:
.incbin "control_record_393.bin"
.ENDS
ROMBLOCK 37, $6b94
.SECTION "ControlRecord394" FORCE
ControlRecord394:
.incbin "control_record_394.bin"
.ENDS
ROMBLOCK 37, $6d92
.SECTION "ControlRecord395" FORCE
ControlRecord395:
.incbin "control_record_395.bin"
.ENDS
ROMBLOCK 37, $6f90
.SECTION "ControlRecord396" FORCE
ControlRecord396:
.incbin "control_record_396.bin"
.ENDS
ROMBLOCK 37, $718e
.SECTION "ControlRecord397" FORCE
ControlRecord397:
.incbin "control_record_397.bin"
.ENDS
ROMBLOCK 37, $738c
.SECTION "ControlRecord398" FORCE
ControlRecord398:
.incbin "control_record_398.bin"
.ENDS
ROMBLOCK 37, $758a
.SECTION "ControlRecord399" FORCE
ControlRecord399:
.incbin "control_record_399.bin"
.ENDS
