.DEFINE GENERAL_PROFILE_COUNT 8
GeneralProfileData:
.dw $0c80,$ff60,$ff60
.incbin "general_signature_sparkster.bin"
.dw $0590,$ff60,$ff60
.incbin "general_signature_toy_story.bin"
.dw $0550,$3200,$46a0
.incbin "general_signature_kirby.bin"
.dw $0550,$3200,$46a0
.incbin "general_signature_puyo.bin"
.dw $0b30,$03c0,$03c0
.incbin "general_signature_jissen.bin"
.dw $0b30,$03c0,$03c0
.incbin "general_signature_jissen_classic.bin"
.dw $02a0,$0f40,$0f40
.incbin "general_signature_battle_cars.bin"
.dw $0800,$d280,$d280
.incbin "general_signature_pac_man2.bin"
